window.MUNISTER = (() => {
  const assets = {
    sunflower: "assets/sunflower.jpg",
    pumpkinOil: "assets/pumpkin-seed-oil.jpg",
    honeyJar: "assets/honey-jar.jpg",
    herbalTea: "assets/herbal-tea.jpg",
    teaJar: "assets/tea-jar.jpg",
    raspberryJam: "assets/raspberry-jam.jpg",
    cherryJam: "assets/cherry-jam.jpg",
  };

  const languages = [
    { id: "uk", short: "UA", name: "Українська" },
    { id: "it", short: "IT", name: "Italiano" },
    { id: "en", short: "EN", name: "English" },
  ];

  const categoryCards = {
    uk: [
      { id: "oil", label: "Холодні олії", number: "01", tone: "gold", image: assets.pumpkinOil },
      { id: "honey", label: "Мед з пасік", number: "02", tone: "amber", image: assets.honeyJar },
      { id: "preserves", label: "Варення і конфітюри", number: "03", tone: "plum", image: assets.cherryJam },
      { id: "tea", label: "Карпатські чаї", number: "04", tone: "moss", image: assets.teaJar },
    ],
    en: [
      { id: "oil", label: "Cold-Pressed Oils", number: "01", tone: "gold", image: assets.pumpkinOil },
      { id: "honey", label: "Apiary Honey", number: "02", tone: "amber", image: assets.honeyJar },
      { id: "preserves", label: "Preserves & Jams", number: "03", tone: "plum", image: assets.cherryJam },
      { id: "tea", label: "Carpathian Teas", number: "04", tone: "moss", image: assets.teaJar },
    ],
    it: [
      { id: "oil", label: "Oli spremuti a freddo", number: "01", tone: "gold", image: assets.pumpkinOil },
      { id: "honey", label: "Mieli d'apiario", number: "02", tone: "amber", image: assets.honeyJar },
      { id: "preserves", label: "Confetture e conserve", number: "03", tone: "plum", image: assets.cherryJam },
      { id: "tea", label: "Tisane dei Carpazi", number: "04", tone: "moss", image: assets.teaJar },
    ],
  };

  const catalogBase = [
    {
      id: "sunflower-oil",
      cat: "oil",
      tone: "gold",
      tag: "bestseller",
      image: assets.sunflower,
      price: 385,
      rating: 4.9,
      reviews: 438,
      size: "250ml",
      sizes: [{ label: "250ml", price: 385 }, { label: "500ml", price: 690 }],
      lot: "SUN-26-04",
      shelf: { uk: "Найкраще протягом 12 міс.", en: "Best within 12 months", it: "Meglio entro 12 mesi" },
      harvest: { uk: "Пресування квітень 2026", en: "Pressed April 2026", it: "Spremitura aprile 2026" },
      region: { uk: "Кіровоградщина", en: "Kirovohrad region", it: "regione di Kirovohrad" },
      name: { uk: "Соняшникова олія першого пресу", en: "First-Press Sunflower Oil", it: "Olio di girasole di prima spremitura" },
      note: { uk: "тепла · горіхова · чиста", en: "warm · nutty · clean", it: "caldo · nocciolato · pulito" },
      desc: {
        uk: "Світла соняшникова олія з насіння нового врожаю. Для салатів, молодої картоплі та теплого хліба.",
        en: "A clear sunflower oil from the new harvest. Made for salads, warm potatoes, and a heel of bread.",
        it: "Un olio di girasole limpido del nuovo raccolto. Perfetto con insalate, patate calde e pane ancora tiepido.",
      },
      tasting: {
        uk: ["Насіння", "Пшениця", "Теплий горіх"],
        en: ["Seed", "Wheat", "Warm nut"],
        it: ["Semi", "Grano", "Noce calda"],
      },
      pairings: {
        uk: ["Варена картопля", "Огірки", "Помідори", "Гречка", "Житній хліб"],
        en: ["Boiled potatoes", "Cucumbers", "Tomatoes", "Buckwheat", "Rye bread"],
        it: ["Patate lesse", "Cetrioli", "Pomodori", "Grano saraceno", "Pane di segale"],
      },
      story: {
        uk: "Насіння сушиться м'яко, а олія йде у пляшку без зайвого нагріву, щоб зберегти м'який смак і сонячний аромат.",
        en: "The seeds are gently dried and pressed without extra heat so the oil keeps its sunny aroma and soft finish.",
        it: "I semi vengono asciugati con delicatezza e spremuti senza calore extra per conservare aroma solare e finale morbido.",
      },
      recipe: {
        uk: "Полийте нею молоду картоплю, кріп і сіль пластівцями.",
        en: "Finish baby potatoes with it, plus dill and flaky salt.",
        it: "Usatelo su patate novelle con aneto e sale in fiocchi.",
      },
    },
    {
      id: "pumpkin-oil",
      cat: "oil",
      tone: "moss",
      tag: "new",
      image: assets.pumpkinOil,
      price: 520,
      rating: 4.8,
      reviews: 221,
      size: "250ml",
      sizes: [{ label: "250ml", price: 520 }],
      lot: "PKN-26-03",
      shelf: { uk: "Найкраще протягом 10 міс.", en: "Best within 10 months", it: "Meglio entro 10 mesi" },
      harvest: { uk: "Пресування березень 2026", en: "Pressed March 2026", it: "Spremitura marzo 2026" },
      region: { uk: "Львівщина", en: "Lviv region", it: "regione di Leopoli" },
      name: { uk: "Гарбузова олія темного віджиму", en: "Dark Pumpkin Seed Oil", it: "Olio scuro di semi di zucca" },
      note: { uk: "густa · підсмажена · оксамитова", en: "dense · toasted · velvety", it: "denso · tostato · vellutato" },
      desc: {
        uk: "Темна, майже шоколадна гарбузова олія для буряків, козячого сиру та осінніх салатів.",
        en: "A deep pumpkin seed oil for beets, goat cheese, and autumn salads.",
        it: "Un olio intenso di semi di zucca per barbabietole, formaggio di capra e insalate d'autunno.",
      },
      tasting: {
        uk: ["Какао", "Підсмажене насіння", "Димок"],
        en: ["Cocoa", "Toasted seed", "Smoke"],
        it: ["Cacao", "Semi tostati", "Fumo"],
      },
      pairings: {
        uk: ["Буряк", "Козячий сир", "Запечений гарбуз", "Квасоля", "Листя салату"],
        en: ["Beets", "Goat cheese", "Roast squash", "Beans", "Leafy greens"],
        it: ["Barbabietole", "Formaggio di capra", "Zucca arrosto", "Fagioli", "Insalata verde"],
      },
      story: {
        uk: "Ми тримаємо її темною, щільною і майже десертною за відчуттям, але без краплі солодощів.",
        en: "We keep it dark, dense, and almost dessert-like in texture, while staying fully savory.",
        it: "La manteniamo scura, densa e quasi da dessert nella consistenza, pur restando totalmente sapida.",
      },
      recipe: {
        uk: "Спробуйте на печеному буряку з кисломолочним сиром.",
        en: "Try it over roasted beets with soft curd cheese.",
        it: "Provatelo su barbabietole arrosto con formaggio fresco.",
      },
    },
    {
      id: "linden-honey",
      cat: "honey",
      tone: "amber",
      tag: "bestseller",
      image: assets.honeyJar,
      price: 295,
      rating: 4.9,
      reviews: 352,
      size: "300g",
      sizes: [{ label: "300g", price: 295 }, { label: "500g", price: 430 }],
      lot: "LND-25-08",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка серпень 2025", en: "Harvested August 2025", it: "Raccolto agosto 2025" },
      region: { uk: "Полтавщина", en: "Poltava region", it: "regione di Poltava" },
      name: { uk: "Липовий мед", en: "Linden Blossom Honey", it: "Miele di tiglio" },
      note: { uk: "квітковий · свіжий · легкий", en: "floral · fresh · light", it: "floreale · fresco · leggero" },
      desc: {
        uk: "Прозорий мед з липового цвіту з м'якою ментоловою свіжістю та довгим чистим післясмаком.",
        en: "A clear linden honey with a cooling floral lift and a long, clean finish.",
        it: "Un miele di tiglio limpido con una freschezza floreale e finale pulito e lungo.",
      },
      tasting: {
        uk: ["Липовий цвіт", "М'ята", "Світлий віск"],
        en: ["Linden bloom", "Mint", "Pale wax"],
        it: ["Fiore di tiglio", "Menta", "Cera chiara"],
      },
      pairings: {
        uk: ["Сирники", "Творог", "Йогурт", "Тости", "Ромашковий чай"],
        en: ["Syrnyky", "Curd cheese", "Yogurt", "Toast", "Chamomile tea"],
        it: ["Syrnyky", "Formaggio fresco", "Yogurt", "Pane tostato", "Camomilla"],
      },
      story: {
        uk: "Пасіки стоять ближче до липових алей, тому мед виходить світлий і дуже чистий по аромату.",
        en: "The hives sit close to old linden alleys, so the honey stays pale and especially perfumed.",
        it: "Le arnie si trovano vicino ai filari di tigli, per questo il miele resta chiaro e molto profumato.",
      },
      recipe: {
        uk: "Полийте ним сирники та додайте дрібку морської солі.",
        en: "Drizzle it over syrnyky and finish with a pinch of sea salt.",
        it: "Versatelo sui syrnyky e completate con un pizzico di sale marino.",
      },
    },
    {
      id: "meadow-honey",
      cat: "honey",
      tone: "cream",
      image: assets.honeyJar,
      price: 275,
      rating: 4.7,
      reviews: 188,
      size: "300g",
      sizes: [{ label: "300g", price: 275 }],
      lot: "MDW-25-07",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка липень 2025", en: "Harvested July 2025", it: "Raccolto luglio 2025" },
      region: { uk: "Черкащина", en: "Cherkasy region", it: "regione di Cherkasy" },
      name: { uk: "Лучний мед", en: "Wild Meadow Honey", it: "Miele di prato" },
      note: { uk: "сонячний · багатоквітковий · м'який", en: "sunny · multifloral · gentle", it: "solare · multifloreale · morbido" },
      desc: {
        uk: "Мед зі змішаного цвіту степових трав. Щедрий, домашній і дуже універсальний на щодень.",
        en: "A multifloral meadow honey from steppe herbs. Generous, homey, and easy to use every day.",
        it: "Un miele multifloreale di erbe di prateria. Generoso, domestico e semplice da usare ogni giorno.",
      },
      tasting: {
        uk: ["Польові трави", "Пилок", "Сухе сіно"],
        en: ["Field herbs", "Pollen", "Dry hay"],
        it: ["Erbe di campo", "Polline", "Fieno secco"],
      },
      pairings: {
        uk: ["Каша", "Вершкове масло", "Млинці", "Яблука", "М'які сири"],
        en: ["Porridge", "Butter", "Crepes", "Apples", "Soft cheese"],
        it: ["Porridge", "Burro", "Crêpes", "Mele", "Formaggi morbidi"],
      },
      story: {
        uk: "Саме цей мед ми тримаємо для сніданків і для тостів, коли хочеться простого доброго смаку.",
        en: "This is the jar we keep for breakfast, toast, and the kind of sweetness that feels uncomplicated.",
        it: "È il vasetto che teniamo per la colazione, il pane tostato e una dolcezza semplice e piena.",
      },
      recipe: {
        uk: "Спробуйте з печеними яблуками та сметаною.",
        en: "Serve it with baked apples and cultured cream.",
        it: "Servitelo con mele al forno e panna acida.",
      },
    },
    {
      id: "cherry-varennya",
      cat: "preserves",
      tone: "plum",
      tag: "new",
      image: assets.cherryJam,
      price: 260,
      rating: 4.8,
      reviews: 149,
      size: "220g",
      sizes: [{ label: "220g", price: 260 }],
      lot: "CHR-25-06",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено червень 2025", en: "Cooked June 2025", it: "Preparata giugno 2025" },
      region: { uk: "Поділля", en: "Podillia", it: "Podolia" },
      name: { uk: "Варення з вишні", en: "Sour Cherry Preserve", it: "Confettura di amarene" },
      note: { uk: "кисле · рубінове · соковите", en: "tart · ruby · vivid", it: "acidulo · rubino · vivido" },
      desc: {
        uk: "Вишня залишається яскравою і трохи терпкою. Добре йде до сирників, круасанів і твердих сирів.",
        en: "Bright, tart cherry preserve for syrnyky, flaky pastries, and aged cheeses.",
        it: "Una confettura vivace e acidula di amarene per syrnyky, sfoglia e formaggi stagionati.",
      },
      tasting: {
        uk: ["Вишня", "Кісточка", "Червоне вино"],
        en: ["Cherry", "Stone fruit pit", "Red wine"],
        it: ["Amarena", "Nocciolo", "Vino rosso"],
      },
      pairings: {
        uk: ["Круасани", "Сирники", "Брі", "Паштет", "Чорний чай"],
        en: ["Croissants", "Syrnyky", "Brie", "Pâté", "Black tea"],
        it: ["Croissant", "Syrnyky", "Brie", "Paté", "Tè nero"],
      },
      story: {
        uk: "Тут ми залишаємо більше кислоти, ніж у класичних джемах, щоб смак був дорослішим і чистішим.",
        en: "We keep more acidity here than a typical jam, so it feels cleaner and more grown-up on the palate.",
        it: "Manteniamo più acidità rispetto a una marmellata classica, per un gusto più netto e maturo.",
      },
      recipe: {
        uk: "Додайте ложку до брі або густого йогурту.",
        en: "Spoon it onto brie or thick yogurt.",
        it: "Mettetene un cucchiaio su brie o yogurt denso.",
      },
    },
    {
      id: "sea-buckthorn",
      cat: "preserves",
      tone: "terra",
      image: assets.raspberryJam,
      price: 285,
      rating: 4.7,
      reviews: 107,
      size: "220g",
      sizes: [{ label: "220g", price: 285 }],
      lot: "SBT-25-10",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено жовтень 2025", en: "Cooked October 2025", it: "Preparata ottobre 2025" },
      region: { uk: "Прикарпаття", en: "Precarpathia", it: "Precarpazia" },
      name: { uk: "Обліпиховий конфітюр", en: "Sea Buckthorn Confiture", it: "Confettura di olivello spinoso" },
      note: { uk: "цитрусова · густа · бадьора", en: "citrusy · dense · vivid", it: "agrumata · densa · vivace" },
      desc: {
        uk: "Яскравий обліпиховий конфітюр з легкою кислинкою. Для тостів, каші та масляних бісквітів.",
        en: "A vivid sea buckthorn confiture with bright acidity for toast, porridge, and butter biscuits.",
        it: "Una confettura vivace di olivello con acidità brillante per pane tostato, porridge e biscotti al burro.",
      },
      tasting: {
        uk: ["Цедра", "Абрикос", "Мед"],
        en: ["Zest", "Apricot", "Honey"],
        it: ["Scorza", "Albicocca", "Miele"],
      },
      pairings: {
        uk: ["Грецький йогурт", "Панкейки", "Пісочне печиво", "Тости", "Теплий чай"],
        en: ["Greek yogurt", "Pancakes", "Shortbread", "Toast", "Warm tea"],
        it: ["Yogurt greco", "Pancake", "Frollini", "Pane tostato", "Tè caldo"],
      },
      story: {
        uk: "Обліпиха дає дуже впізнаваний смак, тому ми не перевантажуємо її спеціями чи ваніллю.",
        en: "Sea buckthorn is so distinctive that we keep the recipe stripped back and free of extra spice.",
        it: "L'olivello ha un gusto così riconoscibile che manteniamo la ricetta essenziale, senza spezie superflue.",
      },
      recipe: {
        uk: "Найкраще смакує з густим йогуртом і гранолою.",
        en: "Best over thick yogurt and granola.",
        it: "Rende al meglio su yogurt denso e granola.",
      },
    },
    {
      id: "carpathian-herbal-tea",
      cat: "tea",
      tone: "moss",
      tag: "bestseller",
      image: assets.herbalTea,
      price: 210,
      rating: 4.9,
      reviews: 301,
      size: "80g",
      sizes: [{ label: "80g", price: 210 }],
      lot: "CRP-26-02",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір лютий 2026", en: "Harvested February 2026", it: "Raccolta febbraio 2026" },
      region: { uk: "Карпати", en: "Carpathian Mountains", it: "Monti Carpazi" },
      name: { uk: "Карпатський трав'яний чай", en: "Carpathian Herbal Tea", it: "Tisana dei Carpazi" },
      note: { uk: "трав'яний · зелений · спокійний", en: "herbal · green · calming", it: "erbaceo · verde · distensivo" },
      desc: {
        uk: "Суміш м'яти, чебрецю, листя смородини та материнки. Добрий вечірній чай без зайвого шуму.",
        en: "Mint, thyme, currant leaf, and oregano in a calm evening blend.",
        it: "Menta, timo, foglia di ribes e origano in una miscela serale calma e profumata.",
      },
      tasting: {
        uk: ["М'ята", "Чебрець", "Луг"],
        en: ["Mint", "Thyme", "Meadow"],
        it: ["Menta", "Timo", "Prato"],
      },
      pairings: {
        uk: ["Мед", "Печиво", "Сирники", "Груша", "Темний шоколад"],
        en: ["Honey", "Biscuits", "Syrnyky", "Pear", "Dark chocolate"],
        it: ["Miele", "Biscotti", "Syrnyky", "Pera", "Cioccolato fondente"],
      },
      story: {
        uk: "Ми збираємо цей чай так, щоб у чашці було більше повітря, свіжості та гірського відчуття.",
        en: "We build this blend for lift and mountain freshness rather than perfume-heavy sweetness.",
        it: "Questa miscela è pensata per dare aria, freschezza e una sensazione di montagna nella tazza.",
      },
      recipe: {
        uk: "Залийте 85°C водою і дайте настоятися 4 хвилини.",
        en: "Steep at 85°C for 4 minutes.",
        it: "Infondete a 85°C per 4 minuti.",
      },
    },
    {
      id: "ivan-chai",
      cat: "tea",
      tone: "sage",
      image: assets.teaJar,
      price: 235,
      rating: 4.8,
      reviews: 164,
      size: "70g",
      sizes: [{ label: "70g", price: 235 }],
      lot: "IVN-26-01",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір січень 2026", en: "Harvested January 2026", it: "Raccolta gennaio 2026" },
      region: { uk: "Верховина", en: "Verkhovyna", it: "Verkhovyna" },
      name: { uk: "Іван-чай ферментований", en: "Fermented Ivan Chai", it: "Ivan chai fermentato" },
      note: { uk: "бурштиновий · сухофруктовий · м'який", en: "amber · dried fruit · soft", it: "ambrato · frutta secca · morbido" },
      desc: {
        uk: "Ферментований кіпрій з теплим сухофруктовим профілем. Затишний чай для довгих вечорів.",
        en: "Fermented fireweed with an amber, dried-fruit profile and a long soft finish.",
        it: "Fireweed fermentato con profilo ambrato di frutta secca e finale lungo e morbido.",
      },
      tasting: {
        uk: ["Курага", "Сіно", "Медовий лист"],
        en: ["Apricot", "Hay", "Honeyed leaf"],
        it: ["Albicocca secca", "Fieno", "Foglia mielata"],
      },
      pairings: {
        uk: ["Медівник", "Пісочне печиво", "Сухофрукти", "Груша", "Твердий сир"],
        en: ["Honey cake", "Shortbread", "Dried fruit", "Pear", "Firm cheese"],
        it: ["Torta al miele", "Frollini", "Frutta secca", "Pera", "Formaggio stagionato"],
      },
      story: {
        uk: "Це чай з повільним темпом: м'який, теплий, без різкості, але з довгим післясмаком.",
        en: "This is our slowest tea: warm, rounded, and long on the finish without becoming heavy.",
        it: "È la nostra tisana più lenta: calda, rotonda e persistente senza diventare pesante.",
      },
      recipe: {
        uk: "Добре заварюється повторно двічі.",
        en: "It takes a second steep beautifully.",
        it: "Regge benissimo anche una seconda infusione.",
      },
    },
  ];

  const ui = {
    uk: {
      metaTitle: "Munister — Сучасна українська крамниця смаку",
      currency: "₴",
      announcement: "Українські pantry-товари малими партіями · безкоштовна доставка від ₴1800",
      nav: { shop: "Крамниця", gifts: "Набори", story: "Історія", search: "Пошук", bag: "Кошик" },
      hero: {
        eyebrow: "Сучасна українська pantry-лінія",
        titleA: "Українські смаки,",
        titleB: "зібрані",
        titleC: "повільно.",
        body: "Холодні олії, мед з пасік, домашні конфітюри та карпатські чаї з новою, чистішою подачею. Більше України на полиці. Менше шуму в дизайні.",
        primary: "Відкрити крамницю",
        secondary: "Подивитись набори",
        stats: [
          ["8", "товарів малого тиражу"],
          ["4", "категорії нового pantry"],
          ["Made in UA", "у центрі історії"],
        ],
        cardEyebrow: "Українська pantry-полиця",
        cardTitle: "Теплі, виразні продукти для щоденного столу.",
        cardBody: "Від соняшникової олії до карпатського чаю — все зібрано у світліший і доросліший storefront.",
        image: assets.pumpkinOil,
      },
      home: {
        categoriesEyebrow: "Категорії",
        categoriesTitle: "Нова українська pantry-полиця.",
        shopAll: "Дивитись усе",
        bestEyebrow: "Бестселери",
        bestTitle: "Те, з чого починають.",
        founderEyebrow: "Погляд засновниці",
        founderQuote: "Ми хотіли, щоб українські продукти виглядали так само переконливо, як і смакували.",
        founderBody: "Munister тепер говорить мовою сучасної української pantry-культури: локальні товари, теплі кольори, чесний каталог і менше декоративного шуму.",
        founderName: "Команда Munister",
        founderRole: "Curation & pantry direction",
        newsletterEyebrow: "Суботній лист",
        newsletterTitle: "Один рецепт. Одна сезонна знахідка. Щосуботи.",
        newsletterBody: "Перший лист дає знижку 10% на перше замовлення.",
        newsletterPlaceholder: "you@kitchen.ua",
        newsletterCta: "Підписатись",
        newsletterDone: "Готово",
      },
      footer: {
        body: "Олії, мед, варення та чай з українським характером і спокійнішою візуальною мовою.",
        badges: ["Made in Ukraine", "Small Batch", "Gift Ready"],
        cols: [
          { title: "Крамниця", items: ["Олії", "Мед", "Варення", "Чаї"] },
          { title: "Дослідити", items: ["Набори", "Історія", "Бестселери", "Подарунки"] },
          { title: "Сервіс", items: ["Доставка", "Повернення", "Контакт", "FAQ"] },
        ],
        left: "© 2026 Munister · українська pantry-колекція",
        right: "Повільно зібрано · чесно подано",
      },
      search: {
        placeholder: "Шукати олію, мед, варення, чай…",
        try: "Спробуйте пошук",
        empty: "Нічого не знайдено",
        emptyBody: "Спробуйте «мед», «олія» або «чай».",
        results: "результатів",
        suggestions: ["олія", "мед", "варення", "чай", "вишня", "карпати"],
      },
      cart: {
        title: "Ваш кошик",
        freeShipping: "Безкоштовну доставку відкрито",
        away: "до безкоштовної доставки",
        emptyTitle: "Кошик порожній.",
        emptyBody: "Почніть з олій або чаю.",
        subtotal: "Разом",
        checkout: "Оформити",
        footer: "Малі партії · Подарункова подача · Український фокус",
      },
      shop: {
        eyebrow: "Повна колекція",
        title: "Купити колекцію.",
        body: "українських pantry-товарів з чистішою подачею і реальними фотографіями.",
        filters: [
          { id: "oil", label: "Олії" },
          { id: "honey", label: "Мед" },
          { id: "preserves", label: "Варення" },
          { id: "tea", label: "Чаї" },
        ],
        clear: "Очистити",
        sortLabel: "Сортування",
        sorts: {
          popular: "Популярні",
          rating: "Рейтинг",
          "price-asc": "Ціна: низька → висока",
          "price-desc": "Ціна: висока → низька",
        },
        add: "Додати",
        addBag: "У кошик",
        story: "Історія продукту",
        pairings: "Поєднання",
        reviews: "Відгуки",
        size: "Розмір",
        recipeIdea: "Ідея подачі",
        lotTrace: "Трасування партії",
        journeyTitle: "Від виробника до вашого столу.",
        journey: [
          { label: "Збір", date: "Сезонно", desc: "Сировина збирається в коротке сезонне вікно, без великих складських запасів." },
          { label: "Приготування", date: "Малі партії", desc: "Олії тиснемо, мед качаємо, варення варимо і чаї фасуємо невеликими серіями." },
          { label: "Настій смаку", date: "Без поспіху", desc: "Ми лишаємо продуктам їхню природну текстуру і не маскуємо їх надмірною обробкою." },
          { label: "Фасування", date: "Під партію", desc: "Кожна банка або пляшка маркується партією для зрозумілого походження." },
          { label: "Відправка", date: "1-3 дні", desc: "Комплектуємо замовлення вручну, щоб подарунковий вигляд не губився в дорозі." },
        ],
        storyHeading: "Чому це працює.",
        storyBody: "У кожному SKU ми зберегли смак локального продукту, але переодягнули його у cleaner retail-мову. Менше випадкових деталей, більше довіри до самого товару.",
        pairingsHeading: "Найкраще поєднується з.",
        pairingsBody: "Короткі підказки для столу, а не вигадані lofty-історії.",
        reviewsTitle: "Перевірені замовлення",
        reviewsSubtitle: "Що пишуть після першої банки або пляшки.",
        relatedEyebrow: "Ще спробувати",
        relatedTitle: "З цієї ж pantry-лінії.",
        stickyAdd: "Додати",
        added: "Додано",
        backHome: "Головна",
        backShop: "Крамниця",
      },
      gifts: {
        eyebrow: "Подарункові набори",
        title: "Українські смаки, зібрані в набір.",
        body: "Чесні комбінації з pantry-товарів, які не соромно дарувати.",
        occasion: "Нагода:",
        occasions: [
          { id: "all", label: "Усі" },
          { id: "host", label: "Для гостин" },
          { id: "cozy", label: "Для затишку" },
          { id: "sweet", label: "Для солодкого столу" },
        ],
        add: "Додати набір",
        noteTitle: "Додаємо картку з побажанням до кожного набору.",
        noteBody: "Коротке побажання впишемо вручну.",
        noteCta: "Усі набори",
      },
      storyPage: {
        eyebrow: "Наша історія",
        title: "Ми змістили фокус з «середземноморської мрії» на сучасний український pantry.",
        lead: "Тепер у центрі не стилізація під чужий ринок, а локальні товари, знайомі смаки і візуальна впевненість без провінційності.",
        founderEyebrow: "Чому це важливо",
        founderQuote: "Українські продукти заслуговують на таку ж сильну подачу, як і будь-який premium storefront у світі.",
        founderBody: "Ми взяли структуру clean editorial-commerce і наповнили її товарами, які ближчі до нашої кухні: соняшникова й гарбузова олія, мед, варення, трав'яні чаї. Так Munister відчувається переконливіше і чесніше.",
        timelineEyebrow: "Що змінилось",
        timelineTitle: "Чотири опори нового напряму.",
        milestones: [
          { year: "01", event: "Переключили сайт на українські товари, знайомі локальному покупцю." },
          { year: "02", event: "Додали живі зображення продуктів замість концептуальних заглушок." },
          { year: "03", event: "Вирівняли типографіку та прибрали зайві декоративні секції." },
          { year: "04", event: "Запустили багатомовність: українська, італійська, англійська." },
        ],
        valuesEyebrow: "Принципи",
        valuesTitle: "Що тримає цю сторінку разом.",
        values: [
          { icon: "◉", title: "Локальний центр", desc: "Товари і словник сайту тепер говорять з українського контексту, а не маскують його." },
          { icon: "◈", title: "Сильніша типографіка", desc: "Заголовки, кнопки і лейбли стали впевненішими, щоби сайт не виглядав кволо." },
          { icon: "◎", title: "Менше шуму", desc: "Ми відрізали блоки, які не допомагали купівлі і лише відтягували увагу." },
          { icon: "○", title: "Справжні фото", desc: "Продукт тепер показаний реально, а не через абстрактні рендери чи stripes." },
        ],
      },
      toasts: {
        added: "Додано до кошика",
        saved: "збережено",
      },
      common: {
        remove: "Прибрати",
        explore: "Дивитись",
        read: "Читати",
        noResults: "Немає результатів",
      },
      reviews: [
        { name: "Олена К.", loc: "Київ", ago: "2 тижні тому", text: "Нарешті український storefront, який не виглядає як ярмарок. І продукти теж чесні." },
        { name: "Марко С.", loc: "Львів", ago: "1 місяць тому", text: "Гарбузова олія дуже сильна. Сайт теж став дорослішим на вигляд." },
        { name: "Ірина Т.", loc: "Дніпро", ago: "3 тижні тому", text: "Чай і мед взяла на подарунок, і саме подача тут вже працює на рішення." },
      ],
      giftBundles: [
        { id: "host", occasions: ["all", "host"], tone: "gold", image: assets.pumpkinOil, price: 980, saving: 120, name: "Набір для гостин", desc: "Соняшникова олія, липовий мед і вишневе варення.", items: ["Соняшникова олія", "Липовий мед", "Варення з вишні"] },
        { id: "cozy", occasions: ["all", "cozy"], tone: "moss", image: assets.teaJar, price: 760, saving: 90, name: "Теплий вечір", desc: "Карпатський чай, іван-чай і лучний мед.", items: ["Карпатський чай", "Іван-чай", "Лучний мед"] },
        { id: "sweet", occasions: ["all", "sweet"], tone: "plum", image: assets.cherryJam, price: 720, saving: 75, name: "Солодкий стіл", desc: "Вишневе варення, обліпиховий конфітюр і липовий мед.", items: ["Варення з вишні", "Обліпиховий конфітюр", "Липовий мед"] },
        { id: "pantry", occasions: ["all", "host", "cozy"], tone: "cream", image: assets.sunflower, price: 1420, saving: 180, name: "Стартова pantry-коробка", desc: "Дві олії, мед і чай для першого великого замовлення.", items: ["Соняшникова олія", "Гарбузова олія", "Липовий мед", "Карпатський чай"] },
      ],
    },
    en: {
      metaTitle: "Munister — The Modern Ukrainian Pantry",
      currency: "₴",
      announcement: "Modern Ukrainian pantry goods · free shipping from ₴1800",
      nav: { shop: "Shop", gifts: "Gifts", story: "Story", search: "Search", bag: "Bag" },
      hero: {
        eyebrow: "A modern Ukrainian pantry line",
        titleA: "Ukrainian flavors,",
        titleB: "gathered",
        titleC: "slowly.",
        body: "Cold-pressed oils, apiary honey, home-style preserves, and Carpathian teas with a cleaner, more confident point of view. More Ukraine on the shelf. Less noise in the design.",
        primary: "Open the pantry",
        secondary: "See gift sets",
        stats: [
          ["8", "small-batch goods"],
          ["4", "new pantry categories"],
          ["Made in UA", "at the center"],
        ],
        cardEyebrow: "A Ukrainian pantry shelf",
        cardTitle: "Warm, expressive products for the everyday table.",
        cardBody: "From sunflower oil to mountain tea, everything is now framed as a calmer, more premium storefront.",
        image: assets.pumpkinOil,
      },
      home: {
        categoriesEyebrow: "Categories",
        categoriesTitle: "The new Ukrainian pantry shelf.",
        shopAll: "Shop all",
        bestEyebrow: "Best sellers",
        bestTitle: "Where most people begin.",
        founderEyebrow: "Founder's angle",
        founderQuote: "We wanted Ukrainian products to look as convincing as they taste.",
        founderBody: "Munister now speaks in the language of a modern Ukrainian pantry: local goods, warmer colors, a more honest catalog, and far less decorative noise.",
        founderName: "Munister Team",
        founderRole: "Curation & pantry direction",
        newsletterEyebrow: "The Saturday letter",
        newsletterTitle: "One recipe. One seasonal find. Every Saturday.",
        newsletterBody: "The first email unlocks 10% off your first order.",
        newsletterPlaceholder: "you@kitchen.com",
        newsletterCta: "Subscribe",
        newsletterDone: "Done",
      },
      footer: {
        body: "Oils, honey, preserves, and tea with a Ukrainian center of gravity and a calmer design language.",
        badges: ["Made in Ukraine", "Small Batch", "Gift Ready"],
        cols: [
          { title: "Shop", items: ["Oils", "Honey", "Preserves", "Tea"] },
          { title: "Explore", items: ["Gift sets", "Our story", "Best sellers", "Giving"] },
          { title: "Help", items: ["Shipping", "Returns", "Contact", "FAQ"] },
        ],
        left: "© 2026 Munister · Ukrainian pantry collection",
        right: "Assembled slowly · presented honestly",
      },
      search: {
        placeholder: "Search oils, honey, preserves, tea…",
        try: "Try searching for",
        empty: "No results found",
        emptyBody: "Try “honey”, “oil”, or “tea”.",
        results: "results",
        suggestions: ["oil", "honey", "preserve", "tea", "cherry", "carpathian"],
      },
      cart: {
        title: "Your bag",
        freeShipping: "Free shipping unlocked",
        away: "away from free shipping",
        emptyTitle: "Your bag is empty.",
        emptyBody: "Start with the oils or the teas.",
        subtotal: "Subtotal",
        checkout: "Checkout",
        footer: "Small batch · Gift-ready · Ukrainian focus",
      },
      shop: {
        eyebrow: "The full collection",
        title: "Shop the collection.",
        body: "Ukrainian pantry goods with a clearer point of view and real photography.",
        filters: [
          { id: "oil", label: "Oils" },
          { id: "honey", label: "Honey" },
          { id: "preserves", label: "Preserves" },
          { id: "tea", label: "Tea" },
        ],
        clear: "Clear",
        sortLabel: "Sort",
        sorts: {
          popular: "Most popular",
          rating: "Top rated",
          "price-asc": "Price: low → high",
          "price-desc": "Price: high → low",
        },
        add: "Add",
        addBag: "Add to bag",
        story: "Story",
        pairings: "Pairings",
        reviews: "Reviews",
        size: "Size",
        recipeIdea: "Serving idea",
        lotTrace: "Lot traceability",
        journeyTitle: "From producer to your table.",
        journey: [
          { label: "Harvest", date: "Seasonal", desc: "Ingredients are gathered in a short seasonal window rather than from anonymous year-round stock." },
          { label: "Make", date: "Small batch", desc: "We press oils, spin honey, cook preserves, and pack tea in deliberately small runs." },
          { label: "Settle", date: "No rush", desc: "Products keep their natural texture and are not over-processed into sameness." },
          { label: "Pack", date: "By lot", desc: "Every jar and bottle is packed with a lot code so the origin stays legible." },
          { label: "Ship", date: "1-3 days", desc: "Orders are assembled by hand so the shelf-ready finish survives the trip." },
        ],
        storyHeading: "Why it works.",
        storyBody: "Each SKU keeps its local identity, but the storefront now frames it with a more composed retail voice. Less noise, more trust in the product itself.",
        pairingsHeading: "Best with.",
        pairingsBody: "Short, useful table cues instead of over-written brand theater.",
        reviewsTitle: "Verified orders",
        reviewsSubtitle: "What people say after the first jar or bottle.",
        relatedEyebrow: "Try next",
        relatedTitle: "From the same pantry line.",
        stickyAdd: "Add",
        added: "Added",
        backHome: "Home",
        backShop: "Shop",
      },
      gifts: {
        eyebrow: "Gift sets",
        title: "Ukrainian flavors, boxed well.",
        body: "Straightforward pantry bundles that feel generous without trying too hard.",
        occasion: "Occasion:",
        occasions: [
          { id: "all", label: "All" },
          { id: "host", label: "Hosting" },
          { id: "cozy", label: "Cozy nights" },
          { id: "sweet", label: "Sweet table" },
        ],
        add: "Add set",
        noteTitle: "Every gift set includes a handwritten note card.",
        noteBody: "We add your message by hand.",
        noteCta: "All gift sets",
      },
      storyPage: {
        eyebrow: "Our story",
        title: "We shifted the center away from a borrowed Mediterranean fantasy and toward a modern Ukrainian pantry.",
        lead: "The point now is not to imitate someone else's market, but to frame local goods with more confidence, clarity, and respect.",
        founderEyebrow: "Why it matters",
        founderQuote: "Ukrainian products deserve the same strength of presentation as any premium storefront anywhere.",
        founderBody: "We kept the clean editorial-commerce structure, but filled it with goods closer to our own kitchen: sunflower and pumpkin seed oils, honey, preserves, and herbal teas. That makes Munister feel truer and stronger at the same time.",
        timelineEyebrow: "What changed",
        timelineTitle: "Four pillars of the reset.",
        milestones: [
          { year: "01", event: "We replaced the catalog with Ukrainian pantry goods that feel familiar and believable." },
          { year: "02", event: "We added real product photography instead of relying on concept placeholders." },
          { year: "03", event: "We tightened the typography and removed sections that only made the page busier." },
          { year: "04", event: "We launched the experience in Ukrainian, Italian, and English." },
        ],
        valuesEyebrow: "Principles",
        valuesTitle: "What holds the page together.",
        values: [
          { icon: "◉", title: "Local at the center", desc: "The catalog and copy now speak from a Ukrainian context instead of disguising it." },
          { icon: "◈", title: "Stronger typography", desc: "Headlines, labels, and buttons were made denser and more self-assured." },
          { icon: "◎", title: "Less noise", desc: "We cut sections that distracted from buying rather than helping it." },
          { icon: "○", title: "Real photos", desc: "The products are now shown as products, not as abstract placeholder patterns." },
        ],
      },
      toasts: {
        added: "Added to bag",
        saved: "saved",
      },
      common: {
        remove: "Remove",
        explore: "Explore",
        read: "Read",
        noResults: "No results",
      },
      reviews: [
        { name: "Olena K.", loc: "Kyiv", ago: "2 weeks ago", text: "Finally a Ukrainian storefront that doesn't feel like a craft fair. The products are honest too." },
        { name: "Marko S.", loc: "Lviv", ago: "1 month ago", text: "The pumpkin seed oil is excellent. The site now looks properly grown up as well." },
        { name: "Iryna T.", loc: "Dnipro", ago: "3 weeks ago", text: "I bought tea and honey as a gift, and the presentation here already does half the work." },
      ],
      giftBundles: [
        { id: "host", occasions: ["all", "host"], tone: "gold", image: assets.pumpkinOil, price: 980, saving: 120, name: "The Host Table", desc: "Sunflower oil, linden honey, and sour cherry preserve.", items: ["Sunflower oil", "Linden honey", "Sour cherry preserve"] },
        { id: "cozy", occasions: ["all", "cozy"], tone: "moss", image: assets.teaJar, price: 760, saving: 90, name: "Warm Evening", desc: "Carpathian herbal tea, ivan chai, and meadow honey.", items: ["Carpathian herbal tea", "Ivan chai", "Wild meadow honey"] },
        { id: "sweet", occasions: ["all", "sweet"], tone: "plum", image: assets.cherryJam, price: 720, saving: 75, name: "Sweet Table", desc: "Cherry preserve, sea buckthorn confiture, and linden honey.", items: ["Sour cherry preserve", "Sea buckthorn confiture", "Linden honey"] },
        { id: "pantry", occasions: ["all", "host", "cozy"], tone: "cream", image: assets.sunflower, price: 1420, saving: 180, name: "Starter Pantry Box", desc: "Two oils, a honey, and a tea to begin with.", items: ["Sunflower oil", "Pumpkin seed oil", "Linden honey", "Carpathian herbal tea"] },
      ],
    },
    it: {
      metaTitle: "Munister — La dispensa ucraina contemporanea",
      currency: "₴",
      announcement: "Prodotti da dispensa ucraini contemporanei · spedizione gratuita da ₴1800",
      nav: { shop: "Negozio", gifts: "Regali", story: "Storia", search: "Cerca", bag: "Borsa" },
      hero: {
        eyebrow: "Una dispensa ucraina contemporanea",
        titleA: "Sapori ucraini,",
        titleB: "raccolti",
        titleC: "con calma.",
        body: "Oli spremuti a freddo, mieli d'apiario, conserve fatte in casa e tisane dei Carpazi con un punto di vista più pulito e deciso. Più Ucraina sullo scaffale, meno rumore nel design.",
        primary: "Apri la dispensa",
        secondary: "Vedi i set regalo",
        stats: [
          ["8", "prodotti small batch"],
          ["4", "categorie dispensa"],
          ["Made in UA", "al centro"],
        ],
        cardEyebrow: "Una dispensa ucraina",
        cardTitle: "Prodotti caldi e espressivi per la tavola di ogni giorno.",
        cardBody: "Dall'olio di girasole alle tisane di montagna, tutto è presentato come uno storefront più calmo e credibile.",
        image: assets.pumpkinOil,
      },
      home: {
        categoriesEyebrow: "Categorie",
        categoriesTitle: "Il nuovo scaffale della dispensa ucraina.",
        shopAll: "Vedi tutto",
        bestEyebrow: "Più scelti",
        bestTitle: "Da dove si comincia.",
        founderEyebrow: "Sguardo curatoriale",
        founderQuote: "Volevamo che i prodotti ucraini apparissero forti quanto il loro sapore.",
        founderBody: "Ora Munister parla il linguaggio di una dispensa ucraina moderna: prodotti locali, colori più caldi, catalogo più onesto e molto meno rumore decorativo.",
        founderName: "Team Munister",
        founderRole: "Curation & pantry direction",
        newsletterEyebrow: "La lettera del sabato",
        newsletterTitle: "Una ricetta. Una scoperta stagionale. Ogni sabato.",
        newsletterBody: "La prima email sblocca il 10% sul primo ordine.",
        newsletterPlaceholder: "you@kitchen.it",
        newsletterCta: "Iscriviti",
        newsletterDone: "Fatto",
      },
      footer: {
        body: "Oli, miele, conserve e tè con un baricentro ucraino e una lingua visiva più tranquilla.",
        badges: ["Made in Ukraine", "Small Batch", "Gift Ready"],
        cols: [
          { title: "Negozio", items: ["Oli", "Mieli", "Conserve", "Tisane"] },
          { title: "Esplora", items: ["Set regalo", "La storia", "Più scelti", "Regali"] },
          { title: "Servizio", items: ["Spedizione", "Resi", "Contatti", "FAQ"] },
        ],
        left: "© 2026 Munister · collezione dispensa ucraina",
        right: "Assemblata con calma · presentata con onestà",
      },
      search: {
        placeholder: "Cerca oli, miele, conserve, tè…",
        try: "Prova a cercare",
        empty: "Nessun risultato",
        emptyBody: "Prova con “miele”, “olio” oppure “tè”.",
        results: "risultati",
        suggestions: ["olio", "miele", "conserve", "tè", "ciliegia", "carpazi"],
      },
      cart: {
        title: "La tua borsa",
        freeShipping: "Spedizione gratuita sbloccata",
        away: "mancano alla spedizione gratuita",
        emptyTitle: "La borsa è vuota.",
        emptyBody: "Inizia dagli oli o dalle tisane.",
        subtotal: "Totale parziale",
        checkout: "Checkout",
        footer: "Piccole serie · Pronto per regalo · Focus ucraino",
      },
      shop: {
        eyebrow: "La collezione completa",
        title: "Acquista la collezione.",
        body: "Prodotti di dispensa ucraini con un linguaggio più chiaro e fotografie reali.",
        filters: [
          { id: "oil", label: "Oli" },
          { id: "honey", label: "Mieli" },
          { id: "preserves", label: "Conserve" },
          { id: "tea", label: "Tisane" },
        ],
        clear: "Pulisci",
        sortLabel: "Ordina",
        sorts: {
          popular: "Più popolari",
          rating: "Più votati",
          "price-asc": "Prezzo: basso → alto",
          "price-desc": "Prezzo: alto → basso",
        },
        add: "Aggiungi",
        addBag: "Aggiungi alla borsa",
        story: "Storia",
        pairings: "Abbinamenti",
        reviews: "Recensioni",
        size: "Formato",
        recipeIdea: "Idea di servizio",
        lotTrace: "Tracciabilità lotto",
        journeyTitle: "Dal produttore alla tua tavola.",
        journey: [
          { label: "Raccolta", date: "Stagionale", desc: "Gli ingredienti vengono raccolti in una breve finestra stagionale invece che da stock anonimi." },
          { label: "Preparazione", date: "Piccole serie", desc: "Spremiamo, invasettiamo e confezioniamo in quantità contenute." },
          { label: "Riposo", date: "Senza fretta", desc: "Manteniamo texture e carattere naturale senza lavorazioni eccessive." },
          { label: "Confezione", date: "Per lotto", desc: "Ogni vaso e bottiglia porta un lotto leggibile e tracciabile." },
          { label: "Spedizione", date: "1-3 giorni", desc: "Gli ordini vengono assemblati a mano per mantenere la qualità visiva del pack." },
        ],
        storyHeading: "Perché funziona.",
        storyBody: "Ogni SKU mantiene identità locale, ma la cornice ora è più composta e retail-ready. Meno rumore, più fiducia nel prodotto.",
        pairingsHeading: "Sta benissimo con.",
        pairingsBody: "Suggerimenti brevi e utili, non teatro di brand.",
        reviewsTitle: "Ordini verificati",
        reviewsSubtitle: "Cosa dicono dopo il primo vasetto o la prima bottiglia.",
        relatedEyebrow: "Prova anche",
        relatedTitle: "Dalla stessa linea dispensa.",
        stickyAdd: "Aggiungi",
        added: "Aggiunto",
        backHome: "Home",
        backShop: "Negozio",
      },
      gifts: {
        eyebrow: "Set regalo",
        title: "Sapori ucraini, ben confezionati.",
        body: "Combinazioni semplici e curate che risultano generose senza forzature.",
        occasion: "Occasione:",
        occasions: [
          { id: "all", label: "Tutti" },
          { id: "host", label: "Per ospiti" },
          { id: "cozy", label: "Sera lenta" },
          { id: "sweet", label: "Tavola dolce" },
        ],
        add: "Aggiungi set",
        noteTitle: "Ogni set include un biglietto scritto a mano.",
        noteBody: "Aggiungiamo il tuo messaggio manualmente.",
        noteCta: "Tutti i set",
      },
      storyPage: {
        eyebrow: "La nostra storia",
        title: "Abbiamo spostato il centro da un'immaginazione mediterranea presa in prestito a una dispensa ucraina contemporanea.",
        lead: "L'obiettivo non è imitare un altro mercato, ma dare ai prodotti locali una cornice più sicura, nitida e rispettosa.",
        founderEyebrow: "Perché conta",
        founderQuote: "I prodotti ucraini meritano la stessa forza di presentazione di qualsiasi storefront premium.",
        founderBody: "Abbiamo mantenuto la struttura editoriale-commerce, ma l'abbiamo riempita con prodotti più vicini alla nostra cucina: oli di girasole e di semi di zucca, miele, conserve e tisane. Così Munister risulta più vero e più forte.",
        timelineEyebrow: "Cosa è cambiato",
        timelineTitle: "Quattro pilastri del reset.",
        milestones: [
          { year: "01", event: "Il catalogo è diventato una dispensa ucraina credibile e riconoscibile." },
          { year: "02", event: "Abbiamo sostituito i placeholder con fotografia di prodotto reale." },
          { year: "03", event: "Abbiamo irrobustito la tipografia e rimosso sezioni superflue." },
          { year: "04", event: "L'esperienza è ora in ucraino, italiano e inglese." },
        ],
        valuesEyebrow: "Principi",
        valuesTitle: "Cosa tiene insieme la pagina.",
        values: [
          { icon: "◉", title: "Locale al centro", desc: "Catalogo e copy parlano ora da un contesto ucraino invece di nasconderlo." },
          { icon: "◈", title: "Tipografia più forte", desc: "Titoli, label e bottoni sono più densi e sicuri." },
          { icon: "◎", title: "Meno rumore", desc: "Abbiamo tagliato le sezioni che distraevano dall'acquisto." },
          { icon: "○", title: "Foto vere", desc: "Il prodotto viene mostrato come prodotto, non come pattern astratto." },
        ],
      },
      toasts: {
        added: "Aggiunto alla borsa",
        saved: "salvato",
      },
      common: {
        remove: "Rimuovi",
        explore: "Esplora",
        read: "Leggi",
        noResults: "Nessun risultato",
      },
      reviews: [
        { name: "Elena K.", loc: "Kyiv", ago: "2 settimane fa", text: "Finalmente uno storefront ucraino che non sembra un mercatino. Anche i prodotti sono onesti." },
        { name: "Marco S.", loc: "Lviv", ago: "1 mese fa", text: "L'olio di semi di zucca è ottimo. Il sito adesso sembra davvero più adulto." },
        { name: "Iryna T.", loc: "Dnipro", ago: "3 settimane fa", text: "Ho preso tè e miele per un regalo e qui la presentazione aiuta già moltissimo." },
      ],
      giftBundles: [
        { id: "host", occasions: ["all", "host"], tone: "gold", image: assets.pumpkinOil, price: 980, saving: 120, name: "Tavola per ospiti", desc: "Olio di girasole, miele di tiglio e confettura di amarene.", items: ["Olio di girasole", "Miele di tiglio", "Confettura di amarene"] },
        { id: "cozy", occasions: ["all", "cozy"], tone: "moss", image: assets.teaJar, price: 760, saving: 90, name: "Sera lenta", desc: "Tisana dei Carpazi, ivan chai e miele di prato.", items: ["Tisana dei Carpazi", "Ivan chai", "Miele di prato"] },
        { id: "sweet", occasions: ["all", "sweet"], tone: "plum", image: assets.cherryJam, price: 720, saving: 75, name: "Tavola dolce", desc: "Confettura di amarene, olivello spinoso e miele di tiglio.", items: ["Confettura di amarene", "Confiture di olivello", "Miele di tiglio"] },
        { id: "pantry", occasions: ["all", "host", "cozy"], tone: "cream", image: assets.sunflower, price: 1420, saving: 180, name: "Scatola dispensa starter", desc: "Due oli, un miele e una tisana per iniziare bene.", items: ["Olio di girasole", "Olio di semi di zucca", "Miele di tiglio", "Tisana dei Carpazi"] },
      ],
    },
  };

  function formatPrice(value) {
    return `₴${Number(value).toLocaleString("uk-UA")}`;
  }

  function getProducts(lang) {
    const active = ui[lang] ? lang : "uk";
    return catalogBase.map((item) => ({
      ...item,
      name: item.name[active],
      note: item.note[active],
      desc: item.desc[active],
      region: item.region[active],
      harvest: item.harvest[active],
      shelf: item.shelf[active],
      tasting: item.tasting[active],
      pairings: item.pairings[active],
      story: item.story[active],
      recipe: item.recipe[active],
      tag: item.tag
        ? (item.tag === "bestseller"
          ? (active === "uk" ? "Хіт" : active === "it" ? "Più scelto" : "Bestseller")
          : (active === "uk" ? "Нове" : active === "it" ? "Novità" : "New"))
        : "",
    }));
  }

  function getCopy(lang) {
    return ui[lang] || ui.uk;
  }

  function getCategoryCards(lang) {
    return categoryCards[lang] || categoryCards.uk;
  }

  return {
    assets,
    languages,
    formatPrice,
    getCopy,
    getProducts,
    getCategoryCards,
    defaultLang: "uk",
  };
})();
