window.MUNISTER = (() => {
  const assets = {
    sunflower: "assets/sunflower.jpg",
    sunflowerOilBottle: "assets/sunflower-oil-bottle.jpg",
    pumpkinOil: "assets/pumpkin-seed-oil.jpg",
    linseedOil: "assets/linseed-oil.jpg",
    honeyJar: "assets/honey-jar.jpg",
    honeyDip: "assets/honey-dipper.jpg",
    acaciaHoney: "assets/acacia-honey.jpg",
    herbalTea: "assets/herbal-tea.jpg",
    teaJar: "assets/tea-jar.jpg",
    chamomileTea: "assets/chamomile-tea.jpg",
    raspberryJam: "assets/raspberry-jam.jpg",
    cherryJam: "assets/cherry-jam.jpg",
    buckwheatHoney: "assets/buckwheat-honey.jpg",
    walnutOil: "assets/walnut-oil.jpg",
    hempOil: "assets/hemp-oil.jpg",
    strawberryJam: "assets/strawberry-jam.jpg",
    apricotJam: "assets/apricot-jam.jpg",
    mintTea: "assets/mint-tea.jpg",
    rosehipTea: "assets/rosehip-tea.jpg",
    blueberryJam: "assets/blueberry-jam.jpg",
  };

  const languages = [
    { id: "uk", short: "UA", name: "Українська" },
    { id: "it", short: "IT", name: "Italiano" },
    { id: "en", short: "EN", name: "English" },
  ];

  const categoryCards = {
    uk: [
      { id: "oil", label: "Холодні олії", number: "01", tone: "gold", image: assets.sunflowerOilBottle },
      { id: "honey", label: "Мед з пасік", number: "02", tone: "amber", image: assets.honeyJar },
      { id: "preserves", label: "Варення і конфітюри", number: "03", tone: "plum", image: assets.blueberryJam },
      { id: "tea", label: "Карпатські чаї", number: "04", tone: "moss", image: assets.chamomileTea },
    ],
    en: [
      { id: "oil", label: "Cold-Pressed Oils", number: "01", tone: "gold", image: assets.sunflowerOilBottle },
      { id: "honey", label: "Apiary Honey", number: "02", tone: "amber", image: assets.honeyJar },
      { id: "preserves", label: "Preserves & Jams", number: "03", tone: "plum", image: assets.blueberryJam },
      { id: "tea", label: "Carpathian Teas", number: "04", tone: "moss", image: assets.chamomileTea },
    ],
    it: [
      { id: "oil", label: "Oli spremuti a freddo", number: "01", tone: "gold", image: assets.sunflowerOilBottle },
      { id: "honey", label: "Mieli d'apiario", number: "02", tone: "amber", image: assets.honeyJar },
      { id: "preserves", label: "Confetture e conserve", number: "03", tone: "plum", image: assets.blueberryJam },
      { id: "tea", label: "Tisane dei Carpazi", number: "04", tone: "moss", image: assets.chamomileTea },
    ],
  };

  const catalogBase = [
    {
      id: "sunflower-oil",
      cat: "oil",
      tone: "gold",
      tag: "bestseller",
      image: assets.sunflowerOilBottle,
      price: 385,
      rating: 4.9,
      reviews: 438,
      size: "250ml",
      sizes: [{ label: "250ml", price: 385 }, { label: "500ml", price: 690 }],
      lot: "SUN-26-04",
      shelf: { uk: "Найкраще протягом 12 міс.", en: "Best within 12 months", it: "Meglio entro 12 mesi" },
      harvest: { uk: "Пресування квітень 2026", en: "Pressed April 2026", it: "Spremitura aprile 2026" },
      region: { uk: "Кіровоградщина", en: "Kirovohrad region", it: "regione di Kirovohrad" },
      name: { uk: "Соняшникова олія першого пресу", en: "First-Press Sunflower Oil", it: "Olio di girasole di prima spremitura" },
      note: { uk: "тепла · горіхова · чиста", en: "warm · nutty · clean", it: "caldo · nocciolato · pulito" },
      desc: {
        uk: "Світла соняшникова олія з насіння нового врожаю. Для салатів, молодої картоплі та теплого хліба.",
        en: "A clear sunflower oil from the new harvest. Made for salads, warm potatoes, and a heel of bread.",
        it: "Un olio di girasole limpido del nuovo raccolto. Perfetto con insalate, patate calde e pane ancora tiepido.",
      },
      tasting: {
        uk: ["Насіння", "Пшениця", "Теплий горіх"],
        en: ["Seed", "Wheat", "Warm nut"],
        it: ["Semi", "Grano", "Noce calda"],
      },
      pairings: {
        uk: ["Варена картопля", "Огірки", "Помідори", "Гречка", "Житній хліб"],
        en: ["Boiled potatoes", "Cucumbers", "Tomatoes", "Buckwheat", "Rye bread"],
        it: ["Patate lesse", "Cetrioli", "Pomodori", "Grano saraceno", "Pane di segale"],
      },
      story: {
        uk: "Насіння сушиться м'яко, а олія йде у пляшку без зайвого нагріву, щоб зберегти м'який смак і сонячний аромат.",
        en: "The seeds are gently dried and pressed without extra heat so the oil keeps its sunny aroma and soft finish.",
        it: "I semi vengono asciugati con delicatezza e spremuti senza calore extra per conservare aroma solare e finale morbido.",
      },
      recipe: {
        uk: "Полийте нею молоду картоплю, кріп і сіль пластівцями.",
        en: "Finish baby potatoes with it, plus dill and flaky salt.",
        it: "Usatelo su patate novelle con aneto e sale in fiocchi.",
      },
    },
    {
      id: "pumpkin-oil",
      cat: "oil",
      tone: "moss",
      tag: "new",
      image: assets.pumpkinOil,
      price: 520,
      rating: 4.8,
      reviews: 221,
      size: "250ml",
      sizes: [{ label: "250ml", price: 520 }],
      lot: "PKN-26-03",
      shelf: { uk: "Найкраще протягом 10 міс.", en: "Best within 10 months", it: "Meglio entro 10 mesi" },
      harvest: { uk: "Пресування березень 2026", en: "Pressed March 2026", it: "Spremitura marzo 2026" },
      region: { uk: "Львівщина", en: "Lviv region", it: "regione di Leopoli" },
      name: { uk: "Гарбузова олія темного віджиму", en: "Dark Pumpkin Seed Oil", it: "Olio scuro di semi di zucca" },
      note: { uk: "густa · підсмажена · оксамитова", en: "dense · toasted · velvety", it: "denso · tostato · vellutato" },
      desc: {
        uk: "Темна, майже шоколадна гарбузова олія для буряків, козячого сиру та осінніх салатів.",
        en: "A deep pumpkin seed oil for beets, goat cheese, and autumn salads.",
        it: "Un olio intenso di semi di zucca per barbabietole, formaggio di capra e insalate d'autunno.",
      },
      tasting: {
        uk: ["Какао", "Підсмажене насіння", "Димок"],
        en: ["Cocoa", "Toasted seed", "Smoke"],
        it: ["Cacao", "Semi tostati", "Fumo"],
      },
      pairings: {
        uk: ["Буряк", "Козячий сир", "Запечений гарбуз", "Квасоля", "Листя салату"],
        en: ["Beets", "Goat cheese", "Roast squash", "Beans", "Leafy greens"],
        it: ["Barbabietole", "Formaggio di capra", "Zucca arrosto", "Fagioli", "Insalata verde"],
      },
      story: {
        uk: "Ми тримаємо її темною, щільною і майже десертною за відчуттям, але без краплі солодощів.",
        en: "We keep it dark, dense, and almost dessert-like in texture, while staying fully savory.",
        it: "La manteniamo scura, densa e quasi da dessert nella consistenza, pur restando totalmente sapida.",
      },
      recipe: {
        uk: "Спробуйте на печеному буряку з кисломолочним сиром.",
        en: "Try it over roasted beets with soft curd cheese.",
        it: "Provatelo su barbabietole arrosto con formaggio fresco.",
      },
    },
    {
      id: "linden-honey",
      cat: "honey",
      tone: "amber",
      tag: "bestseller",
      image: assets.honeyJar,
      price: 295,
      rating: 4.9,
      reviews: 352,
      size: "300g",
      sizes: [{ label: "300g", price: 295 }, { label: "500g", price: 430 }],
      lot: "LND-25-08",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка серпень 2025", en: "Harvested August 2025", it: "Raccolto agosto 2025" },
      region: { uk: "Полтавщина", en: "Poltava region", it: "regione di Poltava" },
      name: { uk: "Липовий мед", en: "Linden Blossom Honey", it: "Miele di tiglio" },
      note: { uk: "квітковий · свіжий · легкий", en: "floral · fresh · light", it: "floreale · fresco · leggero" },
      desc: {
        uk: "Прозорий мед з липового цвіту з м'якою ментоловою свіжістю та довгим чистим післясмаком.",
        en: "A clear linden honey with a cooling floral lift and a long, clean finish.",
        it: "Un miele di tiglio limpido con una freschezza floreale e finale pulito e lungo.",
      },
      tasting: {
        uk: ["Липовий цвіт", "М'ята", "Світлий віск"],
        en: ["Linden bloom", "Mint", "Pale wax"],
        it: ["Fiore di tiglio", "Menta", "Cera chiara"],
      },
      pairings: {
        uk: ["Сирники", "Творог", "Йогурт", "Тости", "Ромашковий чай"],
        en: ["Syrnyky", "Curd cheese", "Yogurt", "Toast", "Chamomile tea"],
        it: ["Syrnyky", "Formaggio fresco", "Yogurt", "Pane tostato", "Camomilla"],
      },
      story: {
        uk: "Пасіки стоять ближче до липових алей, тому мед виходить світлий і дуже чистий по аромату.",
        en: "The hives sit close to old linden alleys, so the honey stays pale and especially perfumed.",
        it: "Le arnie si trovano vicino ai filari di tigli, per questo il miele resta chiaro e molto profumato.",
      },
      recipe: {
        uk: "Полийте ним сирники та додайте дрібку морської солі.",
        en: "Drizzle it over syrnyky and finish with a pinch of sea salt.",
        it: "Versatelo sui syrnyky e completate con un pizzico di sale marino.",
      },
    },
    {
      id: "meadow-honey",
      cat: "honey",
      tone: "cream",
      image: assets.honeyDip,
      price: 275,
      rating: 4.7,
      reviews: 188,
      size: "300g",
      sizes: [{ label: "300g", price: 275 }],
      lot: "MDW-25-07",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка липень 2025", en: "Harvested July 2025", it: "Raccolto luglio 2025" },
      region: { uk: "Черкащина", en: "Cherkasy region", it: "regione di Cherkasy" },
      name: { uk: "Лучний мед", en: "Wild Meadow Honey", it: "Miele di prato" },
      note: { uk: "сонячний · багатоквітковий · м'який", en: "sunny · multifloral · gentle", it: "solare · multifloreale · morbido" },
      desc: {
        uk: "Мед зі змішаного цвіту степових трав. Щедрий, домашній і дуже універсальний на щодень.",
        en: "A multifloral meadow honey from steppe herbs. Generous, homey, and easy to use every day.",
        it: "Un miele multifloreale di erbe di prateria. Generoso, domestico e semplice da usare ogni giorno.",
      },
      tasting: {
        uk: ["Польові трави", "Пилок", "Сухе сіно"],
        en: ["Field herbs", "Pollen", "Dry hay"],
        it: ["Erbe di campo", "Polline", "Fieno secco"],
      },
      pairings: {
        uk: ["Каша", "Вершкове масло", "Млинці", "Яблука", "М'які сири"],
        en: ["Porridge", "Butter", "Crepes", "Apples", "Soft cheese"],
        it: ["Porridge", "Burro", "Crêpes", "Mele", "Formaggi morbidi"],
      },
      story: {
        uk: "Саме цей мед ми тримаємо для сніданків і для тостів, коли хочеться простого доброго смаку.",
        en: "This is the jar we keep for breakfast, toast, and the kind of sweetness that feels uncomplicated.",
        it: "È il vasetto che teniamo per la colazione, il pane tostato e una dolcezza semplice e piena.",
      },
      recipe: {
        uk: "Спробуйте з печеними яблуками та сметаною.",
        en: "Serve it with baked apples and cultured cream.",
        it: "Servitelo con mele al forno e panna acida.",
      },
    },
    {
      id: "cherry-varennya",
      cat: "preserves",
      tone: "plum",
      tag: "new",
      image: assets.cherryJam,
      price: 260,
      rating: 4.8,
      reviews: 149,
      size: "220g",
      sizes: [{ label: "220g", price: 260 }],
      lot: "CHR-25-06",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено червень 2025", en: "Cooked June 2025", it: "Preparata giugno 2025" },
      region: { uk: "Поділля", en: "Podillia", it: "Podolia" },
      name: { uk: "Варення з вишні", en: "Sour Cherry Preserve", it: "Confettura di amarene" },
      note: { uk: "кисле · рубінове · соковите", en: "tart · ruby · vivid", it: "acidulo · rubino · vivido" },
      desc: {
        uk: "Вишня залишається яскравою і трохи терпкою. Добре йде до сирників, круасанів і твердих сирів.",
        en: "Bright, tart cherry preserve for syrnyky, flaky pastries, and aged cheeses.",
        it: "Una confettura vivace e acidula di amarene per syrnyky, sfoglia e formaggi stagionati.",
      },
      tasting: {
        uk: ["Вишня", "Кісточка", "Червоне вино"],
        en: ["Cherry", "Stone fruit pit", "Red wine"],
        it: ["Amarena", "Nocciolo", "Vino rosso"],
      },
      pairings: {
        uk: ["Круасани", "Сирники", "Брі", "Паштет", "Чорний чай"],
        en: ["Croissants", "Syrnyky", "Brie", "Pâté", "Black tea"],
        it: ["Croissant", "Syrnyky", "Brie", "Paté", "Tè nero"],
      },
      story: {
        uk: "Тут ми залишаємо більше кислоти, ніж у класичних джемах, щоб смак був дорослішим і чистішим.",
        en: "We keep more acidity here than a typical jam, so it feels cleaner and more grown-up on the palate.",
        it: "Manteniamo più acidità rispetto a una marmellata classica, per un gusto più netto e maturo.",
      },
      recipe: {
        uk: "Додайте ложку до брі або густого йогурту.",
        en: "Spoon it onto brie or thick yogurt.",
        it: "Mettetene un cucchiaio su brie o yogurt denso.",
      },
    },
    {
      id: "sea-buckthorn",
      cat: "preserves",
      tone: "terra",
      image: assets.raspberryJam,
      price: 285,
      rating: 4.7,
      reviews: 107,
      size: "220g",
      sizes: [{ label: "220g", price: 285 }],
      lot: "SBT-25-10",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено жовтень 2025", en: "Cooked October 2025", it: "Preparata ottobre 2025" },
      region: { uk: "Прикарпаття", en: "Precarpathia", it: "Precarpazia" },
      name: { uk: "Обліпиховий конфітюр", en: "Sea Buckthorn Confiture", it: "Confettura di olivello spinoso" },
      note: { uk: "цитрусова · густа · бадьора", en: "citrusy · dense · vivid", it: "agrumata · densa · vivace" },
      desc: {
        uk: "Яскравий обліпиховий конфітюр з легкою кислинкою. Для тостів, каші та масляних бісквітів.",
        en: "A vivid sea buckthorn confiture with bright acidity for toast, porridge, and butter biscuits.",
        it: "Una confettura vivace di olivello con acidità brillante per pane tostato, porridge e biscotti al burro.",
      },
      tasting: {
        uk: ["Цедра", "Абрикос", "Мед"],
        en: ["Zest", "Apricot", "Honey"],
        it: ["Scorza", "Albicocca", "Miele"],
      },
      pairings: {
        uk: ["Грецький йогурт", "Панкейки", "Пісочне печиво", "Тости", "Теплий чай"],
        en: ["Greek yogurt", "Pancakes", "Shortbread", "Toast", "Warm tea"],
        it: ["Yogurt greco", "Pancake", "Frollini", "Pane tostato", "Tè caldo"],
      },
      story: {
        uk: "Обліпиха дає дуже впізнаваний смак, тому ми не перевантажуємо її спеціями чи ваніллю.",
        en: "Sea buckthorn is so distinctive that we keep the recipe stripped back and free of extra spice.",
        it: "L'olivello ha un gusto così riconoscibile che manteniamo la ricetta essenziale, senza spezie superflue.",
      },
      recipe: {
        uk: "Найкраще смакує з густим йогуртом і гранолою.",
        en: "Best over thick yogurt and granola.",
        it: "Rende al meglio su yogurt denso e granola.",
      },
    },
    {
      id: "carpathian-herbal-tea",
      cat: "tea",
      tone: "moss",
      tag: "bestseller",
      image: assets.herbalTea,
      price: 210,
      rating: 4.9,
      reviews: 301,
      size: "80g",
      sizes: [{ label: "80g", price: 210 }],
      lot: "CRP-26-02",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір лютий 2026", en: "Harvested February 2026", it: "Raccolta febbraio 2026" },
      region: { uk: "Карпати", en: "Carpathian Mountains", it: "Monti Carpazi" },
      name: { uk: "Карпатський трав'яний чай", en: "Carpathian Herbal Tea", it: "Tisana dei Carpazi" },
      note: { uk: "трав'яний · зелений · спокійний", en: "herbal · green · calming", it: "erbaceo · verde · distensivo" },
      desc: {
        uk: "Суміш м'яти, чебрецю, листя смородини та материнки. Добрий вечірній чай без зайвого шуму.",
        en: "Mint, thyme, currant leaf, and oregano in a calm evening blend.",
        it: "Menta, timo, foglia di ribes e origano in una miscela serale calma e profumata.",
      },
      tasting: {
        uk: ["М'ята", "Чебрець", "Луг"],
        en: ["Mint", "Thyme", "Meadow"],
        it: ["Menta", "Timo", "Prato"],
      },
      pairings: {
        uk: ["Мед", "Печиво", "Сирники", "Груша", "Темний шоколад"],
        en: ["Honey", "Biscuits", "Syrnyky", "Pear", "Dark chocolate"],
        it: ["Miele", "Biscotti", "Syrnyky", "Pera", "Cioccolato fondente"],
      },
      story: {
        uk: "Ми збираємо цей чай так, щоб у чашці було більше повітря, свіжості та гірського відчуття.",
        en: "We build this blend for lift and mountain freshness rather than perfume-heavy sweetness.",
        it: "Questa miscela è pensata per dare aria, freschezza e una sensazione di montagna nella tazza.",
      },
      recipe: {
        uk: "Залийте 85°C водою і дайте настоятися 4 хвилини.",
        en: "Steep at 85°C for 4 minutes.",
        it: "Infondete a 85°C per 4 minuti.",
      },
    },
    {
      id: "linseed-oil",
      cat: "oil",
      tone: "sage",
      tag: "new",
      image: assets.linseedOil,
      price: 410,
      rating: 4.7,
      reviews: 96,
      size: "250ml",
      sizes: [{ label: "250ml", price: 410 }],
      lot: "FLX-26-02",
      shelf: { uk: "Найкраще протягом 8 міс.", en: "Best within 8 months", it: "Meglio entro 8 mesi" },
      harvest: { uk: "Пресування лютий 2026", en: "Pressed February 2026", it: "Spremitura febbraio 2026" },
      region: { uk: "Волинь", en: "Volyn region", it: "regione di Volinia" },
      name: { uk: "Лляна олія", en: "Cold-Pressed Linseed Oil", it: "Olio di lino spremuto a freddo" },
      note: { uk: "трав'яниста · свіжа · делікатна", en: "grassy · fresh · delicate", it: "erbaceo · fresco · delicato" },
      desc: {
        uk: "Легка лляна олія з чистим зерновим профілем. Працює там, де потрібна свіжість, а не важка маслянистість.",
        en: "A lighter linseed oil with a clean cereal profile. Best where you want freshness rather than weight.",
        it: "Un olio di lino più leggero, con profilo pulito e cereale. Ideale quando serve freschezza, non pesantezza.",
      },
      tasting: {
        uk: ["Льон", "Трава", "Горіхова шкірка"],
        en: ["Flax", "Grass", "Nut skin"],
        it: ["Lino", "Erba", "Pelle di noce"],
      },
      pairings: {
        uk: ["Творог", "Салат з редиски", "Авокадо", "Каша", "Цільнозерновий тост"],
        en: ["Curd cheese", "Radish salad", "Avocado", "Porridge", "Wholegrain toast"],
        it: ["Formaggio fresco", "Insalata di ravanelli", "Avocado", "Porridge", "Pane integrale tostato"],
      },
      story: {
        uk: "Ми лишаємо цю олію дуже прямою за смаком, без ароматичних домішок і без зайвої важкості.",
        en: "We keep this oil direct and clean, without masking its flax character with anything extra.",
        it: "Manteniamo quest'olio diretto e pulito, senza coprire il carattere del lino con aggiunte superflue.",
      },
      recipe: {
        uk: "Спробуйте з творогом, зеленню та теплою картоплею.",
        en: "Try it with curd cheese, herbs, and warm potatoes.",
        it: "Provatelo con formaggio fresco, erbe e patate tiepide.",
      },
    },
    {
      id: "acacia-honey",
      cat: "honey",
      tone: "amber",
      tag: "new",
      image: assets.acaciaHoney,
      price: 320,
      rating: 4.8,
      reviews: 118,
      size: "300g",
      sizes: [{ label: "300g", price: 320 }, { label: "500g", price: 470 }],
      lot: "ACA-25-06",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка червень 2025", en: "Harvested June 2025", it: "Raccolto giugno 2025" },
      region: { uk: "Вінниччина", en: "Vinnytsia region", it: "regione di Vinnytsia" },
      name: { uk: "Акацієвий мед", en: "Acacia Honey", it: "Miele d'acacia" },
      note: { uk: "світлий · квітковий · прозорий", en: "pale · floral · clear", it: "chiaro · floreale · limpido" },
      desc: {
        uk: "Делікатний прозорий мед для тих, хто любить легший квітковий стиль без надмірної щільності.",
        en: "A delicate, clear honey for people who want a lighter floral style without extra density.",
        it: "Un miele delicato e limpido per chi cerca uno stile floreale più leggero, senza eccessiva densità.",
      },
      tasting: {
        uk: ["Біла акація", "Легкий віск", "Квітковий пилок"],
        en: ["White acacia", "Light wax", "Flower pollen"],
        it: ["Acacia bianca", "Cera chiara", "Polline"],
      },
      pairings: {
        uk: ["Рікота", "Йогурт", "Тости", "Млинці", "Ромашковий чай"],
        en: ["Ricotta", "Yogurt", "Toast", "Pancakes", "Chamomile tea"],
        it: ["Ricotta", "Yogurt", "Pane tostato", "Pancake", "Camomilla"],
      },
      story: {
        uk: "Це мед для світлих сніданків і спокійних поєднань, де не хочеться, щоб солодкість усе забивала.",
        en: "This is the jar for quiet breakfasts and pairings where sweetness should stay graceful, not loud.",
        it: "È il barattolo giusto per colazioni leggere e abbinamenti in cui la dolcezza deve restare elegante, non invadente.",
      },
      recipe: {
        uk: "Добре працює з рікотою, грушею та підсушеним хлібом.",
        en: "Excellent with ricotta, pear, and toasted bread.",
        it: "Funziona benissimo con ricotta, pera e pane tostato.",
      },
    },
    {
      id: "blueberry-varennya",
      cat: "preserves",
      tone: "plum",
      image: assets.blueberryJam,
      price: 275,
      rating: 4.8,
      reviews: 92,
      size: "220g",
      sizes: [{ label: "220g", price: 275 }],
      lot: "BLB-25-08",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено серпень 2025", en: "Cooked August 2025", it: "Preparata agosto 2025" },
      region: { uk: "Житомирщина", en: "Zhytomyr region", it: "regione di Zhytomyr" },
      name: { uk: "Чорничне варення", en: "Blueberry Preserve", it: "Confettura di mirtilli" },
      note: { uk: "ягідне · глибоке · оксамитове", en: "berry-led · deep · velvety", it: "fruttato · profondo · vellutato" },
      desc: {
        uk: "Темне чорничне варення з м'якою текстурою і виразним ягідним смаком. Добре для тостів і сирної тарілки.",
        en: "A dark blueberry preserve with a smooth texture and a full berry profile. Great on toast or with cheese.",
        it: "Una confettura di mirtilli scura e vellutata, con sapore di frutto pieno. Ottima su pane tostato o con formaggi.",
      },
      tasting: {
        uk: ["Чорниця", "Ліс", "Легкий дим"],
        en: ["Blueberry", "Forest", "Light smoke"],
        it: ["Mirtillo", "Bosco", "Fumo leggero"],
      },
      pairings: {
        uk: ["Брі", "Грецький йогурт", "Тости", "Вівсянка", "Млинці"],
        en: ["Brie", "Greek yogurt", "Toast", "Oatmeal", "Crepes"],
        it: ["Brie", "Yogurt greco", "Pane tostato", "Porridge", "Crêpes"],
      },
      story: {
        uk: "Ми тримаємо смак темним і лісовим, не зводячи чорницю до простої десертної солодкості.",
        en: "We keep the profile foresty and dark rather than turning blueberry into a simple sugar note.",
        it: "Manteniamo il profilo boschivo e scuro, senza ridurre il mirtillo a una dolcezza generica.",
      },
      recipe: {
        uk: "Подайте з брі, підсушеним хлібом і чорним перцем.",
        en: "Serve it with brie, toasted bread, and black pepper.",
        it: "Servitela con brie, pane tostato e pepe nero.",
      },
    },
    {
      id: "chamomile-tea",
      cat: "tea",
      tone: "cream",
      tag: "new",
      image: assets.chamomileTea,
      price: 190,
      rating: 4.7,
      reviews: 88,
      size: "60g",
      sizes: [{ label: "60g", price: 190 }],
      lot: "CHM-26-03",
      shelf: { uk: "Найкраще протягом 12 міс.", en: "Best within 12 months", it: "Meglio entro 12 mesi" },
      harvest: { uk: "Збір березень 2026", en: "Harvested March 2026", it: "Raccolta marzo 2026" },
      region: { uk: "Тернопільщина", en: "Ternopil region", it: "regione di Ternopil" },
      name: { uk: "Ромашковий чай", en: "Chamomile Tea", it: "Camomilla" },
      note: { uk: "медовий · квітковий · тихий", en: "honeyed · floral · quiet", it: "mielato · floreale · quieto" },
      desc: {
        uk: "Чистий ромашковий чай з м'яким медовим відтінком. Для вечора, коли хочеться простого спокійного смаку.",
        en: "A clean chamomile tea with a soft honeyed tone. Made for evenings that need a calmer cup.",
        it: "Una camomilla pulita con una nota morbida di miele. Pensata per sere che chiedono una tazza più calma.",
      },
      tasting: {
        uk: ["Ромашка", "Мед", "Сухе сіно"],
        en: ["Chamomile", "Honey", "Dry hay"],
        it: ["Camomilla", "Miele", "Fieno secco"],
      },
      pairings: {
        uk: ["Мед", "Пісочне печиво", "Запечене яблуко", "Творог", "Тости з маслом"],
        en: ["Honey", "Shortbread", "Baked apple", "Curd cheese", "Buttered toast"],
        it: ["Miele", "Frollini", "Mela al forno", "Formaggio fresco", "Pane e burro"],
      },
      story: {
        uk: "Тут ми нічого не ускладнюємо: ромашка має лишатися читабельною, м'якою і дуже домашньою.",
        en: "We do not complicate this one: chamomile should stay legible, soft, and unmistakably homey.",
        it: "Qui non complichiamo nulla: la camomilla deve restare leggibile, morbida e profondamente domestica.",
      },
      recipe: {
        uk: "Добре звучить з ложкою акацієвого меду.",
        en: "Best with a spoon of acacia honey.",
        it: "Rende al meglio con un cucchiaino di miele d'acacia.",
      },
    },
    {
      id: "ivan-chai",
      cat: "tea",
      tone: "sage",
      image: assets.herbalTea,
      price: 235,
      rating: 4.8,
      reviews: 164,
      size: "70g",
      sizes: [{ label: "70g", price: 235 }],
      lot: "IVN-26-01",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір січень 2026", en: "Harvested January 2026", it: "Raccolta gennaio 2026" },
      region: { uk: "Верховина", en: "Verkhovyna", it: "Verkhovyna" },
      name: { uk: "Іван-чай ферментований", en: "Fermented Ivan Chai", it: "Ivan chai fermentato" },
      note: { uk: "бурштиновий · сухофруктовий · м'який", en: "amber · dried fruit · soft", it: "ambrato · frutta secca · morbido" },
      desc: {
        uk: "Ферментований кіпрій з теплим сухофруктовим профілем. Затишний чай для довгих вечорів.",
        en: "Fermented fireweed with an amber, dried-fruit profile and a long soft finish.",
        it: "Fireweed fermentato con profilo ambrato di frutta secca e finale lungo e morbido.",
      },
      tasting: {
        uk: ["Курага", "Сіно", "Медовий лист"],
        en: ["Apricot", "Hay", "Honeyed leaf"],
        it: ["Albicocca secca", "Fieno", "Foglia mielata"],
      },
      pairings: {
        uk: ["Медівник", "Пісочне печиво", "Сухофрукти", "Груша", "Твердий сир"],
        en: ["Honey cake", "Shortbread", "Dried fruit", "Pear", "Firm cheese"],
        it: ["Torta al miele", "Frollini", "Frutta secca", "Pera", "Formaggio stagionato"],
      },
      story: {
        uk: "Це чай з повільним темпом: м'який, теплий, без різкості, але з довгим післясмаком.",
        en: "This is our slowest tea: warm, rounded, and long on the finish without becoming heavy.",
        it: "È la nostra tisana più lenta: calda, rotonda e persistente senza diventare pesante.",
      },
      recipe: {
        uk: "Добре заварюється повторно двічі.",
        en: "It takes a second steep beautifully.",
        it: "Regge benissimo anche una seconda infusione.",
      },
    },
    {
      id: "walnut-oil",
      cat: "oil",
      tone: "terra",
      tag: "new",
      image: assets.sunflowerOilBottle,
      price: 480,
      rating: 4.8,
      reviews: 96,
      size: "200ml",
      sizes: [{ label: "200ml", price: 480 }],
      lot: "WLN-26-02",
      shelf: { uk: "Найкраще протягом 9 міс.", en: "Best within 9 months", it: "Meglio entro 9 mesi" },
      harvest: { uk: "Пресування лютий 2026", en: "Pressed February 2026", it: "Spremitura febbraio 2026" },
      region: { uk: "Закарпаття", en: "Zakarpattia", it: "Transcarpazia" },
      name: { uk: "Олія волоського горіха", en: "Walnut Oil", it: "Olio di noci" },
      note: { uk: "горіхова · масляниста · глибока", en: "nutty · buttery · deep", it: "nocciolato · burroso · profondo" },
      desc: {
        uk: "Темна олія холодного віджиму з волоських горіхів — для салатів, пасти і твердих сирів.",
        en: "A cold-pressed walnut oil — built for salads, pasta, and aged cheese.",
        it: "Olio di noci spremuto a freddo — perfetto per insalate, pasta e formaggi stagionati.",
      },
      tasting: { uk: ["Волоський горіх", "Масло", "Деревина"], en: ["Walnut", "Butter", "Wood"], it: ["Noce", "Burro", "Legno"] },
      pairings: { uk: ["Паста", "Гриби", "Сир", "Груша", "Свіжий салат"], en: ["Pasta", "Mushrooms", "Cheese", "Pear", "Salad"], it: ["Pasta", "Funghi", "Formaggio", "Pera", "Insalata"] },
      story: {
        uk: "Горіхи сушаться повільно, а олія йде до пляшки одразу після пресу — без рафінації.",
        en: "Slowly dried nuts, pressed once, bottled fresh — no refining.",
        it: "Noci asciugate lentamente, una sola spremitura, imbottigliate subito.",
      },
      recipe: { uk: "Збризніть теплу пасту з пармезаном.", en: "Drizzle warm pasta with parmesan.", it: "Su pasta calda con parmigiano." },
    },
    {
      id: "hemp-oil",
      cat: "oil",
      tone: "moss",
      image: assets.linseedOil,
      price: 410,
      rating: 4.6,
      reviews: 72,
      size: "250ml",
      sizes: [{ label: "250ml", price: 410 }],
      lot: "HMP-26-01",
      shelf: { uk: "Найкраще протягом 8 міс.", en: "Best within 8 months", it: "Meglio entro 8 mesi" },
      harvest: { uk: "Пресування січень 2026", en: "Pressed January 2026", it: "Spremitura gennaio 2026" },
      region: { uk: "Сумщина", en: "Sumy region", it: "regione di Sumy" },
      name: { uk: "Конопляна олія", en: "Hempseed Oil", it: "Olio di canapa" },
      note: { uk: "трав'яниста · зелена · свіжа", en: "grassy · green · fresh", it: "erbaceo · verde · fresco" },
      desc: {
        uk: "Зелена нерафінована олія з насіння конопель. Робить салат живішим і підходить до йогурту.",
        en: "An unrefined green hempseed oil. Lifts salads and works in savoury yogurt bowls.",
        it: "Olio verde non raffinato di canapa. Vivacizza le insalate e si sposa con lo yogurt.",
      },
      tasting: { uk: ["Зелень", "Соняшник", "Свіжа трава"], en: ["Greens", "Sunflower", "Fresh grass"], it: ["Verde", "Girasole", "Erba fresca"] },
      pairings: { uk: ["Хумус", "Йогурт", "Помідори", "Паста", "Авокадо"], en: ["Hummus", "Yogurt", "Tomato", "Pasta", "Avocado"], it: ["Hummus", "Yogurt", "Pomodoro", "Pasta", "Avocado"] },
      story: { uk: "Невелика серія для тих, хто хоче більше зелених, рослинних нот у щоденній кухні.", en: "A small batch for greener, more vegetal everyday cooking.", it: "Piccola serie per cucinare con più note verdi e vegetali." },
      recipe: { uk: "Додайте до хумусу замість оливкової.", en: "Use it on hummus instead of olive oil.", it: "Sull'hummus al posto dell'olio d'oliva." },
    },
    {
      id: "buckwheat-honey",
      cat: "honey",
      tone: "plum",
      tag: "new",
      image: assets.buckwheatHoney,
      price: 320,
      rating: 4.8,
      reviews: 134,
      size: "300g",
      sizes: [{ label: "300g", price: 320 }, { label: "500g", price: 470 }],
      lot: "BCK-25-09",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка вересень 2025", en: "Harvested September 2025", it: "Raccolto settembre 2025" },
      region: { uk: "Чернігівщина", en: "Chernihiv region", it: "regione di Chernihiv" },
      name: { uk: "Гречаний мед", en: "Buckwheat Honey", it: "Miele di grano saraceno" },
      note: { uk: "темний · мальтовий · мужній", en: "dark · malty · bold", it: "scuro · maltato · deciso" },
      desc: {
        uk: "Темний, майже патоковий мед з гречаних полів — для чорного хліба, темного шоколаду і кави.",
        en: "Dark, molasses-deep buckwheat honey for rye bread, dark chocolate, and coffee.",
        it: "Miele scuro e quasi melassoso per pane di segale, cioccolato fondente e caffè.",
      },
      tasting: { uk: ["Меляса", "Карамель", "Вологе дерево"], en: ["Molasses", "Caramel", "Damp wood"], it: ["Melassa", "Caramello", "Legno umido"] },
      pairings: { uk: ["Житній хліб", "Темний шоколад", "Кава", "Чеддер", "Імбир"], en: ["Rye bread", "Dark chocolate", "Coffee", "Cheddar", "Ginger"], it: ["Pane di segale", "Cioccolato fondente", "Caffè", "Cheddar", "Zenzero"] },
      story: { uk: "Дорослий, насичений мед з характером — не для тих, хто шукає квітковості.", en: "A grown-up, intense honey — not for those looking for floral lightness.", it: "Un miele intenso e adulto, non per chi cerca leggerezza floreale." },
      recipe: { uk: "З чорним хлібом, маслом і дрібкою солі.", en: "Black bread, butter, a pinch of salt.", it: "Pane nero, burro e un pizzico di sale." },
    },
    {
      id: "strawberry-jam",
      cat: "preserves",
      tone: "amber",
      image: assets.strawberryJam,
      price: 245,
      rating: 4.8,
      reviews: 162,
      size: "220g",
      sizes: [{ label: "220g", price: 245 }],
      lot: "STR-25-07",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено липень 2025", en: "Cooked July 2025", it: "Preparata luglio 2025" },
      region: { uk: "Київщина", en: "Kyiv region", it: "regione di Kyiv" },
      name: { uk: "Полуничне варення", en: "Strawberry Preserve", it: "Confettura di fragole" },
      note: { uk: "соковите · літнє · легке", en: "juicy · summery · soft", it: "succoso · estivo · morbido" },
      desc: {
        uk: "Літнє варення з лісової полуниці, варене швидко, щоб зберегти свіжість і колір.",
        en: "A summer-bright wild strawberry preserve cooked quickly to keep colour and lift.",
        it: "Confettura di fragole selvatiche cotta rapidamente per conservare colore e brillantezza.",
      },
      tasting: { uk: ["Стигла полуниця", "Лимон", "Сонце"], en: ["Ripe strawberry", "Lemon", "Sunlight"], it: ["Fragola matura", "Limone", "Sole"] },
      pairings: { uk: ["Сирники", "Йогурт", "Млинці", "Тости", "Пісочне печиво"], en: ["Syrnyky", "Yogurt", "Crepes", "Toast", "Shortbread"], it: ["Syrnyky", "Yogurt", "Crêpes", "Pane tostato", "Frollini"] },
      story: { uk: "Менше цукру, більше ягоди — варення, яке нагадує літо, а не цукерню.", en: "Less sugar, more fruit — a preserve that tastes like summer.", it: "Meno zucchero, più frutta — una confettura che sa d'estate." },
      recipe: { uk: "Подавайте з густою сметаною на тостах.", en: "Spread on toast with thick cream.", it: "Su pane tostato con panna densa." },
    },
    {
      id: "apricot-jam",
      cat: "preserves",
      tone: "gold",
      image: assets.apricotJam,
      price: 250,
      rating: 4.7,
      reviews: 119,
      size: "220g",
      sizes: [{ label: "220g", price: 250 }],
      lot: "APR-25-07",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено липень 2025", en: "Cooked July 2025", it: "Preparata luglio 2025" },
      region: { uk: "Одещина", en: "Odesa region", it: "regione di Odesa" },
      name: { uk: "Абрикосовий конфітюр", en: "Apricot Confiture", it: "Confettura di albicocche" },
      note: { uk: "медовий · теплий · золотавий", en: "honeyed · warm · golden", it: "mielato · caldo · dorato" },
      desc: {
        uk: "Густий конфітюр зі зрілих абрикосів — для круасанів, м'яких сирів і теплої кави.",
        en: "A dense apricot confiture for croissants, soft cheese, and warm coffee.",
        it: "Una confettura densa di albicocche per croissant, formaggi morbidi e caffè caldo.",
      },
      tasting: { uk: ["Абрикос", "Мед", "Цедра"], en: ["Apricot", "Honey", "Zest"], it: ["Albicocca", "Miele", "Scorza"] },
      pairings: { uk: ["Круасани", "Бріош", "Сир камамбер", "Тости", "Чорний чай"], en: ["Croissants", "Brioche", "Camembert", "Toast", "Black tea"], it: ["Croissant", "Brioche", "Camembert", "Pane tostato", "Tè nero"] },
      story: { uk: "Робиться з абрикос пізнього збору — менше кислоти, більше глибини.", en: "Late-harvest apricots — less acid, more depth.", it: "Albicocche di tarda raccolta — meno acidità, più profondità." },
      recipe: { uk: "Тепла бріош, ложка масла, ложка конфітюру.", en: "Warm brioche, butter, a spoon of jam.", it: "Brioche calda, burro, un cucchiaio di confettura." },
    },
    {
      id: "mint-tea",
      cat: "tea",
      tone: "moss",
      image: assets.mintTea,
      price: 195,
      rating: 4.7,
      reviews: 142,
      size: "70g",
      sizes: [{ label: "70g", price: 195 }],
      lot: "MNT-26-03",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір березень 2026", en: "Harvested March 2026", it: "Raccolta marzo 2026" },
      region: { uk: "Полтавщина", en: "Poltava region", it: "regione di Poltava" },
      name: { uk: "М'ятний чай", en: "Mountain Mint Tea", it: "Tisana alla menta" },
      note: { uk: "прохолодний · ясний · чистий", en: "cooling · clear · clean", it: "fresco · chiaro · pulito" },
      desc: {
        uk: "Класичний м'ятний чай з ноткою меліси — найкраще для післяобіднього спокою.",
        en: "A classic mint tea with a hint of lemon balm — for an unhurried afternoon.",
        it: "Tisana classica alla menta con un tocco di melissa, per un pomeriggio lento.",
      },
      tasting: { uk: ["М'ята", "Меліса", "Свіжість"], en: ["Mint", "Lemon balm", "Lift"], it: ["Menta", "Melissa", "Freschezza"] },
      pairings: { uk: ["Лимон", "Мед", "Печиво", "Шоколад", "Йогурт"], en: ["Lemon", "Honey", "Biscuits", "Chocolate", "Yogurt"], it: ["Limone", "Miele", "Biscotti", "Cioccolato", "Yogurt"] },
      story: { uk: "Лист збираємо вручну і сушимо в тіні, щоб ефірні олії не вивітрювалися.", en: "Hand-picked leaves dried in shade to keep the essential oils.", it: "Foglie raccolte a mano ed essiccate in ombra per preservare gli oli essenziali." },
      recipe: { uk: "Заваріть 90°C і додайте скибочку лимона.", en: "Steep at 90°C with a slice of lemon.", it: "Infondete a 90°C con una fetta di limone." },
    },
    {
      id: "sunflower-honey",
      cat: "honey",
      tone: "gold",
      image: assets.honeyDip,
      price: 285,
      rating: 4.7,
      reviews: 94,
      size: "300g",
      sizes: [{ label: "300g", price: 285 }],
      lot: "SNH-25-07",
      shelf: { uk: "Найкраще протягом 24 міс.", en: "Best within 24 months", it: "Meglio entro 24 mesi" },
      harvest: { uk: "Викачка липень 2025", en: "Harvested July 2025", it: "Raccolto luglio 2025" },
      region: { uk: "Миколаївщина", en: "Mykolaiv region", it: "regione di Mykolaiv" },
      name: { uk: "Соняшниковий мед", en: "Sunflower Honey", it: "Miele di girasole" },
      note: { uk: "бурштиновий · польовий · м'який", en: "amber · fieldy · soft", it: "ambrato · campestre · morbido" },
      desc: {
        uk: "Теплий соняшниковий мед із щільнішим смаком і спокійною солодкістю. Добре пасує до тостів і каш.",
        en: "A warm sunflower honey with a fuller body and a calm everyday sweetness for toast and porridge.",
        it: "Un miele di girasole caldo, dal corpo più pieno e dalla dolcezza tranquilla, perfetto su pane e porridge.",
      },
      tasting: {
        uk: ["Пилок", "Сонце", "Сіно"],
        en: ["Pollen", "Sun", "Hay"],
        it: ["Polline", "Sole", "Fieno"],
      },
      pairings: {
        uk: ["Тости", "Вівсянка", "Масло", "Рікота", "Тепле молоко"],
        en: ["Toast", "Oatmeal", "Butter", "Ricotta", "Warm milk"],
        it: ["Pane tostato", "Porridge", "Burro", "Ricotta", "Latte caldo"],
      },
      story: {
        uk: "Цей мед беремо для щоденного столу: він прямий, впізнаваний і без зайвої парфумності.",
        en: "We keep this jar for the everyday table: direct, familiar, and never overly perfumed.",
        it: "E il barattolo per la tavola di tutti i giorni: diretto, riconoscibile e mai troppo profumato.",
      },
      recipe: {
        uk: "Спробуйте на теплому тості з вершковим маслом.",
        en: "Try it on warm toast with cultured butter.",
        it: "Provatelo su pane caldo con burro.",
      },
    },
    {
      id: "quince-confiture",
      cat: "preserves",
      tone: "gold",
      image: assets.apricotJam,
      price: 255,
      rating: 4.7,
      reviews: 79,
      size: "220g",
      sizes: [{ label: "220g", price: 255 }],
      lot: "QNC-25-09",
      shelf: { uk: "Найкраще протягом 18 міс.", en: "Best within 18 months", it: "Meglio entro 18 mesi" },
      harvest: { uk: "Зварено вересень 2025", en: "Cooked September 2025", it: "Preparata settembre 2025" },
      region: { uk: "Вінниччина", en: "Vinnytsia region", it: "regione di Vinnytsia" },
      name: { uk: "Айвовий конфітюр", en: "Quince Confiture", it: "Confettura di mele cotogne" },
      note: { uk: "золотавий · медовий · тихий", en: "golden · honeyed · mellow", it: "dorato · mielato · quieto" },
      desc: {
        uk: "Густий конфітюр з айви з теплою фруктовою глибиною. Для круасанів, бринзи й осіннього столу.",
        en: "A dense quince confiture with gentle fruit depth for croissants, brynza, and autumn breakfasts.",
        it: "Una confettura densa di mele cotogne, con profondita fruttata e calda, perfetta per croissant e formaggi freschi.",
      },
      tasting: {
        uk: ["Айва", "Мед", "Тепла шкірка"],
        en: ["Quince", "Honey", "Warm peel"],
        it: ["Mela cotogna", "Miele", "Buccia calda"],
      },
      pairings: {
        uk: ["Круасани", "Бринза", "Йогурт", "Пісочне печиво", "Чорний чай"],
        en: ["Croissants", "Brynza", "Yogurt", "Shortbread", "Black tea"],
        it: ["Croissant", "Brynza", "Yogurt", "Frollini", "Te nero"],
      },
      story: {
        uk: "Айва лишається трохи щільною за текстурою, тому конфітюр не перетворюється на безлику солодку пасту.",
        en: "We keep some quince texture intact so the confiture never turns into a flat sweet paste.",
        it: "Lasciamo un po' di consistenza della mela cotogna, cosi la confettura non diventa una crema dolce indistinta.",
      },
      recipe: {
        uk: "Добре працює з бринзою і теплим підсушеним хлібом.",
        en: "Excellent with brynza and a slice of warm toasted bread.",
        it: "Ottima con brynza e pane tostato ancora tiepido.",
      },
    },
    {
      id: "melissa-tea",
      cat: "tea",
      tone: "sage",
      image: assets.mintTea,
      price: 205,
      rating: 4.7,
      reviews: 71,
      size: "65g",
      sizes: [{ label: "65g", price: 205 }],
      lot: "MLS-26-03",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір березень 2026", en: "Harvested March 2026", it: "Raccolta marzo 2026" },
      region: { uk: "Хмельниччина", en: "Khmelnytskyi region", it: "regione di Khmelnytskyi" },
      name: { uk: "Чай з меліси", en: "Lemon Balm Tea", it: "Tisana alla melissa" },
      note: { uk: "лимонний · м'який · свіжий", en: "lemony · soft · fresh", it: "agrumato · morbido · fresco" },
      desc: {
        uk: "Спокійний чай з меліси з легким цитрусовим відтінком. Добрий для вечора і легких десертів.",
        en: "A calm lemon balm tea with a light citrus lift, made for evenings and lighter sweets.",
        it: "Una tisana alla melissa calma, con una lieve nota agrumata, perfetta per la sera e per dessert leggeri.",
      },
      tasting: {
        uk: ["Меліса", "Лимонна шкірка", "Трава"],
        en: ["Lemon balm", "Lemon peel", "Grass"],
        it: ["Melissa", "Scorza di limone", "Erba"],
      },
      pairings: {
        uk: ["Мед", "Пісочне печиво", "Яблучний пиріг", "Тости", "Груша"],
        en: ["Honey", "Shortbread", "Apple cake", "Toast", "Pear"],
        it: ["Miele", "Frollini", "Torta di mele", "Pane tostato", "Pera"],
      },
      story: {
        uk: "Сушимо лист делікатно, щоб меліса лишалася не аптечною, а живою і кухонною за характером.",
        en: "We dry the leaves gently so lemon balm stays lively and kitchen-friendly rather than medicinal.",
        it: "Essicchiamo le foglie con delicatezza perche la melissa resti viva e domestica, non medicinale.",
      },
      recipe: {
        uk: "Заваріть 85°C і подайте з ложкою світлого меду.",
        en: "Steep at 85°C and serve with a spoon of light honey.",
        it: "Infondete a 85°C e servite con un cucchiaino di miele chiaro.",
      },
    },
    {
      id: "thyme-tea",
      cat: "tea",
      tone: "moss",
      image: assets.herbalTea,
      price: 215,
      rating: 4.8,
      reviews: 77,
      size: "65g",
      sizes: [{ label: "65g", price: 215 }],
      lot: "THY-26-02",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір лютий 2026", en: "Harvested February 2026", it: "Raccolta febbraio 2026" },
      region: { uk: "Карпати", en: "Carpathian Mountains", it: "Monti Carpazi" },
      name: { uk: "Чебрецевий чай", en: "Wild Thyme Tea", it: "Tisana al timo selvatico" },
      note: { uk: "трав'яний · сухий · гірський", en: "herbal · dry · alpine", it: "erbaceo · asciutto · montano" },
      desc: {
        uk: "Гірський чебрець із сухим, чистим ароматом. Добре зігріває і лишається дуже зібраним у чашці.",
        en: "Mountain thyme with a dry, clean aroma. Warming, focused, and very clear in the cup.",
        it: "Timo di montagna dal profilo secco e pulito. Riscalda la tazza senza diventare pesante.",
      },
      tasting: {
        uk: ["Чебрець", "Сухі трави", "Легкий мед"],
        en: ["Thyme", "Dry herbs", "Light honey"],
        it: ["Timo", "Erbe secche", "Miele leggero"],
      },
      pairings: {
        uk: ["Мед", "Сир", "Галети", "Запечене яблуко", "Темний хліб"],
        en: ["Honey", "Cheese", "Galettes", "Baked apple", "Dark bread"],
        it: ["Miele", "Formaggio", "Galette", "Mela al forno", "Pane scuro"],
      },
      story: {
        uk: "У цьому чаї ми не шукаємо солодкості: головне тут сухий карпатський профіль і дуже чистий фініш.",
        en: "This tea is not about sweetness; it is about a dry Carpathian profile and a very clean finish.",
        it: "Qui non cerchiamo dolcezza: conta il profilo secco dei Carpazi e un finale molto pulito.",
      },
      recipe: {
        uk: "Спробуйте 4 хвилини при 90°C з краплею липового меду.",
        en: "Steep for 4 minutes at 90°C with a touch of linden honey.",
        it: "Infondete 4 minuti a 90°C con una goccia di miele di tiglio.",
      },
    },
    {
      id: "rosehip-tea",
      cat: "tea",
      tone: "terra",
      tag: "new",
      image: assets.rosehipTea,
      price: 220,
      rating: 4.8,
      reviews: 88,
      size: "80g",
      sizes: [{ label: "80g", price: 220 }],
      lot: "ROS-25-11",
      shelf: { uk: "Найкраще протягом 14 міс.", en: "Best within 14 months", it: "Meglio entro 14 mesi" },
      harvest: { uk: "Збір листопад 2025", en: "Harvested November 2025", it: "Raccolta novembre 2025" },
      region: { uk: "Карпати", en: "Carpathian Mountains", it: "Monti Carpazi" },
      name: { uk: "Чай з шипшини", en: "Rosehip Tea", it: "Tisana di rosa canina" },
      note: { uk: "цитрусовий · яскравий · теплий", en: "citrus · bright · warm", it: "agrumato · brillante · caldo" },
      desc: {
        uk: "Подрібнена шипшина з ноткою чорної смородини. Зимовий чай з чесною кислинкою.",
        en: "Crushed rosehips with a touch of blackcurrant — a winter tea with honest tartness.",
        it: "Rosa canina spezzata con un tocco di ribes nero — una tisana invernale acidula.",
      },
      tasting: { uk: ["Шипшина", "Цитрус", "Сухі ягоди"], en: ["Rosehip", "Citrus", "Dried berry"], it: ["Rosa canina", "Agrumi", "Bacche secche"] },
      pairings: { uk: ["Мед", "Імбир", "Темний шоколад", "Гарячий хліб", "Лимон"], en: ["Honey", "Ginger", "Dark chocolate", "Warm bread", "Lemon"], it: ["Miele", "Zenzero", "Cioccolato fondente", "Pane caldo", "Limone"] },
      story: { uk: "Збираємо після першого морозу, коли цукри і смак стають насиченішими.", en: "We pick after the first frost, when sugars and flavour deepen.", it: "Raccolta dopo la prima gelata, quando zuccheri e sapore si concentrano." },
      recipe: { uk: "10 хвилин при 95°C, з ложкою меду.", en: "10 minutes at 95°C with a spoon of honey.", it: "10 minuti a 95°C con un cucchiaio di miele." },
    },
  ];

  const ui = {
    uk: {
      metaTitle: "Munister — Сучасна українська крамниця смаку",
      currency: "₴",
      announcement: "Українські pantry-товари малими партіями · безкоштовна доставка від ₴1800",
      nav: { shop: "Крамниця", gifts: "Набори", story: "Історія", search: "Пошук", bag: "Кошик" },
      hero: {
        eyebrow: "Сучасна українська pantry-лінія",
        titleA: "Українські смаки,",
        titleB: "зібрані",
        titleC: "повільно.",
        body: "Холодні олії, мед з пасік, домашні конфітюри та карпатські чаї з новою, чистішою подачею. Більше України на полиці. Менше шуму в дизайні.",
        primary: "Відкрити крамницю",
        secondary: "Подивитись набори",
        stats: [
          ["23", "товарів малого тиражу"],
          ["4", "категорії нового pantry"],
          ["Made in UA", "у центрі історії"],
        ],
        cardEyebrow: "Українська pantry-полиця",
        cardTitle: "Теплі, виразні продукти для щоденного столу.",
        cardBody: "Від соняшникової та лляної олії до акацієвого меду, чорничного варення і ромашкового чаю — тепер каталог виглядає так само конкретно, як і самі товари.",
        image: assets.sunflowerOilBottle,
      },
      home: {
        categoriesEyebrow: "Категорії",
        categoriesTitle: "Нова українська pantry-полиця.",
        shopAll: "Дивитись усе",
        bestEyebrow: "Бестселери",
        bestTitle: "Те, з чого починають.",
        founderEyebrow: "Погляд засновниці",
        founderQuote: "Ми хотіли, щоб українські продукти виглядали так само переконливо, як і смакували.",
        founderBody: "Munister тепер говорить мовою сучасної української pantry-культури: 23 локальних SKU, теплі кольори, реальні фото під кожен товар і менше декоративного шуму.",
        founderName: "Команда Munister",
        founderRole: "Curation & pantry direction",
        newsletterEyebrow: "Суботній лист",
        newsletterTitle: "Один рецепт. Одна сезонна знахідка. Щосуботи.",
        newsletterBody: "Перший лист дає знижку 10% на перше замовлення.",
        newsletterPlaceholder: "you@kitchen.ua",
        newsletterCta: "Підписатись",
        newsletterDone: "Готово",
      },
      footer: {
        body: "Олії, мед, варення та чай з українським характером і спокійнішою візуальною мовою.",
        badges: ["Made in Ukraine", "Small Batch", "Gift Ready"],
        cols: [
          { title: "Крамниця", items: ["Олії", "Мед", "Варення", "Чаї"] },
          { title: "Дослідити", items: ["Набори", "Історія", "Бестселери", "Подарунки"] },
          { title: "Сервіс", items: ["Доставка", "Повернення", "Контакт", "FAQ"] },
        ],
        left: "© 2026 Munister · українська pantry-колекція",
        right: "Повільно зібрано · чесно подано",
      },
      search: {
        placeholder: "Шукати олію, мед, варення, чай…",
        try: "Спробуйте пошук",
        empty: "Нічого не знайдено",
        emptyBody: "Спробуйте «мед», «олія» або «чай».",
        results: "результатів",
        suggestions: ["олія", "льон", "мед", "чорниця", "ромашка", "карпати"],
      },
      cart: {
        title: "Ваш кошик",
        freeShipping: "Безкоштовну доставку відкрито",
        away: "до безкоштовної доставки",
        emptyTitle: "Кошик порожній.",
        emptyBody: "Почніть з олій або чаю.",
        subtotal: "Разом",
        checkout: "Оформити",
        footer: "Малі партії · Подарункова подача · Український фокус",
      },
      shop: {
        eyebrow: "Повна колекція",
        title: "Купити колекцію.",
        body: "українських pantry-товарів з чистішою подачею і реальними фотографіями.",
        filters: [
          { id: "oil", label: "Олії" },
          { id: "honey", label: "Мед" },
          { id: "preserves", label: "Варення" },
          { id: "tea", label: "Чаї" },
        ],
        clear: "Очистити",
        sortLabel: "Сортування",
        sorts: {
          popular: "Популярні",
          rating: "Рейтинг",
          "price-asc": "Ціна: низька → висока",
          "price-desc": "Ціна: висока → низька",
        },
        add: "Додати",
        addBag: "У кошик",
        story: "Історія продукту",
        pairings: "Поєднання",
        reviews: "Відгуки",
        size: "Розмір",
        recipeIdea: "Ідея подачі",
        lotTrace: "Трасування партії",
        journeyTitle: "Від виробника до вашого столу.",
        journey: [
          { label: "Збір", date: "Сезонно", desc: "Сировина збирається в коротке сезонне вікно, без великих складських запасів." },
          { label: "Приготування", date: "Малі партії", desc: "Олії тиснемо, мед качаємо, варення варимо і чаї фасуємо невеликими серіями." },
          { label: "Настій смаку", date: "Без поспіху", desc: "Ми лишаємо продуктам їхню природну текстуру і не маскуємо їх надмірною обробкою." },
          { label: "Фасування", date: "Під партію", desc: "Кожна банка або пляшка маркується партією для зрозумілого походження." },
          { label: "Відправка", date: "1-3 дні", desc: "Комплектуємо замовлення вручну, щоб подарунковий вигляд не губився в дорозі." },
        ],
        storyHeading: "Чому це працює.",
        storyBody: "У кожному SKU ми зберегли смак локального продукту, але переодягнули його у cleaner retail-мову. Менше випадкових деталей, більше довіри до самого товару.",
        pairingsHeading: "Найкраще поєднується з.",
        pairingsBody: "Короткі підказки для столу, а не вигадані lofty-історії.",
        reviewsTitle: "Перевірені замовлення",
        reviewsSubtitle: "Що пишуть після першої банки або пляшки.",
        relatedEyebrow: "Ще спробувати",
        relatedTitle: "З цієї ж pantry-лінії.",
        stickyAdd: "Додати",
        added: "Додано",
        backHome: "Головна",
        backShop: "Крамниця",
      },
      gifts: {
        eyebrow: "Подарункові набори",
        title: "Українські смаки, зібрані в набір.",
        body: "Чесні комбінації з pantry-товарів, які не соромно дарувати.",
        occasion: "Нагода:",
        occasions: [
          { id: "all", label: "Усі" },
          { id: "host", label: "Для гостин" },
          { id: "cozy", label: "Для затишку" },
          { id: "sweet", label: "Для солодкого столу" },
        ],
        add: "Додати набір",
        noteTitle: "Додаємо картку з побажанням до кожного набору.",
        noteBody: "Коротке побажання впишемо вручну.",
        noteCta: "Усі набори",
      },
      storyPage: {
        eyebrow: "Наша історія",
        title: "Ми змістили фокус з «середземноморської мрії» на сучасний український pantry.",
        lead: "Тепер у центрі не стилізація під чужий ринок, а локальні товари, знайомі смаки і візуальна впевненість без провінційності.",
        founderEyebrow: "Чому це важливо",
        founderQuote: "Українські продукти заслуговують на таку ж сильну подачу, як і будь-який premium storefront у світі.",
        founderBody: "Ми взяли структуру clean editorial-commerce і наповнили її товарами, які ближчі до нашої кухні: соняшникова й гарбузова олія, мед, варення, трав'яні чаї. Так Munister відчувається переконливіше і чесніше.",
        timelineEyebrow: "Що змінилось",
        timelineTitle: "Чотири опори нового напряму.",
        milestones: [
          { year: "01", event: "Переключили сайт на українські товари, знайомі локальному покупцю." },
          { year: "02", event: "Підібрали реальні фото під кожен SKU, а не під загальну «атмосферу»." },
          { year: "03", event: "Вирівняли типографіку та прибрали зайві декоративні секції." },
          { year: "04", event: "Запустили багатомовність: українська, італійська, англійська." },
        ],
        valuesEyebrow: "Принципи",
        valuesTitle: "Що тримає цю сторінку разом.",
        values: [
          { icon: "◉", title: "Локальний центр", desc: "Товари і словник сайту тепер говорять з українського контексту, а не маскують його." },
          { icon: "◈", title: "Сильніша типографіка", desc: "Заголовки, кнопки і лейбли стали впевненішими, щоби сайт не виглядав кволо." },
          { icon: "◎", title: "Менше шуму", desc: "Ми відрізали блоки, які не допомагали купівлі і лише відтягували увагу." },
          { icon: "○", title: "Справжні фото", desc: "Продукт тепер показаний реально, а не через абстрактні рендери чи stripes." },
        ],
      },
      toasts: {
        added: "Додано до кошика",
        saved: "збережено",
      },
      common: {
        remove: "Прибрати",
        explore: "Дивитись",
        read: "Читати",
        noResults: "Немає результатів",
      },
      reviews: [
        { name: "Олена К.", loc: "Київ", ago: "2 тижні тому", text: "Нарешті український storefront, який не виглядає як ярмарок. І продукти теж чесні." },
        { name: "Марко С.", loc: "Львів", ago: "1 місяць тому", text: "Гарбузова олія дуже сильна. Сайт теж став дорослішим на вигляд." },
        { name: "Ірина Т.", loc: "Дніпро", ago: "3 тижні тому", text: "Чай і мед взяла на подарунок, і саме подача тут вже працює на рішення." },
      ],
      giftBundles: [
        { id: "host", occasions: ["all", "host"], tone: "gold", image: assets.sunflowerOilBottle, price: 980, saving: 120, name: "Набір для гостин", desc: "Соняшникова олія, липовий мед і вишневе варення.", items: ["Соняшникова олія", "Липовий мед", "Варення з вишні"] },
        { id: "cozy", occasions: ["all", "cozy"], tone: "moss", image: assets.chamomileTea, price: 760, saving: 90, name: "Теплий вечір", desc: "Карпатський чай, ромашковий чай і лучний мед.", items: ["Карпатський чай", "Ромашковий чай", "Лучний мед"] },
        { id: "sweet", occasions: ["all", "sweet"], tone: "plum", image: assets.blueberryJam, price: 720, saving: 75, name: "Солодкий стіл", desc: "Чорничне варення, обліпиховий конфітюр і акацієвий мед.", items: ["Чорничне варення", "Обліпиховий конфітюр", "Акацієвий мед"] },
        { id: "pantry", occasions: ["all", "host", "cozy"], tone: "cream", image: assets.sunflowerOilBottle, price: 1420, saving: 180, name: "Стартова pantry-коробка", desc: "Три різні товари для першого великого замовлення: олія, мед, варення і чай.", items: ["Соняшникова олія", "Лляна олія", "Акацієвий мед", "Карпатський чай"] },
      ],
    },
    en: {
      metaTitle: "Munister — The Modern Ukrainian Pantry",
      currency: "₴",
      announcement: "Modern Ukrainian pantry goods · free shipping from ₴1800",
      nav: { shop: "Shop", gifts: "Gifts", story: "Story", search: "Search", bag: "Bag" },
      hero: {
        eyebrow: "A modern Ukrainian pantry line",
        titleA: "Ukrainian flavors,",
        titleB: "gathered",
        titleC: "slowly.",
        body: "Cold-pressed oils, apiary honey, home-style preserves, and Carpathian teas with a cleaner, more confident point of view. More Ukraine on the shelf. Less noise in the design.",
        primary: "Open the pantry",
        secondary: "See gift sets",
        stats: [
          ["23", "small-batch goods"],
          ["4", "new pantry categories"],
          ["Made in UA", "at the center"],
        ],
        cardEyebrow: "A Ukrainian pantry shelf",
        cardTitle: "Warm, expressive products for the everyday table.",
        cardBody: "From sunflower and linseed oil to acacia honey, blueberry preserve, and chamomile tea, the storefront now matches the goods more literally.",
        image: assets.sunflowerOilBottle,
      },
      home: {
        categoriesEyebrow: "Categories",
        categoriesTitle: "The new Ukrainian pantry shelf.",
        shopAll: "Shop all",
        bestEyebrow: "Best sellers",
        bestTitle: "Where most people begin.",
        founderEyebrow: "Founder's angle",
        founderQuote: "We wanted Ukrainian products to look as convincing as they taste.",
        founderBody: "Munister now speaks in the language of a modern Ukrainian pantry: 23 local SKUs, warmer colors, real photos matched to each item, and far less decorative noise.",
        founderName: "Munister Team",
        founderRole: "Curation & pantry direction",
        newsletterEyebrow: "The Saturday letter",
        newsletterTitle: "One recipe. One seasonal find. Every Saturday.",
        newsletterBody: "The first email unlocks 10% off your first order.",
        newsletterPlaceholder: "you@kitchen.com",
        newsletterCta: "Subscribe",
        newsletterDone: "Done",
      },
      footer: {
        body: "Oils, honey, preserves, and tea with a Ukrainian center of gravity and a calmer design language.",
        badges: ["Made in Ukraine", "Small Batch", "Gift Ready"],
        cols: [
          { title: "Shop", items: ["Oils", "Honey", "Preserves", "Tea"] },
          { title: "Explore", items: ["Gift sets", "Our story", "Best sellers", "Giving"] },
          { title: "Help", items: ["Shipping", "Returns", "Contact", "FAQ"] },
        ],
        left: "© 2026 Munister · Ukrainian pantry collection",
        right: "Assembled slowly · presented honestly",
      },
      search: {
        placeholder: "Search oils, honey, preserves, tea…",
        try: "Try searching for",
        empty: "No results found",
        emptyBody: "Try “honey”, “oil”, or “tea”.",
        results: "results",
        suggestions: ["oil", "linseed", "honey", "blueberry", "chamomile", "carpathian"],
      },
      cart: {
        title: "Your bag",
        freeShipping: "Free shipping unlocked",
        away: "away from free shipping",
        emptyTitle: "Your bag is empty.",
        emptyBody: "Start with the oils or the teas.",
        subtotal: "Subtotal",
        checkout: "Checkout",
        footer: "Small batch · Gift-ready · Ukrainian focus",
      },
      shop: {
        eyebrow: "The full collection",
        title: "Shop the collection.",
        body: "Ukrainian pantry goods with a clearer point of view and real photography.",
        filters: [
          { id: "oil", label: "Oils" },
          { id: "honey", label: "Honey" },
          { id: "preserves", label: "Preserves" },
          { id: "tea", label: "Tea" },
        ],
        clear: "Clear",
        sortLabel: "Sort",
        sorts: {
          popular: "Most popular",
          rating: "Top rated",
          "price-asc": "Price: low → high",
          "price-desc": "Price: high → low",
        },
        add: "Add",
        addBag: "Add to bag",
        story: "Story",
        pairings: "Pairings",
        reviews: "Reviews",
        size: "Size",
        recipeIdea: "Serving idea",
        lotTrace: "Lot traceability",
        journeyTitle: "From producer to your table.",
        journey: [
          { label: "Harvest", date: "Seasonal", desc: "Ingredients are gathered in a short seasonal window rather than from anonymous year-round stock." },
          { label: "Make", date: "Small batch", desc: "We press oils, spin honey, cook preserves, and pack tea in deliberately small runs." },
          { label: "Settle", date: "No rush", desc: "Products keep their natural texture and are not over-processed into sameness." },
          { label: "Pack", date: "By lot", desc: "Every jar and bottle is packed with a lot code so the origin stays legible." },
          { label: "Ship", date: "1-3 days", desc: "Orders are assembled by hand so the shelf-ready finish survives the trip." },
        ],
        storyHeading: "Why it works.",
        storyBody: "Each SKU keeps its local identity, but the storefront now frames it with a more composed retail voice. Less noise, more trust in the product itself.",
        pairingsHeading: "Best with.",
        pairingsBody: "Short, useful table cues instead of over-written brand theater.",
        reviewsTitle: "Verified orders",
        reviewsSubtitle: "What people say after the first jar or bottle.",
        relatedEyebrow: "Try next",
        relatedTitle: "From the same pantry line.",
        stickyAdd: "Add",
        added: "Added",
        backHome: "Home",
        backShop: "Shop",
      },
      gifts: {
        eyebrow: "Gift sets",
        title: "Ukrainian flavors, boxed well.",
        body: "Straightforward pantry bundles that feel generous without trying too hard.",
        occasion: "Occasion:",
        occasions: [
          { id: "all", label: "All" },
          { id: "host", label: "Hosting" },
          { id: "cozy", label: "Cozy nights" },
          { id: "sweet", label: "Sweet table" },
        ],
        add: "Add set",
        noteTitle: "Every gift set includes a handwritten note card.",
        noteBody: "We add your message by hand.",
        noteCta: "All gift sets",
      },
      storyPage: {
        eyebrow: "Our story",
        title: "We shifted the center away from a borrowed Mediterranean fantasy and toward a modern Ukrainian pantry.",
        lead: "The point now is not to imitate someone else's market, but to frame local goods with more confidence, clarity, and respect.",
        founderEyebrow: "Why it matters",
        founderQuote: "Ukrainian products deserve the same strength of presentation as any premium storefront anywhere.",
        founderBody: "We kept the clean editorial-commerce structure, but filled it with goods closer to our own kitchen: sunflower and pumpkin seed oils, honey, preserves, and herbal teas. That makes Munister feel truer and stronger at the same time.",
        timelineEyebrow: "What changed",
        timelineTitle: "Four pillars of the reset.",
        milestones: [
          { year: "01", event: "We replaced the catalog with Ukrainian pantry goods that feel familiar and believable." },
          { year: "02", event: "We matched each SKU to a real product photo instead of relying on broad atmospheric placeholders." },
          { year: "03", event: "We tightened the typography and removed sections that only made the page busier." },
          { year: "04", event: "We launched the experience in Ukrainian, Italian, and English." },
        ],
        valuesEyebrow: "Principles",
        valuesTitle: "What holds the page together.",
        values: [
          { icon: "◉", title: "Local at the center", desc: "The catalog and copy now speak from a Ukrainian context instead of disguising it." },
          { icon: "◈", title: "Stronger typography", desc: "Headlines, labels, and buttons were made denser and more self-assured." },
          { icon: "◎", title: "Less noise", desc: "We cut sections that distracted from buying rather than helping it." },
          { icon: "○", title: "Real photos", desc: "The products are now shown as products, not as abstract placeholder patterns." },
        ],
      },
      toasts: {
        added: "Added to bag",
        saved: "saved",
      },
      common: {
        remove: "Remove",
        explore: "Explore",
        read: "Read",
        noResults: "No results",
      },
      reviews: [
        { name: "Olena K.", loc: "Kyiv", ago: "2 weeks ago", text: "Finally a Ukrainian storefront that doesn't feel like a craft fair. The products are honest too." },
        { name: "Marko S.", loc: "Lviv", ago: "1 month ago", text: "The pumpkin seed oil is excellent. The site now looks properly grown up as well." },
        { name: "Iryna T.", loc: "Dnipro", ago: "3 weeks ago", text: "I bought tea and honey as a gift, and the presentation here already does half the work." },
      ],
      giftBundles: [
        { id: "host", occasions: ["all", "host"], tone: "gold", image: assets.sunflowerOilBottle, price: 980, saving: 120, name: "The Host Table", desc: "Sunflower oil, linden honey, and sour cherry preserve.", items: ["Sunflower oil", "Linden honey", "Sour cherry preserve"] },
        { id: "cozy", occasions: ["all", "cozy"], tone: "moss", image: assets.chamomileTea, price: 760, saving: 90, name: "Warm Evening", desc: "Carpathian herbal tea, chamomile tea, and meadow honey.", items: ["Carpathian herbal tea", "Chamomile tea", "Wild meadow honey"] },
        { id: "sweet", occasions: ["all", "sweet"], tone: "plum", image: assets.blueberryJam, price: 720, saving: 75, name: "Sweet Table", desc: "Blueberry preserve, sea buckthorn confiture, and acacia honey.", items: ["Blueberry preserve", "Sea buckthorn confiture", "Acacia honey"] },
        { id: "pantry", occasions: ["all", "host", "cozy"], tone: "cream", image: assets.sunflowerOilBottle, price: 1420, saving: 180, name: "Starter Pantry Box", desc: "A broader first order with two oils, a honey, and a tea.", items: ["Sunflower oil", "Linseed oil", "Acacia honey", "Carpathian herbal tea"] },
      ],
    },
    it: {
      metaTitle: "Munister — La dispensa ucraina contemporanea",
      currency: "₴",
      announcement: "Prodotti da dispensa ucraini contemporanei · spedizione gratuita da ₴1800",
      nav: { shop: "Negozio", gifts: "Regali", story: "Storia", search: "Cerca", bag: "Borsa" },
      hero: {
        eyebrow: "Una dispensa ucraina contemporanea",
        titleA: "Sapori ucraini,",
        titleB: "raccolti",
        titleC: "con calma.",
        body: "Oli spremuti a freddo, mieli d'apiario, conserve fatte in casa e tisane dei Carpazi con un punto di vista più pulito e deciso. Più Ucraina sullo scaffale, meno rumore nel design.",
        primary: "Apri la dispensa",
        secondary: "Vedi i set regalo",
        stats: [
          ["23", "prodotti small batch"],
          ["4", "categorie dispensa"],
          ["Made in UA", "al centro"],
        ],
        cardEyebrow: "Una dispensa ucraina",
        cardTitle: "Prodotti caldi e espressivi per la tavola di ogni giorno.",
        cardBody: "Dall'olio di girasole e di lino al miele d'acacia, alla confettura di mirtilli e alla camomilla: ora le immagini seguono davvero i prodotti.",
        image: assets.sunflowerOilBottle,
      },
      home: {
        categoriesEyebrow: "Categorie",
        categoriesTitle: "Il nuovo scaffale della dispensa ucraina.",
        shopAll: "Vedi tutto",
        bestEyebrow: "Più scelti",
        bestTitle: "Da dove si comincia.",
        founderEyebrow: "Sguardo curatoriale",
        founderQuote: "Volevamo che i prodotti ucraini apparissero forti quanto il loro sapore.",
        founderBody: "Ora Munister parla il linguaggio di una dispensa ucraina moderna: 23 SKU locali, colori più caldi, foto reali per ogni prodotto e molto meno rumore decorativo.",
        founderName: "Team Munister",
        founderRole: "Curation & pantry direction",
        newsletterEyebrow: "La lettera del sabato",
        newsletterTitle: "Una ricetta. Una scoperta stagionale. Ogni sabato.",
        newsletterBody: "La prima email sblocca il 10% sul primo ordine.",
        newsletterPlaceholder: "you@kitchen.it",
        newsletterCta: "Iscriviti",
        newsletterDone: "Fatto",
      },
      footer: {
        body: "Oli, miele, conserve e tè con un baricentro ucraino e una lingua visiva più tranquilla.",
        badges: ["Made in Ukraine", "Small Batch", "Gift Ready"],
        cols: [
          { title: "Negozio", items: ["Oli", "Mieli", "Conserve", "Tisane"] },
          { title: "Esplora", items: ["Set regalo", "La storia", "Più scelti", "Regali"] },
          { title: "Servizio", items: ["Spedizione", "Resi", "Contatti", "FAQ"] },
        ],
        left: "© 2026 Munister · collezione dispensa ucraina",
        right: "Assemblata con calma · presentata con onestà",
      },
      search: {
        placeholder: "Cerca oli, miele, conserve, tè…",
        try: "Prova a cercare",
        empty: "Nessun risultato",
        emptyBody: "Prova con “miele”, “olio” oppure “tè”.",
        results: "risultati",
        suggestions: ["olio", "lino", "miele", "mirtilli", "camomilla", "carpazi"],
      },
      cart: {
        title: "La tua borsa",
        freeShipping: "Spedizione gratuita sbloccata",
        away: "mancano alla spedizione gratuita",
        emptyTitle: "La borsa è vuota.",
        emptyBody: "Inizia dagli oli o dalle tisane.",
        subtotal: "Totale parziale",
        checkout: "Checkout",
        footer: "Piccole serie · Pronto per regalo · Focus ucraino",
      },
      shop: {
        eyebrow: "La collezione completa",
        title: "Acquista la collezione.",
        body: "Prodotti di dispensa ucraini con un linguaggio più chiaro e fotografie reali.",
        filters: [
          { id: "oil", label: "Oli" },
          { id: "honey", label: "Mieli" },
          { id: "preserves", label: "Conserve" },
          { id: "tea", label: "Tisane" },
        ],
        clear: "Pulisci",
        sortLabel: "Ordina",
        sorts: {
          popular: "Più popolari",
          rating: "Più votati",
          "price-asc": "Prezzo: basso → alto",
          "price-desc": "Prezzo: alto → basso",
        },
        add: "Aggiungi",
        addBag: "Aggiungi alla borsa",
        story: "Storia",
        pairings: "Abbinamenti",
        reviews: "Recensioni",
        size: "Formato",
        recipeIdea: "Idea di servizio",
        lotTrace: "Tracciabilità lotto",
        journeyTitle: "Dal produttore alla tua tavola.",
        journey: [
          { label: "Raccolta", date: "Stagionale", desc: "Gli ingredienti vengono raccolti in una breve finestra stagionale invece che da stock anonimi." },
          { label: "Preparazione", date: "Piccole serie", desc: "Spremiamo, invasettiamo e confezioniamo in quantità contenute." },
          { label: "Riposo", date: "Senza fretta", desc: "Manteniamo texture e carattere naturale senza lavorazioni eccessive." },
          { label: "Confezione", date: "Per lotto", desc: "Ogni vaso e bottiglia porta un lotto leggibile e tracciabile." },
          { label: "Spedizione", date: "1-3 giorni", desc: "Gli ordini vengono assemblati a mano per mantenere la qualità visiva del pack." },
        ],
        storyHeading: "Perché funziona.",
        storyBody: "Ogni SKU mantiene identità locale, ma la cornice ora è più composta e retail-ready. Meno rumore, più fiducia nel prodotto.",
        pairingsHeading: "Sta benissimo con.",
        pairingsBody: "Suggerimenti brevi e utili, non teatro di brand.",
        reviewsTitle: "Ordini verificati",
        reviewsSubtitle: "Cosa dicono dopo il primo vasetto o la prima bottiglia.",
        relatedEyebrow: "Prova anche",
        relatedTitle: "Dalla stessa linea dispensa.",
        stickyAdd: "Aggiungi",
        added: "Aggiunto",
        backHome: "Home",
        backShop: "Negozio",
      },
      gifts: {
        eyebrow: "Set regalo",
        title: "Sapori ucraini, ben confezionati.",
        body: "Combinazioni semplici e curate che risultano generose senza forzature.",
        occasion: "Occasione:",
        occasions: [
          { id: "all", label: "Tutti" },
          { id: "host", label: "Per ospiti" },
          { id: "cozy", label: "Sera lenta" },
          { id: "sweet", label: "Tavola dolce" },
        ],
        add: "Aggiungi set",
        noteTitle: "Ogni set include un biglietto scritto a mano.",
        noteBody: "Aggiungiamo il tuo messaggio manualmente.",
        noteCta: "Tutti i set",
      },
      storyPage: {
        eyebrow: "La nostra storia",
        title: "Abbiamo spostato il centro da un'immaginazione mediterranea presa in prestito a una dispensa ucraina contemporanea.",
        lead: "L'obiettivo non è imitare un altro mercato, ma dare ai prodotti locali una cornice più sicura, nitida e rispettosa.",
        founderEyebrow: "Perché conta",
        founderQuote: "I prodotti ucraini meritano la stessa forza di presentazione di qualsiasi storefront premium.",
        founderBody: "Abbiamo mantenuto la struttura editoriale-commerce, ma l'abbiamo riempita con prodotti più vicini alla nostra cucina: oli di girasole e di semi di zucca, miele, conserve e tisane. Così Munister risulta più vero e più forte.",
        timelineEyebrow: "Cosa è cambiato",
        timelineTitle: "Quattro pilastri del reset.",
        milestones: [
          { year: "01", event: "Il catalogo è diventato una dispensa ucraina credibile e riconoscibile." },
          { year: "02", event: "Abbiamo abbinato ogni SKU a una foto reale di prodotto, invece di usare immagini atmosferiche troppo generiche." },
          { year: "03", event: "Abbiamo irrobustito la tipografia e rimosso sezioni superflue." },
          { year: "04", event: "L'esperienza è ora in ucraino, italiano e inglese." },
        ],
        valuesEyebrow: "Principi",
        valuesTitle: "Cosa tiene insieme la pagina.",
        values: [
          { icon: "◉", title: "Locale al centro", desc: "Catalogo e copy parlano ora da un contesto ucraino invece di nasconderlo." },
          { icon: "◈", title: "Tipografia più forte", desc: "Titoli, label e bottoni sono più densi e sicuri." },
          { icon: "◎", title: "Meno rumore", desc: "Abbiamo tagliato le sezioni che distraevano dall'acquisto." },
          { icon: "○", title: "Foto vere", desc: "Il prodotto viene mostrato come prodotto, non come pattern astratto." },
        ],
      },
      toasts: {
        added: "Aggiunto alla borsa",
        saved: "salvato",
      },
      common: {
        remove: "Rimuovi",
        explore: "Esplora",
        read: "Leggi",
        noResults: "Nessun risultato",
      },
      reviews: [
        { name: "Elena K.", loc: "Kyiv", ago: "2 settimane fa", text: "Finalmente uno storefront ucraino che non sembra un mercatino. Anche i prodotti sono onesti." },
        { name: "Marco S.", loc: "Lviv", ago: "1 mese fa", text: "L'olio di semi di zucca è ottimo. Il sito adesso sembra davvero più adulto." },
        { name: "Iryna T.", loc: "Dnipro", ago: "3 settimane fa", text: "Ho preso tè e miele per un regalo e qui la presentazione aiuta già moltissimo." },
      ],
      giftBundles: [
        { id: "host", occasions: ["all", "host"], tone: "gold", image: assets.sunflowerOilBottle, price: 980, saving: 120, name: "Tavola per ospiti", desc: "Olio di girasole, miele di tiglio e confettura di amarene.", items: ["Olio di girasole", "Miele di tiglio", "Confettura di amarene"] },
        { id: "cozy", occasions: ["all", "cozy"], tone: "moss", image: assets.chamomileTea, price: 760, saving: 90, name: "Sera lenta", desc: "Tisana dei Carpazi, camomilla e miele di prato.", items: ["Tisana dei Carpazi", "Camomilla", "Miele di prato"] },
        { id: "sweet", occasions: ["all", "sweet"], tone: "plum", image: assets.blueberryJam, price: 720, saving: 75, name: "Tavola dolce", desc: "Confettura di mirtilli, olivello spinoso e miele d'acacia.", items: ["Confettura di mirtilli", "Confettura di olivello", "Miele d'acacia"] },
        { id: "pantry", occasions: ["all", "host", "cozy"], tone: "cream", image: assets.sunflowerOilBottle, price: 1420, saving: 180, name: "Scatola dispensa starter", desc: "Un primo ordine più ampio con due oli, un miele e una tisana.", items: ["Olio di girasole", "Olio di lino", "Miele d'acacia", "Tisana dei Carpazi"] },
      ],
    },
  };

  function formatPrice(value) {
    return `₴${Number(value).toLocaleString("uk-UA")}`;
  }

  function getProducts(lang) {
    const active = ui[lang] ? lang : "uk";
    return catalogBase.map((item) => ({
      ...item,
      name: item.name[active],
      note: item.note[active],
      desc: item.desc[active],
      region: item.region[active],
      harvest: item.harvest[active],
      shelf: item.shelf[active],
      tasting: item.tasting[active],
      pairings: item.pairings[active],
      story: item.story[active],
      recipe: item.recipe[active],
      tag: item.tag
        ? (item.tag === "bestseller"
          ? (active === "uk" ? "Хіт" : active === "it" ? "Più scelto" : "Bestseller")
          : (active === "uk" ? "Нове" : active === "it" ? "Novità" : "New"))
        : "",
    }));
  }

  function getCopy(lang) {
    return ui[lang] || ui.uk;
  }

  function getCategoryCards(lang) {
    return categoryCards[lang] || categoryCards.uk;
  }

  return {
    assets,
    languages,
    formatPrice,
    getCopy,
    getProducts,
    getCategoryCards,
    defaultLang: "uk",
  };
})();
