// Oracle DDL generator
import { t as tr } from './i18n.js?v=202609210942';
const RESERVED = new Set(`ACCESS ADD ALL ALTER AND ANY AS ASC AUDIT BETWEEN BY CHAR CHECK CLUSTER COLUMN COMMENT
COMPRESS CONNECT CREATE CURRENT DATE DECIMAL DEFAULT DELETE DESC DISTINCT DROP ELSE EXCLUSIVE EXISTS FILE FLOAT
FOR FROM GRANT GROUP HAVING IDENTIFIED IMMEDIATE IN INCREMENT INDEX INITIAL INSERT INTEGER INTERSECT INTO IS
LEVEL LIKE LOCK LONG MAXEXTENTS MINUS MLSLABEL MODE MODIFY NOAUDIT NOCOMPRESS NOT NOWAIT NULL NUMBER OF OFFLINE
ON ONLINE OPTION OR ORDER PCTFREE PRIOR PUBLIC RAW RENAME RESOURCE REVOKE ROW ROWID ROWNUM ROWS SELECT SESSION
SET SHARE SIZE SMALLINT START SUCCESSFUL SYNONYM SYSDATE TABLE THEN TO TRIGGER UID UNION UNIQUE UPDATE USER
VALIDATE VALUES VARCHAR VARCHAR2 VIEW WHENEVER WHERE WITH`.split(/\s+/));

export function ident(name) {
  if (/^[A-Z][A-Z0-9_$#]*$/.test(name) && !RESERVED.has(name) && name.length <= 128) return name;
  return `"${name.replace(/"/g, '')}"`;
}

export const qname = t => (t.schema ? `${ident(t.schema)}.` : '') + ident(t.name);
export const str = s => `'${String(s).replace(/'/g, "''")}'`;

export function generateDDL(model, { comments = true, drop = false } = {}) {
  const out = [];
  const byId = Object.fromEntries(model.tables.map(t => [t.id, t]));
  const col = (t, id) => t.columns.find(c => c.id === id);

  out.push(`-- ${tr('ddl.header')}`, `-- ${tr('ddl.model')}: ${model.name}`, `-- ${new Date().toISOString()}`, '');

  if (drop) {
    (model.views || []).forEach(v => out.push(`DROP VIEW ${qname(v)};`));
    model.tables.forEach(t => out.push(`DROP TABLE ${qname(t)} CASCADE CONSTRAINTS PURGE;`));
    (model.sequences || []).forEach(q => out.push(`DROP SEQUENCE ${qname(q)};`));
    out.push('');
  }

  for (const q of model.sequences || []) out.push(sequenceDDL(q), '');

  for (const t of model.tables) {
    const lines = t.columns.map(c => `    ${columnDef(c, true)}`);
    const pk = t.columns.filter(c => c.pk);
    if (pk.length) lines.push(`    CONSTRAINT ${ident(t.pkName || `${t.name}_PK`)} PRIMARY KEY ( ${pk.map(c => ident(c.name)).join(', ')} )`);
    for (const u of t.uniques) {
      const cols = u.columns.map(id => col(t, id)).filter(Boolean);
      if (cols.length) lines.push(`    CONSTRAINT ${ident(u.name)} UNIQUE ( ${cols.map(c => ident(c.name)).join(', ')} )`);
    }
    for (const k of t.checks || []) if (k.expr?.trim()) lines.push(`    CONSTRAINT ${ident(k.name)} CHECK ( ${k.expr.trim()} )`);
    out.push(`CREATE TABLE ${qname(t)} (`, lines.join(',\n'), `)${tableOptions(t)};`, '');

    if (comments) {
      if (t.comment) out.push(`COMMENT ON TABLE ${qname(t)} IS ${str(t.comment)};`);
      t.columns.filter(c => c.comment).forEach(c =>
        out.push(`COMMENT ON COLUMN ${qname(t)}.${ident(c.name)} IS ${str(c.comment)};`));
      if (t.comment || t.columns.some(c => c.comment)) out.push('');
    }

    for (const ix of t.indexes) {
      const cols = ix.columns.map(id => col(t, id)).filter(Boolean);
      if (!cols.length) continue;
      out.push(`CREATE ${ix.unique ? 'UNIQUE ' : ''}INDEX ${ident(ix.name)} ON ${qname(t)} ( ${cols.map(c => ident(c.name)).join(', ')} );`);
    }
    if (t.indexes.length) out.push('');
  }

  for (const f of model.fks) {
    const from = byId[f.fromTable], to = byId[f.toTable];
    if (!from || !to || !f.columns.length) continue;
    const fc = f.columns.map(p => col(from, p.from)).filter(Boolean);
    const tc = f.columns.map(p => col(to, p.to)).filter(Boolean);
    if (fc.length !== tc.length) continue;
    out.push(`ALTER TABLE ${qname(from)}`,
      `    ADD CONSTRAINT ${ident(f.name)} FOREIGN KEY ( ${fc.map(c => ident(c.name)).join(', ')} )`,
      `        REFERENCES ${qname(to)} ( ${tc.map(c => ident(c.name)).join(', ')} )` +
      (f.onDelete ? `\n        ON DELETE ${f.onDelete}` : '') + ';', '');
  }
  for (const v of model.views || []) {
    out.push(viewDDL(v), '');
    if (comments && v.comment) out.push(`COMMENT ON TABLE ${qname(v)} IS ${str(v.comment)};`, '');
  }
  return out.join('\n');
}

export function columnDef(c, pad = false) {
  const name = pad ? ident(c.name).padEnd(30) : ident(c.name);
  if (c.virtual) return `${name} ${c.type ? `${c.type} ` : ''}GENERATED ALWAYS AS ( ${c.virtual} ) VIRTUAL`;
  let s = `${name} ${c.type || 'VARCHAR2(100 CHAR)'}`;
  if (c.identity) s += ' GENERATED BY DEFAULT ON NULL AS IDENTITY';
  else if (c.default) s += ` DEFAULT ${c.default}`;
  if (!c.nullable || c.pk) s += ' NOT NULL';
  return s;
}

export function tableOptions(t) {
  let s = '';
  if (t.tablespace) s += `\nTABLESPACE ${ident(t.tablespace.toUpperCase())}`;
  const p = t.partition;
  if (p?.type && p.columns) {
    s += `\nPARTITION BY ${p.type} ( ${p.columns} )`;
    if (p.type === 'RANGE' && p.interval) s += ` INTERVAL ( ${p.interval} )`;
    if (p.type === 'HASH' && p.count && !p.definitions) s += ` PARTITIONS ${p.count}`;
    if (p.definitions) s += `\n( ${p.definitions.trim()} )`;
  }
  return s;
}

export function sequenceDDL(q) {
  let s = `CREATE SEQUENCE ${qname(q)} START WITH ${q.start || 1} INCREMENT BY ${q.increment || 1}`;
  if (q.minvalue) s += ` MINVALUE ${q.minvalue}`;
  if (q.maxvalue) s += ` MAXVALUE ${q.maxvalue}`;
  s += +q.cache > 1 ? ` CACHE ${q.cache}` : ' NOCACHE';
  s += q.cycle ? ' CYCLE' : ' NOCYCLE';
  if (q.order) s += ' ORDER';
  return `${s};`;
}

export function viewDDL(v) {
  return `CREATE OR REPLACE VIEW ${qname(v)} AS\n${(v.sql || 'SELECT 1 AS x FROM dual').trim().replace(/;\s*$/, '')};`;
}
