// Model diff → Oracle migration script (from = what the database has, to = the current model)
import { ident, qname, str, generateDDL } from './ddl-gen.js?v=202609171543';
import { t as tr } from './i18n.js?v=202609171543';

const U = s => (s || '').toUpperCase();
const norm = s => (s || '').replace(/\s+/g, ' ').trim().toUpperCase();
const colNames = (tb, ids) => ids.map(id => tb.columns.find(c => c.id === id)?.name).filter(Boolean);
const sig = (tb, ids) => colNames(tb, ids).map(U).join(',');
const list = names => names.map(ident).join(', ');

function fkSig(model, f) {
  const from = model.tables.find(x => x.id === f.fromTable), to = model.tables.find(x => x.id === f.toTable);
  if (!from || !to) return null;
  return `${U(from.name)}(${sig(from, f.columns.map(p => p.from))})->${U(to.name)}(${sig(to, f.columns.map(p => p.to))})|${f.onDelete || ''}`;
}

export function diffModels(from, to, { destructive = false } = {}) {
  const changes = [];
  const out = { dropFk: [], dropIdx: [], dropUk: [], dropPk: [], table: [], create: [], addPk: [], addUk: [], addIdx: [], addFk: [], comments: [], dropTable: [] };
  const change = (kind, text, destructiveChange = false) => changes.push({ kind, text, destructive: destructiveChange });
  const emit = (bucket, sql, isDestructive = false) => out[bucket].push(isDestructive && !destructive ? sql.split('\n').map(l => `-- ${l}`).join('\n') : sql);

  const fromT = new Map(from.tables.map(x => [U(x.name), x]));
  const toT = new Map(to.tables.map(x => [U(x.name), x]));

  // ----- tables that only exist in the model: full CREATE (constraints and indexes included) -----
  const created = to.tables.filter(x => !fromT.has(U(x.name)));
  if (created.length) {
    const ddl = generateDDL({ name: to.name, tables: created, fks: [] }).split('\n').slice(4).join('\n').trim();
    out.create.push(ddl);
    created.forEach(x => change('add', tr('mig.addTable', { t: x.name })));
  }

  // ----- dropped tables -----
  for (const x of from.tables) {
    if (toT.has(U(x.name))) continue;
    emit('dropTable', `DROP TABLE ${qname(x)} CASCADE CONSTRAINTS;`, true);
    change('drop', tr('mig.dropTable', { t: x.name }), true);
  }

  // ----- tables in both -----
  for (const b of to.tables) {
    const a = fromT.get(U(b.name));
    if (!a) continue;
    const T = qname(b);
    const aCols = new Map(a.columns.map(c => [U(c.name), c]));
    const bCols = new Map(b.columns.map(c => [U(c.name), c]));

    for (const c of b.columns) {
      const old = aCols.get(U(c.name));
      if (!old) {
        let def = `${ident(c.name)} ${c.type}`;
        if (c.identity) def += ' GENERATED BY DEFAULT ON NULL AS IDENTITY';
        else if (c.default) def += ` DEFAULT ${c.default}`;
        if (!c.nullable || c.pk) def += ' NOT NULL';
        emit('table', `ALTER TABLE ${T} ADD ( ${def} );`);
        change('add', tr('mig.addCol', { t: b.name, c: c.name, ty: c.type }));
        if (!c.nullable && !c.default && !c.identity) change('warn', tr('mig.nnNoDefault', { t: b.name, c: c.name }));
        if (c.comment) out.comments.push(`COMMENT ON COLUMN ${T}.${ident(c.name)} IS ${str(c.comment)};`);
        continue;
      }
      const mods = [];
      if (norm(old.type) !== norm(c.type)) { mods.push(c.type); change('modify', tr('mig.type', { t: b.name, c: c.name, a: old.type, b: c.type })); }
      if (!c.identity && norm(old.default) !== norm(c.default)) { mods.push(`DEFAULT ${c.default || 'NULL'}`); change('modify', tr('mig.default', { t: b.name, c: c.name, v: c.default || 'NULL' })); }
      const oldNN = !old.nullable || old.pk, newNN = !c.nullable || c.pk;
      if (oldNN !== newNN) { mods.push(newNN ? 'NOT NULL' : 'NULL'); change('modify', tr(newNN ? 'mig.nn' : 'mig.null', { t: b.name, c: c.name })); }
      if (mods.length) emit('table', `ALTER TABLE ${T} MODIFY ( ${ident(c.name)} ${mods.join(' ')} );`);
      if ((old.comment || '') !== (c.comment || '')) {
        out.comments.push(`COMMENT ON COLUMN ${T}.${ident(c.name)} IS ${str(c.comment || '')};`);
        change('modify', tr('mig.comment', { o: `${b.name}.${c.name}` }));
      }
    }
    for (const c of a.columns) {
      if (bCols.has(U(c.name))) continue;
      emit('table', `ALTER TABLE ${T} DROP COLUMN ${ident(c.name)};`, true);
      change('drop', tr('mig.dropCol', { t: b.name, c: c.name }), true);
    }
    if ((a.comment || '') !== (b.comment || '')) {
      out.comments.push(`COMMENT ON TABLE ${T} IS ${str(b.comment || '')};`);
      change('modify', tr('mig.comment', { o: b.name }));
    }

    // primary key
    const pkA = a.columns.filter(c => c.pk).map(c => U(c.name)).join(','), pkB = b.columns.filter(c => c.pk).map(c => U(c.name)).join(',');
    if (pkA !== pkB) {
      if (pkA) emit('dropPk', `ALTER TABLE ${T} DROP PRIMARY KEY KEEP INDEX;`);
      if (pkB) out.addPk.push(`ALTER TABLE ${T} ADD CONSTRAINT ${ident(b.pkName || `${b.name}_PK`)} PRIMARY KEY ( ${list(b.columns.filter(c => c.pk).map(c => c.name))} );`);
      change('modify', tr('mig.pk', { t: b.name, k: pkB || '—' }));
    }

    // unique keys (by column signature)
    const ukA = new Map(a.uniques.map(u => [sig(a, u.columns), u])), ukB = new Map(b.uniques.map(u => [sig(b, u.columns), u]));
    for (const [k, u] of ukA) if (k && !ukB.has(k)) { emit('dropUk', `ALTER TABLE ${T} DROP CONSTRAINT ${ident(u.name)};`); change('drop', tr('mig.dropUk', { n: u.name })); }
    for (const [k, u] of ukB) if (k && !ukA.has(k)) { out.addUk.push(`ALTER TABLE ${T} ADD CONSTRAINT ${ident(u.name)} UNIQUE ( ${list(colNames(b, u.columns))} );`); change('add', tr('mig.addUk', { n: u.name })); }

    // indexes (by columns + uniqueness)
    const ixKey = (tb, ix) => `${ix.unique ? 'U' : ''}:${sig(tb, ix.columns)}`;
    const ixA = new Map(a.indexes.map(ix => [ixKey(a, ix), ix])), ixB = new Map(b.indexes.map(ix => [ixKey(b, ix), ix]));
    for (const [k, ix] of ixA) if (!ixB.has(k)) { emit('dropIdx', `DROP INDEX ${ident(ix.name)};`); change('drop', tr('mig.dropIdx', { n: ix.name })); }
    for (const [k, ix] of ixB) if (!ixA.has(k)) { out.addIdx.push(`CREATE ${ix.unique ? 'UNIQUE ' : ''}INDEX ${ident(ix.name)} ON ${T} ( ${list(colNames(b, ix.columns))} );`); change('add', tr('mig.addIdx', { n: ix.name })); }
  }

  // indexes and comments of freshly created tables are already inside the CREATE block

  // ----- foreign keys (by signature, so renamed tables/ids do not matter) -----
  const fkA = new Map(from.fks.map(f => [fkSig(from, f), f]).filter(([k]) => k));
  const fkB = new Map(to.fks.map(f => [fkSig(to, f), f]).filter(([k]) => k));
  for (const [k, f] of fkA) {
    if (fkB.has(k)) continue;
    const child = from.tables.find(x => x.id === f.fromTable);
    if (!toT.has(U(child.name))) continue; // dropped with the table
    emit('dropFk', `ALTER TABLE ${qname(child)} DROP CONSTRAINT ${ident(f.name)};`);
    change('drop', tr('mig.dropFk', { n: f.name }));
  }
  for (const [k, f] of fkB) {
    if (fkA.has(k)) continue;
    const child = to.tables.find(x => x.id === f.fromTable), parent = to.tables.find(x => x.id === f.toTable);
    out.addFk.push(`ALTER TABLE ${qname(child)} ADD CONSTRAINT ${ident(f.name)} FOREIGN KEY ( ${list(colNames(child, f.columns.map(p => p.from)))} )\n    REFERENCES ${qname(parent)} ( ${list(colNames(parent, f.columns.map(p => p.to)))} )${f.onDelete ? ` ON DELETE ${f.onDelete}` : ''};`);
    change('add', tr('mig.addFk', { n: f.name, a: child.name, b: parent.name }));
  }

  const section = (key, items) => items.length ? [`-- ${tr(key)}`, ...items, ''] : [];
  const sql = [
    `-- ${tr('mig.header')}`,
    `-- ${tr('ddl.model')}: ${to.name}`,
    `-- ${new Date().toISOString()}`,
    ...(changes.some(c => c.destructive) && !destructive ? [`-- ${tr('mig.commented')}`] : []),
    '',
    ...section('mig.sDropFk', out.dropFk),
    ...section('mig.sDropKeys', [...out.dropIdx, ...out.dropUk, ...out.dropPk]),
    ...section('mig.sCreate', out.create),
    ...section('mig.sAlter', out.table),
    ...section('mig.sKeys', [...out.addPk, ...out.addUk, ...out.addIdx]),
    ...section('mig.sFk', out.addFk),
    ...section('mig.sComments', out.comments),
    ...section('mig.sDropTables', out.dropTable),
  ].join('\n');

  return { changes, sql: changes.length ? sql : `-- ${tr('mig.none')}\n` };
}
