// Локализация: українська та English
const DICT = {
  uk: {
    'app.tagline': 'Моделювання даних для Oracle',
    'tb.new': 'Нова', 'tb.new.t': 'Нова модель',
    'tb.open': 'Відкрити', 'tb.open.t': 'Відкрити .json',
    'tb.save': 'Зберегти', 'tb.save.t': 'Зберегти .json (⌘S)',
    'tb.import': 'Імпорт DDL', 'tb.import.t': 'Імпорт зі скрипта DDL',
    'tb.ddl': 'DDL', 'tb.ddl.t': 'Згенерувати Oracle DDL',
    'tb.svg': 'SVG', 'tb.svg.t': 'Експорт діаграми в SVG',
    'tb.table': 'Таблиця', 'tb.table.t': 'Нова таблиця (T)',
    'tb.relation': 'Звʼязок', 'tb.relation.t': 'Зовнішній ключ (R)',
    'tb.layout': 'Розкласти', 'tb.layout.t': 'Авторозкладка',
    'tb.undo.t': 'Скасувати (⌘Z)', 'tb.redo.t': 'Повторити (⌘⇧Z)',
    'tb.zoomIn.t': 'Збільшити', 'tb.zoomOut.t': 'Зменшити', 'tb.fit.t': 'Показати все (F)',
    'canvas.label': 'Діаграма моделі',

    'model.default': 'Нова модель',
    'p.model': 'Модель', 'p.name': 'Назва',
    'p.stat.tables': 'таблиць', 'p.stat.fks': 'звʼязків', 'p.stat.cols': 'колонок',
    'p.hints': 'Підказки',
    'p.hint1': '<b>Подвійний клік</b> по полотну — нова таблиця',
    'p.hint2': '<b>Звʼязок</b>: увімкніть режим, клікніть дочірню, потім батьківську таблицю',
    'p.hint3': '<b>Колесо</b> або тачпад — прокрутка, <b>Ctrl + колесо</b> — масштаб',
    'p.hint4': '<b>Del</b> — видалити, <b>⌘Z / ⌘⇧Z</b> — скасувати / повторити',
    'p.table': 'Таблиця', 'p.delete': 'Видалити', 'p.schema': 'Схема', 'p.comment': 'Коментар',
    'p.columns': 'Колонки', 'p.addColumn': 'Колонка',
    'p.col.name': 'Імʼя', 'p.col.type': 'Тип',
    'p.pk.t': 'Первинний ключ', 'p.more.t': 'Більше', 'p.up.t': 'Вгору', 'p.del.t': 'Видалити',
    'p.default.ph': 'напр. SYSDATE', 'p.identity': 'IDENTITY (GENERATED BY DEFAULT ON NULL)',
    'p.uniques': 'Унікальні ключі', 'p.indexes': 'Індекси', 'p.relations': 'Звʼязки', 'p.none': 'немає',
    'p.fk': 'Зовнішній ключ', 'p.mandatory': 'Обовʼязковий (колонки NOT NULL)',
    'd.noColumns': 'немає колонок',

    'ddl.title': 'Oracle DDL', 'ddl.comments': 'COMMENT ON', 'ddl.drop': 'DROP TABLE перед створенням',
    'ddl.copy': 'Копіювати', 'ddl.download': 'Завантажити .sql', 'ddl.header': 'Згенеровано Ferret Data Modeler', 'ddl.model': 'Модель',
    'imp.title': 'Імпорт DDL',
    'imp.desc': 'Підтримується: CREATE TABLE, ALTER TABLE … ADD CONSTRAINT (PK / UK / FK), CREATE [UNIQUE] INDEX, COMMENT ON. Інші команди пропускаються.',
    'imp.replace': 'Замінити поточну модель', 'imp.file': 'З файлу…', 'imp.sample': 'Демо-схема', 'imp.run': 'Імпортувати',
    'imp.warnings': 'Попередження ({n})',
    'close': 'Закрити',

    't.relCreated': 'Звʼязок створено',
    't.relHint': 'Клікніть дочірню таблицю, потім батьківську (Esc — скасувати)',
    't.opened': 'Модель відкрито', 't.openFail': 'Не вдалося відкрити: {e}',
    't.copied': 'Скопійовано', 't.pasteDDL': 'Вставте скрипт DDL',
    't.imported': 'Імпортовано таблиць: {n}', 't.importedWarn': ', попереджень: {n}',
    'confirm.new': 'Створити нову порожню модель? Зміни можна повернути через ⌘Z.',

    'e.format': 'Невірний формат моделі',
    'e.noPk': 'У таблиці {t} немає первинного ключа',
    'w.expected': 'Очікувалося {a}, отримано {b}', 'w.end': 'кінець',
    'w.expectedName': 'Очікувалося імʼя, отримано {b}', 'w.paren': 'Незакрита дужка',
    'w.in': '{m} у «{s}…»',
    'w.alterNoTable': 'ALTER TABLE: таблицю не знайдено',
    'w.skipped': 'Пропущено: {s}…',
    'w.replaced': 'Таблиця {t} вже є — замінено',
    'w.noCols': '{t}: CREATE TABLE без списку колонок пропущено',
    'w.idxNoTable': 'Індекс {i}: таблицю не знайдено',
    'w.idxFunc': 'Індекс {i}: функціональні індекси поки не підтримуються',
    'w.fkNoTable': 'FK {f}: таблицю {t} не знайдено',
    'w.fkNoCols': 'FK {f}: колонки не знайдено',
  },
  en: {
    'app.tagline': 'Data modelling for Oracle',
    'tb.new': 'New', 'tb.new.t': 'New model',
    'tb.open': 'Open', 'tb.open.t': 'Open .json',
    'tb.save': 'Save', 'tb.save.t': 'Save .json (⌘S)',
    'tb.import': 'Import DDL', 'tb.import.t': 'Import from a DDL script',
    'tb.ddl': 'DDL', 'tb.ddl.t': 'Generate Oracle DDL',
    'tb.svg': 'SVG', 'tb.svg.t': 'Export diagram as SVG',
    'tb.table': 'Table', 'tb.table.t': 'New table (T)',
    'tb.relation': 'Relation', 'tb.relation.t': 'Foreign key (R)',
    'tb.layout': 'Arrange', 'tb.layout.t': 'Auto layout',
    'tb.undo.t': 'Undo (⌘Z)', 'tb.redo.t': 'Redo (⌘⇧Z)',
    'tb.zoomIn.t': 'Zoom in', 'tb.zoomOut.t': 'Zoom out', 'tb.fit.t': 'Fit to screen (F)',
    'canvas.label': 'Model diagram',

    'model.default': 'New model',
    'p.model': 'Model', 'p.name': 'Name',
    'p.stat.tables': 'tables', 'p.stat.fks': 'relations', 'p.stat.cols': 'columns',
    'p.hints': 'Tips',
    'p.hint1': '<b>Double-click</b> the canvas to add a table',
    'p.hint2': '<b>Relation</b>: turn the mode on, click the child table, then the parent',
    'p.hint3': '<b>Wheel</b> or trackpad pans, <b>Ctrl + wheel</b> zooms',
    'p.hint4': '<b>Del</b> deletes, <b>⌘Z / ⌘⇧Z</b> undo / redo',
    'p.table': 'Table', 'p.delete': 'Delete', 'p.schema': 'Schema', 'p.comment': 'Comment',
    'p.columns': 'Columns', 'p.addColumn': 'Column',
    'p.col.name': 'Name', 'p.col.type': 'Type',
    'p.pk.t': 'Primary key', 'p.more.t': 'More', 'p.up.t': 'Move up', 'p.del.t': 'Delete',
    'p.default.ph': 'e.g. SYSDATE', 'p.identity': 'IDENTITY (GENERATED BY DEFAULT ON NULL)',
    'p.uniques': 'Unique keys', 'p.indexes': 'Indexes', 'p.relations': 'Relations', 'p.none': 'none',
    'p.fk': 'Foreign key', 'p.mandatory': 'Mandatory (columns NOT NULL)',
    'd.noColumns': 'no columns',

    'ddl.title': 'Oracle DDL', 'ddl.comments': 'COMMENT ON', 'ddl.drop': 'DROP TABLE before create',
    'ddl.copy': 'Copy', 'ddl.download': 'Download .sql', 'ddl.header': 'Generated by Ferret Data Modeler', 'ddl.model': 'Model',
    'imp.title': 'Import DDL',
    'imp.desc': 'Supported: CREATE TABLE, ALTER TABLE … ADD CONSTRAINT (PK / UK / FK), CREATE [UNIQUE] INDEX, COMMENT ON. Other statements are skipped.',
    'imp.replace': 'Replace current model', 'imp.file': 'From file…', 'imp.sample': 'Sample schema', 'imp.run': 'Import',
    'imp.warnings': 'Warnings ({n})',
    'close': 'Close',

    't.relCreated': 'Relation created',
    't.relHint': 'Click the child table, then the parent (Esc to cancel)',
    't.opened': 'Model opened', 't.openFail': 'Could not open: {e}',
    't.copied': 'Copied', 't.pasteDDL': 'Paste a DDL script',
    't.imported': 'Tables imported: {n}', 't.importedWarn': ', warnings: {n}',
    'confirm.new': 'Create a new empty model? You can bring the current one back with ⌘Z.',

    'e.format': 'Invalid model format',
    'e.noPk': 'Table {t} has no primary key',
    'w.expected': 'Expected {a}, got {b}', 'w.end': 'end of input',
    'w.expectedName': 'Expected a name, got {b}', 'w.paren': 'Unclosed parenthesis',
    'w.in': '{m} in “{s}…”',
    'w.alterNoTable': 'ALTER TABLE: table not found',
    'w.skipped': 'Skipped: {s}…',
    'w.replaced': 'Table {t} already existed and was replaced',
    'w.noCols': '{t}: CREATE TABLE without a column list skipped',
    'w.idxNoTable': 'Index {i}: table not found',
    'w.idxFunc': 'Index {i}: function-based indexes are not supported yet',
    'w.fkNoTable': 'FK {f}: table {t} not found',
    'w.fkNoCols': 'FK {f}: columns not found',
  },
};

function detect() {
  try { const saved = localStorage.getItem('ferret-lang'); if (DICT[saved]) return saved; } catch {}
  const nav = typeof navigator !== 'undefined' ? navigator.languages || [navigator.language] : [];
  return nav.some(l => /^(uk|ru|be)/i.test(l)) ? 'uk' : 'en';
}

let lang = detect();
const listeners = new Set();

export const getLang = () => lang;
export function setLang(l) {
  if (!DICT[l] || l === lang) return;
  lang = l;
  try { localStorage.setItem('ferret-lang', l); } catch {}
  listeners.forEach(fn => fn(l));
}
export const onLang = fn => listeners.add(fn);

export function t(key, params = {}) {
  const s = DICT[lang][key] ?? DICT.en[key] ?? key;
  return s.replace(/\{(\w+)\}/g, (_, k) => params[k] ?? '');
}

// Статичний HTML: data-i18n (текст), data-i18n-html, data-i18n-title, data-i18n-ph
export function applyStatic(root = document) {
  document.documentElement.lang = lang;
  root.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = t(el.dataset.i18n); });
  root.querySelectorAll('[data-i18n-title]').forEach(el => { el.title = t(el.dataset.i18nTitle); el.setAttribute('aria-label', el.title); });
  root.querySelectorAll('[data-i18n-label]').forEach(el => el.setAttribute('aria-label', t(el.dataset.i18nLabel)));
}
