// Панель свойств: таблица (колонки, ключи, индексы) или связь
import { ORACLE_TYPES, newColumn, uid, uniqueName } from './model.js';

const esc = s => String(s ?? '').replace(/[&<>"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[ch]));
const upper = v => v.trim().toUpperCase().replace(/\s+/g, '_');

export class Panel {
  constructor(el, store) {
    this.el = el; this.store = store;
    store.subscribe(r => { if (r !== 'panel' && r !== 'move') this.render(); });
    el.addEventListener('change', e => this.onChange(e));
    el.addEventListener('click', e => this.onClick(e));
    document.body.insertAdjacentHTML('beforeend',
      `<datalist id="oracle-types">${ORACLE_TYPES.map(t => `<option value="${t}">`).join('')}</datalist>`);
  }

  render() {
    const s = this.store.selection;
    const m = this.store.model;
    if (!s) {
      this.el.innerHTML = `
        <h2>Модель</h2>
        <label>Название<input data-f="model.name" value="${esc(m.name)}"></label>
        <div class="stats"><div><b>${m.tables.length}</b> таблиц</div><div><b>${m.fks.length}</b> связей</div>
          <div><b>${m.tables.reduce((n, t) => n + t.columns.length, 0)}</b> колонок</div></div>
        <div class="hint">
          <p><b>Двойной клик</b> по холсту — новая таблица</p>
          <p><b>Связь</b>: выберите режим, кликните дочернюю, затем родительскую таблицу</p>
          <p><b>Колесо</b> / тачпад — прокрутка, <b>Ctrl+колесо</b> — масштаб</p>
          <p><b>Del</b> — удалить, <b>⌘Z / ⌘⇧Z</b> — отмена / повтор</p>
        </div>`;
      return;
    }
    if (s.kind === 'fk') return this.renderFk(m.fks.find(f => f.id === s.id));
    this.renderTable(this.store.table(s.id));
  }

  renderTable(t) {
    const m = this.store.model;
    const cols = t.columns.map((c, i) => `
      <tr data-col="${c.id}">
        <td><input data-f="col.name" value="${esc(c.name)}" spellcheck="false"></td>
        <td><input data-f="col.type" value="${esc(c.type)}" list="oracle-types" spellcheck="false"></td>
        <td class="c"><input type="checkbox" data-f="col.pk" ${c.pk ? 'checked' : ''} title="Первичный ключ"></td>
        <td class="c"><input type="checkbox" data-f="col.nn" ${!c.nullable || c.pk ? 'checked' : ''} ${c.pk ? 'disabled' : ''} title="NOT NULL"></td>
        <td class="actions">
          <button data-a="col-more" title="Ещё">⋯</button>
          <button data-a="col-up" ${i ? '' : 'disabled'} title="Вверх">↑</button>
          <button data-a="col-del" title="Удалить">✕</button>
        </td>
      </tr>
      <tr class="more ${this.openCol === c.id ? '' : 'hidden'}" data-col="${c.id}"><td colspan="5">
        <label>DEFAULT<input data-f="col.default" value="${esc(c.default)}" placeholder="напр. SYSDATE" ${c.identity ? 'disabled' : ''}></label>
        <label class="check"><input type="checkbox" data-f="col.identity" ${c.identity ? 'checked' : ''}> IDENTITY (GENERATED BY DEFAULT ON NULL)</label>
        <label>Комментарий<input data-f="col.comment" value="${esc(c.comment)}"></label>
      </td></tr>`).join('');

    const colOptions = sel => t.columns.map(c => `<option value="${c.id}" ${sel.includes(c.id) ? 'selected' : ''}>${esc(c.name)}</option>`).join('');
    const keyList = (arr, kind) => arr.map(x => `
      <div class="key" data-${kind}="${x.id}">
        <div class="row"><input data-f="${kind}.name" value="${esc(x.name)}" spellcheck="false">
          ${kind === 'idx' ? `<label class="check"><input type="checkbox" data-f="idx.unique" ${x.unique ? 'checked' : ''}> UNIQUE</label>` : ''}
          <button data-a="${kind}-del" title="Удалить">✕</button></div>
        <select multiple data-f="${kind}.columns" size="${Math.min(4, Math.max(2, t.columns.length))}">${colOptions(x.columns)}</select>
      </div>`).join('');

    const fks = m.fks.filter(f => f.fromTable === t.id || f.toTable === t.id).map(f => {
      const other = this.store.table(f.fromTable === t.id ? f.toTable : f.fromTable);
      return `<li><a data-a="goto-fk" data-id="${f.id}">${esc(f.name)}</a> <span class="muted">${f.fromTable === t.id ? '→' : '←'} ${esc(other?.name)}</span></li>`;
    }).join('');

    this.el.innerHTML = `
      <h2>Таблица <button class="danger small" data-a="table-del">Удалить</button></h2>
      <div class="grid2">
        <label>Имя<input data-f="table.name" value="${esc(t.name)}" spellcheck="false"></label>
        <label>Схема<input data-f="table.schema" value="${esc(t.schema)}" placeholder="—" spellcheck="false"></label>
      </div>
      <label>Комментарий<textarea data-f="table.comment" rows="2">${esc(t.comment)}</textarea></label>

      <h3>Колонки <button class="small" data-a="col-add">+ Колонка</button></h3>
      <table class="cols"><thead><tr><th>Имя</th><th>Тип</th><th title="Primary key">PK</th><th title="NOT NULL">NN</th><th></th></tr></thead>
        <tbody>${cols}</tbody></table>

      <h3>Уникальные ключи <button class="small" data-a="uk-add">+</button></h3>
      ${keyList(t.uniques, 'uk') || '<p class="muted">нет</p>'}

      <h3>Индексы <button class="small" data-a="idx-add">+</button></h3>
      ${keyList(t.indexes, 'idx') || '<p class="muted">нет</p>'}

      <h3>Связи</h3>
      ${fks ? `<ul class="fklist">${fks}</ul>` : '<p class="muted">нет</p>'}`;
  }

  renderFk(f) {
    const from = this.store.table(f.fromTable), to = this.store.table(f.toTable);
    const pairs = f.columns.map(p => `<tr><td>${esc(from.columns.find(c => c.id === p.from)?.name)}</td><td>→</td><td>${esc(to.columns.find(c => c.id === p.to)?.name)}</td></tr>`).join('');
    this.el.innerHTML = `
      <h2>Внешний ключ <button class="danger small" data-a="fk-del">Удалить</button></h2>
      <label>Имя<input data-f="fk.name" value="${esc(f.name)}" spellcheck="false"></label>
      <p class="rel-desc"><a data-a="goto-table" data-id="${from.id}">${esc(from.name)}</a> → <a data-a="goto-table" data-id="${to.id}">${esc(to.name)}</a></p>
      <table class="pairs">${pairs}</table>
      <label>ON DELETE<select data-f="fk.onDelete">
        ${[['', 'NO ACTION'], ['CASCADE', 'CASCADE'], ['SET NULL', 'SET NULL']].map(([v, l]) => `<option value="${v}" ${f.onDelete === v ? 'selected' : ''}>${l}</option>`).join('')}
      </select></label>
      <label class="check"><input type="checkbox" data-f="fk.mandatory" ${f.columns.every(p => from.columns.find(c => c.id === p.from)?.nullable === false) ? 'checked' : ''}> Обязательная (колонки NOT NULL)</label>`;
  }

  ctx(target) {
    const s = this.store.selection;
    return {
      colId: target.closest('[data-col]')?.dataset.col,
      ukId: target.closest('[data-uk]')?.dataset.uk,
      idxId: target.closest('[data-idx]')?.dataset.idx,
      tableId: s?.kind === 'table' ? s.id : null,
      fkId: s?.kind === 'fk' ? s.id : null,
    };
  }

  onChange(e) {
    const el = e.target, f = el.dataset.f;
    if (!f) return;
    const c = this.ctx(el);
    const val = el.type === 'checkbox' ? el.checked : el.value;
    let rerender = false;
    this.store.update(m => {
      const t = c.tableId && m.tables.find(x => x.id === c.tableId);
      const col = t && c.colId && t.columns.find(x => x.id === c.colId);
      const uk = t && c.ukId && t.uniques.find(x => x.id === c.ukId);
      const idx = t && c.idxId && t.indexes.find(x => x.id === c.idxId);
      const fk = c.fkId && m.fks.find(x => x.id === c.fkId);
      switch (f) {
        case 'model.name': m.name = val; break;
        case 'table.name': t.name = el.value = upper(val) || t.name; break;
        case 'table.schema': t.schema = el.value = upper(val); break;
        case 'table.comment': t.comment = val; break;
        case 'col.name': col.name = el.value = upper(val) || col.name; break;
        case 'col.type': col.type = el.value = val.trim().toUpperCase(); break;
        case 'col.pk': col.pk = val; if (val) col.nullable = false; rerender = true; break;
        case 'col.nn': col.nullable = !val; break;
        case 'col.default': col.default = val.trim(); break;
        case 'col.identity': col.identity = val; if (val) { col.nullable = false; col.default = ''; } rerender = true; break;
        case 'col.comment': col.comment = val; break;
        case 'uk.name': uk.name = el.value = upper(val) || uk.name; break;
        case 'idx.name': idx.name = el.value = upper(val) || idx.name; break;
        case 'idx.unique': idx.unique = val; break;
        case 'uk.columns': case 'idx.columns':
          (uk || idx).columns = [...el.selectedOptions].map(o => o.value); break;
        case 'fk.name': fk.name = el.value = upper(val) || fk.name; break;
        case 'fk.onDelete': fk.onDelete = val; break;
        case 'fk.mandatory': {
          const from = m.tables.find(x => x.id === fk.fromTable);
          fk.columns.forEach(p => { const cc = from.columns.find(x => x.id === p.from); if (cc && !cc.pk) cc.nullable = !val; });
          break;
        }
      }
    }, rerender ? 'change' : 'panel');
  }

  onClick(e) {
    const btn = e.target.closest('[data-a]');
    if (!btn || btn.disabled) return;
    const a = btn.dataset.a, c = this.ctx(btn), st = this.store;
    const t = c.tableId && st.table(c.tableId);
    switch (a) {
      case 'table-del': st.deleteTable(c.tableId); break;
      case 'col-add': {
        const col = newColumn(t.columns.length ? `COLUMN_${t.columns.length + 1}` : 'ID', t.columns.length ? 'VARCHAR2(100 CHAR)' : 'NUMBER');
        if (!t.columns.length) { col.pk = true; col.identity = true; col.nullable = false; }
        st.update(() => t.columns.push(col));
        this.el.querySelector(`tr[data-col="${col.id}"] input`)?.select();
        break;
      }
      case 'col-del': st.deleteColumn(t.id, c.colId); break;
      case 'col-up': st.update(() => {
        const i = t.columns.findIndex(x => x.id === c.colId);
        [t.columns[i - 1], t.columns[i]] = [t.columns[i], t.columns[i - 1]];
      }); break;
      case 'col-more':
        this.openCol = this.openCol === c.colId ? null : c.colId;
        this.render(); break;
      case 'uk-add': st.update(m => t.uniques.push({ id: uid('u'), name: uniqueName(m, `${t.name}_UN`), columns: [] })); break;
      case 'idx-add': st.update(m => t.indexes.push({ id: uid('i'), name: uniqueName(m, `${t.name}_IDX`), unique: false, columns: [] })); break;
      case 'uk-del': st.update(() => { t.uniques = t.uniques.filter(x => x.id !== c.ukId); }); break;
      case 'idx-del': st.update(() => { t.indexes = t.indexes.filter(x => x.id !== c.idxId); }); break;
      case 'fk-del': st.update(m => { m.fks = m.fks.filter(x => x.id !== c.fkId); }); st.select(null); break;
      case 'goto-fk': st.select({ kind: 'fk', id: btn.dataset.id }); break;
      case 'goto-table': st.select({ kind: 'table', id: btn.dataset.id }); break;
    }
  }
}
