// Sample schema: online store orders
export const SAMPLE_DDL = `
CREATE TABLE customers (
  customer_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email         VARCHAR2(255 CHAR) NOT NULL,
  full_name     VARCHAR2(200 CHAR) NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT customers_pk PRIMARY KEY (customer_id),
  CONSTRAINT customers_email_un UNIQUE (email)
);
COMMENT ON TABLE customers IS 'Customers';

CREATE TABLE products (
  product_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  sku           VARCHAR2(40 CHAR) NOT NULL UNIQUE,
  name          VARCHAR2(200 CHAR) NOT NULL,
  price         NUMBER(12,2) NOT NULL,
  attributes    JSON
);

CREATE TABLE orders (
  order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id   NUMBER NOT NULL,
  status        VARCHAR2(20 CHAR) DEFAULT 'NEW' NOT NULL,
  ordered_at    DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT orders_pk PRIMARY KEY (order_id)
);

CREATE TABLE order_items (
  order_id      NUMBER NOT NULL,
  line_no       NUMBER(4) NOT NULL,
  product_id    NUMBER NOT NULL,
  quantity      NUMBER(6) NOT NULL,
  unit_price    NUMBER(12,2) NOT NULL,
  CONSTRAINT order_items_pk PRIMARY KEY (order_id, line_no)
);

ALTER TABLE orders ADD CONSTRAINT orders_customers_fk FOREIGN KEY (customer_id) REFERENCES customers (customer_id);
ALTER TABLE order_items ADD CONSTRAINT order_items_orders_fk FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE;
ALTER TABLE order_items ADD CONSTRAINT order_items_products_fk FOREIGN KEY (product_id) REFERENCES products (product_id);
CREATE INDEX orders_customer_idx ON orders (customer_id);
`;
