// Ready-made Oracle schemas (DDL is the source; comments are in Ukrainian)
const ID = 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY';
const AUDIT = `created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP`;

export const TEMPLATES = [
  {
    id: 'shop', icon: '🛒', tables: 10,
    name: { uk: 'Інтернет-магазин', en: 'Online store' },
    desc: { uk: 'Покупці, адреси, товари, категорії, замовлення, оплати, купони, відгуки, доставка', en: 'Customers, addresses, products, categories, orders, payments, coupons, reviews, shipping' },
    ddl: `
CREATE SEQUENCE order_no_seq START WITH 100000 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE TABLE customers (
  customer_id ${ID},
  email VARCHAR2(255 CHAR) NOT NULL,
  full_name VARCHAR2(200 CHAR) NOT NULL,
  phone VARCHAR2(20 CHAR),
  ${AUDIT},
  CONSTRAINT customers_pk PRIMARY KEY (customer_id),
  CONSTRAINT customers_email_un UNIQUE (email)
);
COMMENT ON TABLE customers IS 'Покупці';
COMMENT ON COLUMN customers.email IS 'Електронна пошта для входу';

CREATE TABLE addresses (
  address_id ${ID},
  customer_id NUMBER NOT NULL,
  city VARCHAR2(100 CHAR) NOT NULL,
  street VARCHAR2(200 CHAR) NOT NULL,
  postcode VARCHAR2(10 CHAR),
  is_default CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT addresses_pk PRIMARY KEY (address_id)
);
COMMENT ON TABLE addresses IS 'Адреси доставки';

CREATE TABLE categories (
  category_id ${ID},
  parent_id NUMBER,
  name VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT categories_pk PRIMARY KEY (category_id)
);
COMMENT ON TABLE categories IS 'Дерево категорій';

CREATE TABLE products (
  product_id ${ID},
  category_id NUMBER NOT NULL,
  sku VARCHAR2(40 CHAR) NOT NULL,
  name VARCHAR2(200 CHAR) NOT NULL,
  price NUMBER(12,2) NOT NULL,
  stock_qty NUMBER(10) DEFAULT 0 NOT NULL,
  attributes JSON,
  CONSTRAINT products_pk PRIMARY KEY (product_id),
  CONSTRAINT products_sku_un UNIQUE (sku),
  CONSTRAINT products_price_ck CHECK (price >= 0)
);
COMMENT ON TABLE products IS 'Товари';

CREATE TABLE orders (
  order_id ${ID},
  order_no NUMBER DEFAULT order_no_seq.NEXTVAL NOT NULL,
  customer_id NUMBER NOT NULL,
  address_id NUMBER NOT NULL,
  coupon_id NUMBER,
  status VARCHAR2(20 CHAR) DEFAULT 'NEW' NOT NULL,
  total NUMBER(12,2) NOT NULL,
  ordered_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT orders_pk PRIMARY KEY (order_id),
  CONSTRAINT orders_no_un UNIQUE (order_no),
  CONSTRAINT orders_status_ck CHECK (status IN ('NEW', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
)
PARTITION BY RANGE (ordered_at) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(PARTITION p_start VALUES LESS THAN (DATE '2025-01-01'));
COMMENT ON TABLE orders IS 'Замовлення';

CREATE TABLE order_items (
  order_id NUMBER NOT NULL,
  line_no NUMBER(4) NOT NULL,
  product_id NUMBER NOT NULL,
  quantity NUMBER(6) NOT NULL,
  unit_price NUMBER(12,2) NOT NULL,
  line_total NUMBER(14,2) GENERATED ALWAYS AS (quantity * unit_price) VIRTUAL,
  CONSTRAINT order_items_pk PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_items_qty_ck CHECK (quantity > 0)
);
COMMENT ON TABLE order_items IS 'Позиції замовлення';

CREATE TABLE payments (
  payment_id ${ID},
  order_id NUMBER NOT NULL,
  amount NUMBER(12,2) NOT NULL,
  method VARCHAR2(20 CHAR) NOT NULL,
  paid_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT payments_pk PRIMARY KEY (payment_id)
);
COMMENT ON TABLE payments IS 'Оплати';

CREATE TABLE coupons (
  coupon_id ${ID},
  code VARCHAR2(30 CHAR) NOT NULL,
  discount_pct NUMBER(5,2) NOT NULL,
  valid_from DATE DEFAULT SYSDATE NOT NULL,
  valid_to DATE NOT NULL,
  CONSTRAINT coupons_pk PRIMARY KEY (coupon_id),
  CONSTRAINT coupons_code_un UNIQUE (code),
  CONSTRAINT coupons_pct_ck CHECK (discount_pct BETWEEN 0 AND 100)
);
COMMENT ON TABLE coupons IS 'Знижкові купони';

CREATE TABLE reviews (
  review_id ${ID},
  product_id NUMBER NOT NULL,
  customer_id NUMBER NOT NULL,
  rating NUMBER(1) NOT NULL,
  body VARCHAR2(2000 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT reviews_pk PRIMARY KEY (review_id),
  CONSTRAINT reviews_one_un UNIQUE (product_id, customer_id),
  CONSTRAINT reviews_rating_ck CHECK (rating BETWEEN 1 AND 5)
);
COMMENT ON TABLE reviews IS 'Відгуки на товари';

CREATE TABLE shipments (
  shipment_id ${ID},
  order_id NUMBER NOT NULL,
  carrier VARCHAR2(50 CHAR) NOT NULL,
  tracking_no VARCHAR2(40 CHAR),
  status VARCHAR2(15 CHAR) DEFAULT 'PREPARING' NOT NULL,
  shipped_at TIMESTAMP,
  delivered_at TIMESTAMP,
  CONSTRAINT shipments_pk PRIMARY KEY (shipment_id),
  CONSTRAINT shipments_order_un UNIQUE (order_id),
  CONSTRAINT shipments_status_ck CHECK (status IN ('PREPARING', 'SHIPPED', 'DELIVERED', 'RETURNED'))
);
COMMENT ON TABLE shipments IS 'Доставка (одна на замовлення)';

ALTER TABLE addresses ADD CONSTRAINT addresses_customers_fk FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE;
ALTER TABLE categories ADD CONSTRAINT categories_parent_fk FOREIGN KEY (parent_id) REFERENCES categories (category_id);
ALTER TABLE products ADD CONSTRAINT products_categories_fk FOREIGN KEY (category_id) REFERENCES categories (category_id);
ALTER TABLE orders ADD CONSTRAINT orders_customers_fk FOREIGN KEY (customer_id) REFERENCES customers (customer_id);
ALTER TABLE orders ADD CONSTRAINT orders_addresses_fk FOREIGN KEY (address_id) REFERENCES addresses (address_id);
ALTER TABLE orders ADD CONSTRAINT orders_coupons_fk FOREIGN KEY (coupon_id) REFERENCES coupons (coupon_id);
ALTER TABLE order_items ADD CONSTRAINT order_items_orders_fk FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE;
ALTER TABLE order_items ADD CONSTRAINT order_items_products_fk FOREIGN KEY (product_id) REFERENCES products (product_id);
ALTER TABLE payments ADD CONSTRAINT payments_orders_fk FOREIGN KEY (order_id) REFERENCES orders (order_id);
ALTER TABLE reviews ADD CONSTRAINT reviews_products_fk FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE CASCADE;
ALTER TABLE reviews ADD CONSTRAINT reviews_customers_fk FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE;
ALTER TABLE shipments ADD CONSTRAINT shipments_orders_fk FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE;
CREATE INDEX orders_customer_idx ON orders (customer_id);
CREATE INDEX products_category_idx ON products (category_id);

CREATE OR REPLACE VIEW v_customer_sales AS
SELECT c.customer_id,
       c.full_name,
       COUNT(o.order_id) AS orders_count,
       NVL(SUM(o.total), 0) AS revenue
  FROM customers c
  LEFT JOIN orders o ON o.customer_id = c.customer_id AND o.status <> 'CANCELLED'
 GROUP BY c.customer_id, c.full_name;
COMMENT ON TABLE v_customer_sales IS 'Продажі по покупцях';
`,
  },
  {
    id: 'hr', icon: '👥', tables: 9,
    name: { uk: 'Кадри (HR)', en: 'Human resources' },
    desc: { uk: 'Регіони, локації, відділи, посади, працівники, історія посад, навички, відпустки', en: 'Regions, locations, departments, jobs, employees, job history, skills, leave' },
    ddl: `
CREATE TABLE regions (
  region_id NUMBER NOT NULL,
  region_name VARCHAR2(50 CHAR) NOT NULL,
  CONSTRAINT regions_pk PRIMARY KEY (region_id)
);
COMMENT ON TABLE regions IS 'Регіони';

CREATE TABLE locations (
  location_id ${ID},
  region_id NUMBER NOT NULL,
  city VARCHAR2(100 CHAR) NOT NULL,
  street_address VARCHAR2(200 CHAR),
  postal_code VARCHAR2(12 CHAR),
  CONSTRAINT locations_pk PRIMARY KEY (location_id)
);
COMMENT ON TABLE locations IS 'Офіси та локації';

CREATE TABLE departments (
  department_id ${ID},
  department_name VARCHAR2(100 CHAR) NOT NULL,
  manager_id NUMBER,
  location_id NUMBER,
  CONSTRAINT departments_pk PRIMARY KEY (department_id)
);
COMMENT ON TABLE departments IS 'Відділи';

CREATE TABLE jobs (
  job_id VARCHAR2(10 CHAR) NOT NULL,
  job_title VARCHAR2(100 CHAR) NOT NULL,
  min_salary NUMBER(10,2),
  max_salary NUMBER(10,2),
  CONSTRAINT jobs_pk PRIMARY KEY (job_id)
);
COMMENT ON TABLE jobs IS 'Посади';

CREATE TABLE employees (
  employee_id ${ID},
  first_name VARCHAR2(50 CHAR) NOT NULL,
  last_name VARCHAR2(50 CHAR) NOT NULL,
  email VARCHAR2(255 CHAR) NOT NULL,
  hire_date DATE DEFAULT SYSDATE NOT NULL,
  job_id VARCHAR2(10 CHAR) NOT NULL,
  salary NUMBER(10,2),
  manager_id NUMBER,
  department_id NUMBER,
  CONSTRAINT employees_pk PRIMARY KEY (employee_id),
  CONSTRAINT employees_email_un UNIQUE (email)
);
COMMENT ON TABLE employees IS 'Працівники';
COMMENT ON COLUMN employees.manager_id IS 'Безпосередній керівник';

CREATE TABLE job_history (
  employee_id NUMBER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  job_id VARCHAR2(10 CHAR) NOT NULL,
  department_id NUMBER,
  CONSTRAINT job_history_pk PRIMARY KEY (employee_id, start_date)
);
COMMENT ON TABLE job_history IS 'Історія зміни посад';

CREATE TABLE skills (
  skill_id ${ID},
  name VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT skills_pk PRIMARY KEY (skill_id),
  CONSTRAINT skills_name_un UNIQUE (name)
);
COMMENT ON TABLE skills IS 'Навички';

CREATE TABLE employee_skills (
  employee_id NUMBER NOT NULL,
  skill_id NUMBER NOT NULL,
  skill_level NUMBER(1) NOT NULL,
  CONSTRAINT employee_skills_pk PRIMARY KEY (employee_id, skill_id),
  CONSTRAINT employee_skills_level_ck CHECK (skill_level BETWEEN 1 AND 5)
);
COMMENT ON TABLE employee_skills IS 'Навички працівників (M:N), 1-5 — рівень володіння';

CREATE TABLE leave_requests (
  leave_id ${ID},
  employee_id NUMBER NOT NULL,
  leave_type VARCHAR2(10 CHAR) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR2(10 CHAR) DEFAULT 'PENDING' NOT NULL,
  CONSTRAINT leave_requests_pk PRIMARY KEY (leave_id),
  CONSTRAINT leave_requests_type_ck CHECK (leave_type IN ('VACATION', 'SICK', 'UNPAID')),
  CONSTRAINT leave_requests_status_ck CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT leave_requests_dates_ck CHECK (end_date >= start_date)
);
COMMENT ON TABLE leave_requests IS 'Заяви на відпустку/лікарняний';

ALTER TABLE locations ADD CONSTRAINT locations_regions_fk FOREIGN KEY (region_id) REFERENCES regions (region_id);
ALTER TABLE departments ADD CONSTRAINT departments_locations_fk FOREIGN KEY (location_id) REFERENCES locations (location_id);
ALTER TABLE departments ADD CONSTRAINT departments_manager_fk FOREIGN KEY (manager_id) REFERENCES employees (employee_id);
ALTER TABLE employees ADD CONSTRAINT employees_jobs_fk FOREIGN KEY (job_id) REFERENCES jobs (job_id);
ALTER TABLE employees ADD CONSTRAINT employees_manager_fk FOREIGN KEY (manager_id) REFERENCES employees (employee_id);
ALTER TABLE employees ADD CONSTRAINT employees_departments_fk FOREIGN KEY (department_id) REFERENCES departments (department_id);
ALTER TABLE job_history ADD CONSTRAINT job_history_employees_fk FOREIGN KEY (employee_id) REFERENCES employees (employee_id);
ALTER TABLE job_history ADD CONSTRAINT job_history_jobs_fk FOREIGN KEY (job_id) REFERENCES jobs (job_id);
ALTER TABLE job_history ADD CONSTRAINT job_history_departments_fk FOREIGN KEY (department_id) REFERENCES departments (department_id);
ALTER TABLE employee_skills ADD CONSTRAINT employee_skills_employees_fk FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE;
ALTER TABLE employee_skills ADD CONSTRAINT employee_skills_skills_fk FOREIGN KEY (skill_id) REFERENCES skills (skill_id) ON DELETE CASCADE;
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_employees_fk FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE;
`,
  },
  {
    id: 'uni', icon: '🎓', tables: 10,
    name: { uk: 'Університет', en: 'University' },
    desc: { uk: 'Факультети, групи, студенти, викладачі, дисципліни, оцінки, завдання, стипендії', en: 'Faculties, groups, students, teachers, courses, grades, assignments, scholarships' },
    ddl: `
CREATE TABLE faculties (
  faculty_id ${ID},
  name VARCHAR2(200 CHAR) NOT NULL,
  dean_name VARCHAR2(200 CHAR),
  CONSTRAINT faculties_pk PRIMARY KEY (faculty_id)
);
COMMENT ON TABLE faculties IS 'Факультети';

CREATE TABLE study_groups (
  group_id ${ID},
  faculty_id NUMBER NOT NULL,
  code VARCHAR2(20 CHAR) NOT NULL,
  admission_year NUMBER(4) NOT NULL,
  CONSTRAINT study_groups_pk PRIMARY KEY (group_id),
  CONSTRAINT study_groups_code_un UNIQUE (code)
);
COMMENT ON TABLE study_groups IS 'Академічні групи';

CREATE TABLE students (
  student_id ${ID},
  group_id NUMBER NOT NULL,
  full_name VARCHAR2(200 CHAR) NOT NULL,
  record_book_no VARCHAR2(20 CHAR) NOT NULL,
  birth_date DATE,
  email VARCHAR2(255 CHAR),
  CONSTRAINT students_pk PRIMARY KEY (student_id),
  CONSTRAINT students_record_book_un UNIQUE (record_book_no)
);
COMMENT ON TABLE students IS 'Студенти';
COMMENT ON COLUMN students.record_book_no IS 'Номер залікової книжки';

CREATE TABLE teachers (
  teacher_id ${ID},
  faculty_id NUMBER NOT NULL,
  full_name VARCHAR2(200 CHAR) NOT NULL,
  academic_title VARCHAR2(50 CHAR),
  CONSTRAINT teachers_pk PRIMARY KEY (teacher_id)
);
COMMENT ON TABLE teachers IS 'Викладачі';

CREATE TABLE subjects (
  subject_id ${ID},
  name VARCHAR2(200 CHAR) NOT NULL,
  credits NUMBER(3,1) NOT NULL,
  CONSTRAINT subjects_pk PRIMARY KEY (subject_id)
);
COMMENT ON TABLE subjects IS 'Дисципліни';

CREATE TABLE schedule (
  schedule_id ${ID},
  group_id NUMBER NOT NULL,
  subject_id NUMBER NOT NULL,
  teacher_id NUMBER NOT NULL,
  semester NUMBER(2) NOT NULL,
  CONSTRAINT schedule_pk PRIMARY KEY (schedule_id)
);
COMMENT ON TABLE schedule IS 'Навчальне навантаження';

CREATE TABLE grades (
  grade_id ${ID},
  student_id NUMBER NOT NULL,
  schedule_id NUMBER NOT NULL,
  score NUMBER(3) NOT NULL,
  graded_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT grades_pk PRIMARY KEY (grade_id)
);
COMMENT ON TABLE grades IS 'Оцінки (100-бальна шкала)';

CREATE TABLE assignments (
  assignment_id ${ID},
  schedule_id NUMBER NOT NULL,
  title VARCHAR2(200 CHAR) NOT NULL,
  due_date DATE NOT NULL,
  max_score NUMBER(3) DEFAULT 100 NOT NULL,
  CONSTRAINT assignments_pk PRIMARY KEY (assignment_id)
);
COMMENT ON TABLE assignments IS 'Завдання по дисципліні групи';

CREATE TABLE submissions (
  submission_id ${ID},
  assignment_id NUMBER NOT NULL,
  student_id NUMBER NOT NULL,
  submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  score NUMBER(3),
  CONSTRAINT submissions_pk PRIMARY KEY (submission_id),
  CONSTRAINT submissions_one_un UNIQUE (assignment_id, student_id)
);
COMMENT ON TABLE submissions IS 'Здані роботи студентів';

CREATE TABLE scholarships (
  scholarship_id ${ID},
  student_id NUMBER NOT NULL,
  name VARCHAR2(150 CHAR) NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  granted_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT scholarships_pk PRIMARY KEY (scholarship_id)
);
COMMENT ON TABLE scholarships IS 'Стипендії';

ALTER TABLE study_groups ADD CONSTRAINT study_groups_faculties_fk FOREIGN KEY (faculty_id) REFERENCES faculties (faculty_id);
ALTER TABLE students ADD CONSTRAINT students_groups_fk FOREIGN KEY (group_id) REFERENCES study_groups (group_id);
ALTER TABLE teachers ADD CONSTRAINT teachers_faculties_fk FOREIGN KEY (faculty_id) REFERENCES faculties (faculty_id);
ALTER TABLE schedule ADD CONSTRAINT schedule_groups_fk FOREIGN KEY (group_id) REFERENCES study_groups (group_id);
ALTER TABLE schedule ADD CONSTRAINT schedule_subjects_fk FOREIGN KEY (subject_id) REFERENCES subjects (subject_id);
ALTER TABLE schedule ADD CONSTRAINT schedule_teachers_fk FOREIGN KEY (teacher_id) REFERENCES teachers (teacher_id);
ALTER TABLE grades ADD CONSTRAINT grades_students_fk FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE;
ALTER TABLE grades ADD CONSTRAINT grades_schedule_fk FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id);
ALTER TABLE assignments ADD CONSTRAINT assignments_schedule_fk FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id) ON DELETE CASCADE;
ALTER TABLE submissions ADD CONSTRAINT submissions_assignments_fk FOREIGN KEY (assignment_id) REFERENCES assignments (assignment_id) ON DELETE CASCADE;
ALTER TABLE submissions ADD CONSTRAINT submissions_students_fk FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE;
ALTER TABLE scholarships ADD CONSTRAINT scholarships_students_fk FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE;
`,
  },
  {
    id: 'bank', icon: '🏦', tables: 9,
    name: { uk: 'Банк', en: 'Bank' },
    desc: { uk: 'Клієнти, рахунки, картки, транзакції, кредити, платежі, відділення, застава', en: 'Clients, accounts, cards, transactions, loans, repayments, branches, collateral' },
    ddl: `
CREATE TABLE clients (
  client_id ${ID},
  full_name VARCHAR2(200 CHAR) NOT NULL,
  tax_number VARCHAR2(10 CHAR) NOT NULL,
  phone VARCHAR2(20 CHAR),
  ${AUDIT},
  CONSTRAINT clients_pk PRIMARY KEY (client_id),
  CONSTRAINT clients_tax_un UNIQUE (tax_number)
);
COMMENT ON TABLE clients IS 'Клієнти банку';
COMMENT ON COLUMN clients.tax_number IS 'РНОКПП';

CREATE TABLE accounts (
  account_id ${ID},
  client_id NUMBER NOT NULL,
  branch_id NUMBER NOT NULL,
  iban VARCHAR2(29 CHAR) NOT NULL,
  currency CHAR(3) DEFAULT 'UAH' NOT NULL,
  balance NUMBER(18,2) DEFAULT 0 NOT NULL,
  opened_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT accounts_pk PRIMARY KEY (account_id),
  CONSTRAINT accounts_iban_un UNIQUE (iban)
);
COMMENT ON TABLE accounts IS 'Рахунки';

CREATE TABLE cards (
  card_id ${ID},
  account_id NUMBER NOT NULL,
  masked_pan VARCHAR2(19 CHAR) NOT NULL,
  expires_on DATE NOT NULL,
  status VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT cards_pk PRIMARY KEY (card_id)
);
COMMENT ON TABLE cards IS 'Платіжні картки';

CREATE TABLE transactions (
  transaction_id ${ID},
  account_id NUMBER NOT NULL,
  amount NUMBER(18,2) NOT NULL,
  direction CHAR(1) NOT NULL,
  description VARCHAR2(400 CHAR),
  booked_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT transactions_pk PRIMARY KEY (transaction_id)
);
COMMENT ON TABLE transactions IS 'Рух коштів';
COMMENT ON COLUMN transactions.direction IS 'D — дебет, C — кредит';

CREATE TABLE loans (
  loan_id ${ID},
  client_id NUMBER NOT NULL,
  principal NUMBER(18,2) NOT NULL,
  rate_pct NUMBER(5,2) NOT NULL,
  term_months NUMBER(4) NOT NULL,
  issued_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT loans_pk PRIMARY KEY (loan_id)
);
COMMENT ON TABLE loans IS 'Кредити';

CREATE TABLE loan_payments (
  loan_id NUMBER NOT NULL,
  payment_no NUMBER(4) NOT NULL,
  due_date DATE NOT NULL,
  amount NUMBER(18,2) NOT NULL,
  paid_at DATE,
  CONSTRAINT loan_payments_pk PRIMARY KEY (loan_id, payment_no)
);
COMMENT ON TABLE loan_payments IS 'Графік погашення';

CREATE TABLE branches (
  branch_id ${ID},
  name VARCHAR2(100 CHAR) NOT NULL,
  city VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT branches_pk PRIMARY KEY (branch_id)
);
COMMENT ON TABLE branches IS 'Відділення банку';

CREATE TABLE beneficiaries (
  beneficiary_id ${ID},
  client_id NUMBER NOT NULL,
  name VARCHAR2(200 CHAR) NOT NULL,
  iban VARCHAR2(29 CHAR) NOT NULL,
  CONSTRAINT beneficiaries_pk PRIMARY KEY (beneficiary_id)
);
COMMENT ON TABLE beneficiaries IS 'Збережені отримувачі переказів';

CREATE TABLE loan_collateral (
  collateral_id ${ID},
  loan_id NUMBER NOT NULL,
  description VARCHAR2(400 CHAR) NOT NULL,
  value NUMBER(18,2) NOT NULL,
  CONSTRAINT loan_collateral_pk PRIMARY KEY (collateral_id)
);
COMMENT ON TABLE loan_collateral IS 'Застава по кредиту';

ALTER TABLE accounts ADD CONSTRAINT accounts_branches_fk FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE accounts ADD CONSTRAINT accounts_clients_fk FOREIGN KEY (client_id) REFERENCES clients (client_id);
ALTER TABLE cards ADD CONSTRAINT cards_accounts_fk FOREIGN KEY (account_id) REFERENCES accounts (account_id);
ALTER TABLE transactions ADD CONSTRAINT transactions_accounts_fk FOREIGN KEY (account_id) REFERENCES accounts (account_id);
ALTER TABLE loans ADD CONSTRAINT loans_clients_fk FOREIGN KEY (client_id) REFERENCES clients (client_id);
ALTER TABLE loan_payments ADD CONSTRAINT loan_payments_loans_fk FOREIGN KEY (loan_id) REFERENCES loans (loan_id) ON DELETE CASCADE;
ALTER TABLE beneficiaries ADD CONSTRAINT beneficiaries_clients_fk FOREIGN KEY (client_id) REFERENCES clients (client_id) ON DELETE CASCADE;
ALTER TABLE loan_collateral ADD CONSTRAINT loan_collateral_loans_fk FOREIGN KEY (loan_id) REFERENCES loans (loan_id) ON DELETE CASCADE;
CREATE INDEX transactions_account_idx ON transactions (account_id, booked_at);
`,
  },
  {
    id: 'blog', icon: '📝', tables: 9,
    name: { uk: 'Блог / CMS', en: 'Blog / CMS' },
    desc: { uk: 'Автори, публікації, рубрики, теги, коментарі, медіа, підписники, ревізії', en: 'Authors, posts, sections, tags, comments, media, subscribers, revisions' },
    ddl: `
CREATE TABLE authors (
  author_id ${ID},
  display_name VARCHAR2(100 CHAR) NOT NULL,
  email VARCHAR2(255 CHAR) NOT NULL,
  bio CLOB,
  CONSTRAINT authors_pk PRIMARY KEY (author_id),
  CONSTRAINT authors_email_un UNIQUE (email)
);
COMMENT ON TABLE authors IS 'Автори';

CREATE TABLE sections (
  section_id ${ID},
  slug VARCHAR2(100 CHAR) NOT NULL,
  title VARCHAR2(200 CHAR) NOT NULL,
  CONSTRAINT sections_pk PRIMARY KEY (section_id),
  CONSTRAINT sections_slug_un UNIQUE (slug)
);
COMMENT ON TABLE sections IS 'Рубрики';

CREATE TABLE posts (
  post_id ${ID},
  author_id NUMBER NOT NULL,
  section_id NUMBER,
  slug VARCHAR2(200 CHAR) NOT NULL,
  title VARCHAR2(300 CHAR) NOT NULL,
  body CLOB,
  status VARCHAR2(12 CHAR) DEFAULT 'DRAFT' NOT NULL,
  published_at TIMESTAMP,
  CONSTRAINT posts_pk PRIMARY KEY (post_id),
  CONSTRAINT posts_slug_un UNIQUE (slug)
);
COMMENT ON TABLE posts IS 'Публікації';

CREATE TABLE tags (
  tag_id ${ID},
  name VARCHAR2(50 CHAR) NOT NULL,
  CONSTRAINT tags_pk PRIMARY KEY (tag_id),
  CONSTRAINT tags_name_un UNIQUE (name)
);
COMMENT ON TABLE tags IS 'Теги';

CREATE TABLE post_tags (
  post_id NUMBER NOT NULL,
  tag_id NUMBER NOT NULL,
  CONSTRAINT post_tags_pk PRIMARY KEY (post_id, tag_id)
);
COMMENT ON TABLE post_tags IS 'Звʼязок публікацій і тегів (M:N)';

CREATE TABLE comments (
  comment_id ${ID},
  post_id NUMBER NOT NULL,
  parent_id NUMBER,
  author_name VARCHAR2(100 CHAR) NOT NULL,
  body VARCHAR2(4000 CHAR) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT comments_pk PRIMARY KEY (comment_id)
);
COMMENT ON TABLE comments IS 'Коментарі';

CREATE TABLE media (
  media_id ${ID},
  post_id NUMBER,
  url VARCHAR2(500 CHAR) NOT NULL,
  kind VARCHAR2(10 CHAR) DEFAULT 'IMAGE' NOT NULL,
  uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT media_pk PRIMARY KEY (media_id),
  CONSTRAINT media_kind_ck CHECK (kind IN ('IMAGE', 'VIDEO', 'FILE'))
);
COMMENT ON TABLE media IS 'Медіафайли публікацій';

CREATE TABLE subscribers (
  subscriber_id ${ID},
  email VARCHAR2(255 CHAR) NOT NULL,
  subscribed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  confirmed CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT subscribers_pk PRIMARY KEY (subscriber_id),
  CONSTRAINT subscribers_email_un UNIQUE (email)
);
COMMENT ON TABLE subscribers IS 'Підписники розсилки';

CREATE TABLE post_revisions (
  revision_id ${ID},
  post_id NUMBER NOT NULL,
  editor_id NUMBER NOT NULL,
  body CLOB,
  edited_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT post_revisions_pk PRIMARY KEY (revision_id)
);
COMMENT ON TABLE post_revisions IS 'Історія редагувань публікації';

ALTER TABLE posts ADD CONSTRAINT posts_authors_fk FOREIGN KEY (author_id) REFERENCES authors (author_id);
ALTER TABLE posts ADD CONSTRAINT posts_sections_fk FOREIGN KEY (section_id) REFERENCES sections (section_id) ON DELETE SET NULL;
ALTER TABLE post_tags ADD CONSTRAINT post_tags_posts_fk FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE;
ALTER TABLE post_tags ADD CONSTRAINT post_tags_tags_fk FOREIGN KEY (tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_posts_fk FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_parent_fk FOREIGN KEY (parent_id) REFERENCES comments (comment_id);
ALTER TABLE media ADD CONSTRAINT media_posts_fk FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE;
ALTER TABLE post_revisions ADD CONSTRAINT post_revisions_posts_fk FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE;
ALTER TABLE post_revisions ADD CONSTRAINT post_revisions_authors_fk FOREIGN KEY (editor_id) REFERENCES authors (author_id);
`,
  },
  {
    id: 'warehouse', icon: '📦', tables: 9,
    name: { uk: 'Склад і логістика', en: 'Warehouse & logistics' },
    desc: { uk: 'Склади, постачальники, номенклатура, залишки, накладні, категорії, переміщення', en: 'Warehouses, suppliers, items, stock, waybills, categories, transfers' },
    ddl: `
CREATE TABLE warehouses (
  warehouse_id ${ID},
  name VARCHAR2(100 CHAR) NOT NULL,
  city VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT warehouses_pk PRIMARY KEY (warehouse_id)
);
COMMENT ON TABLE warehouses IS 'Склади';

CREATE TABLE suppliers (
  supplier_id ${ID},
  name VARCHAR2(200 CHAR) NOT NULL,
  edrpou VARCHAR2(10 CHAR),
  contact_phone VARCHAR2(20 CHAR),
  CONSTRAINT suppliers_pk PRIMARY KEY (supplier_id)
);
COMMENT ON TABLE suppliers IS 'Постачальники';
COMMENT ON COLUMN suppliers.edrpou IS 'Код ЄДРПОУ';

CREATE TABLE items (
  item_id ${ID},
  category_id NUMBER,
  sku VARCHAR2(40 CHAR) NOT NULL,
  name VARCHAR2(200 CHAR) NOT NULL,
  unit VARCHAR2(10 CHAR) DEFAULT 'шт' NOT NULL,
  weight_kg NUMBER(10,3),
  CONSTRAINT items_pk PRIMARY KEY (item_id),
  CONSTRAINT items_sku_un UNIQUE (sku)
);
COMMENT ON TABLE items IS 'Номенклатура';

CREATE TABLE stock (
  warehouse_id NUMBER NOT NULL,
  item_id NUMBER NOT NULL,
  quantity NUMBER(12,3) DEFAULT 0 NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT stock_pk PRIMARY KEY (warehouse_id, item_id)
);
COMMENT ON TABLE stock IS 'Залишки';

CREATE TABLE waybills (
  waybill_id ${ID},
  warehouse_id NUMBER NOT NULL,
  supplier_id NUMBER,
  kind VARCHAR2(10 CHAR) NOT NULL,
  doc_no VARCHAR2(30 CHAR) NOT NULL,
  doc_date DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT waybills_pk PRIMARY KEY (waybill_id)
);
COMMENT ON TABLE waybills IS 'Накладні (прихід / витрата)';

CREATE TABLE waybill_lines (
  waybill_id NUMBER NOT NULL,
  line_no NUMBER(4) NOT NULL,
  item_id NUMBER NOT NULL,
  quantity NUMBER(12,3) NOT NULL,
  price NUMBER(12,2),
  CONSTRAINT waybill_lines_pk PRIMARY KEY (waybill_id, line_no)
);
COMMENT ON TABLE waybill_lines IS 'Рядки накладних';

CREATE TABLE item_categories (
  category_id ${ID},
  parent_id NUMBER,
  name VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT item_categories_pk PRIMARY KEY (category_id)
);
COMMENT ON TABLE item_categories IS 'Категорії номенклатури';

CREATE TABLE item_suppliers (
  item_id NUMBER NOT NULL,
  supplier_id NUMBER NOT NULL,
  supplier_sku VARCHAR2(40 CHAR),
  lead_time_days NUMBER(4) DEFAULT 0 NOT NULL,
  CONSTRAINT item_suppliers_pk PRIMARY KEY (item_id, supplier_id)
);
COMMENT ON TABLE item_suppliers IS 'Хто з постачальників що постачає (M:N)';

CREATE TABLE stock_transfers (
  transfer_id ${ID},
  item_id NUMBER NOT NULL,
  from_warehouse_id NUMBER NOT NULL,
  to_warehouse_id NUMBER NOT NULL,
  quantity NUMBER(12,3) NOT NULL,
  transferred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT stock_transfers_pk PRIMARY KEY (transfer_id),
  CONSTRAINT stock_transfers_qty_ck CHECK (quantity > 0)
);
COMMENT ON TABLE stock_transfers IS 'Переміщення між складами';

ALTER TABLE items ADD CONSTRAINT items_categories_fk FOREIGN KEY (category_id) REFERENCES item_categories (category_id);
ALTER TABLE item_categories ADD CONSTRAINT item_categories_parent_fk FOREIGN KEY (parent_id) REFERENCES item_categories (category_id);
ALTER TABLE stock ADD CONSTRAINT stock_warehouses_fk FOREIGN KEY (warehouse_id) REFERENCES warehouses (warehouse_id);
ALTER TABLE stock ADD CONSTRAINT stock_items_fk FOREIGN KEY (item_id) REFERENCES items (item_id);
ALTER TABLE waybills ADD CONSTRAINT waybills_warehouses_fk FOREIGN KEY (warehouse_id) REFERENCES warehouses (warehouse_id);
ALTER TABLE waybills ADD CONSTRAINT waybills_suppliers_fk FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id);
ALTER TABLE waybill_lines ADD CONSTRAINT waybill_lines_waybills_fk FOREIGN KEY (waybill_id) REFERENCES waybills (waybill_id) ON DELETE CASCADE;
ALTER TABLE waybill_lines ADD CONSTRAINT waybill_lines_items_fk FOREIGN KEY (item_id) REFERENCES items (item_id);
ALTER TABLE item_suppliers ADD CONSTRAINT item_suppliers_items_fk FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE;
ALTER TABLE item_suppliers ADD CONSTRAINT item_suppliers_suppliers_fk FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id) ON DELETE CASCADE;
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_items_fk FOREIGN KEY (item_id) REFERENCES items (item_id);
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_from_fk FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (warehouse_id);
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_to_fk FOREIGN KEY (to_warehouse_id) REFERENCES warehouses (warehouse_id);
`,
  },
  {
    id: 'clinic', icon: '🏥', tables: 9,
    name: { uk: 'Клініка', en: 'Clinic' },
    desc: { uk: 'Пацієнти, лікарі, спеціальності, прийоми, діагнози, рецепти, страхування, аналізи', en: 'Patients, doctors, specialties, visits, diagnoses, prescriptions, insurance, lab tests' },
    ddl: `
CREATE TABLE specialties (
  specialty_id ${ID},
  name VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT specialties_pk PRIMARY KEY (specialty_id)
);
COMMENT ON TABLE specialties IS 'Лікарські спеціальності';

CREATE TABLE doctors (
  doctor_id ${ID},
  specialty_id NUMBER NOT NULL,
  full_name VARCHAR2(200 CHAR) NOT NULL,
  room VARCHAR2(10 CHAR),
  CONSTRAINT doctors_pk PRIMARY KEY (doctor_id)
);
COMMENT ON TABLE doctors IS 'Лікарі';

CREATE TABLE patients (
  patient_id ${ID},
  full_name VARCHAR2(200 CHAR) NOT NULL,
  birth_date DATE NOT NULL,
  phone VARCHAR2(20 CHAR),
  declaration_no VARCHAR2(20 CHAR),
  CONSTRAINT patients_pk PRIMARY KEY (patient_id)
);
COMMENT ON TABLE patients IS 'Пацієнти';
COMMENT ON COLUMN patients.declaration_no IS 'Номер декларації з сімейним лікарем';

CREATE TABLE visits (
  visit_id ${ID},
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  visit_at TIMESTAMP NOT NULL,
  status VARCHAR2(12 CHAR) DEFAULT 'PLANNED' NOT NULL,
  notes CLOB,
  CONSTRAINT visits_pk PRIMARY KEY (visit_id)
);
COMMENT ON TABLE visits IS 'Прийоми';

CREATE TABLE diagnoses (
  diagnosis_id ${ID},
  visit_id NUMBER NOT NULL,
  icd10_code VARCHAR2(8 CHAR) NOT NULL,
  description VARCHAR2(400 CHAR),
  CONSTRAINT diagnoses_pk PRIMARY KEY (diagnosis_id)
);
COMMENT ON TABLE diagnoses IS 'Діагнози (МКХ-10)';

CREATE TABLE prescriptions (
  prescription_id ${ID},
  visit_id NUMBER NOT NULL,
  medicine VARCHAR2(200 CHAR) NOT NULL,
  dosage VARCHAR2(100 CHAR) NOT NULL,
  days NUMBER(3),
  CONSTRAINT prescriptions_pk PRIMARY KEY (prescription_id)
);
COMMENT ON TABLE prescriptions IS 'Рецепти';

CREATE TABLE insurance_policies (
  policy_id ${ID},
  patient_id NUMBER NOT NULL,
  provider VARCHAR2(150 CHAR) NOT NULL,
  policy_no VARCHAR2(30 CHAR) NOT NULL,
  valid_to DATE NOT NULL,
  CONSTRAINT insurance_policies_pk PRIMARY KEY (policy_id),
  CONSTRAINT insurance_policies_no_un UNIQUE (policy_no)
);
COMMENT ON TABLE insurance_policies IS 'Страхові поліси пацієнтів';

CREATE TABLE lab_tests (
  test_id ${ID},
  visit_id NUMBER NOT NULL,
  test_name VARCHAR2(150 CHAR) NOT NULL,
  result VARCHAR2(400 CHAR),
  performed_at TIMESTAMP,
  CONSTRAINT lab_tests_pk PRIMARY KEY (test_id)
);
COMMENT ON TABLE lab_tests IS 'Лабораторні аналізи';

CREATE TABLE vaccinations (
  vaccination_id ${ID},
  patient_id NUMBER NOT NULL,
  vaccine_name VARCHAR2(150 CHAR) NOT NULL,
  dose_no NUMBER(2) DEFAULT 1 NOT NULL,
  given_at DATE NOT NULL,
  CONSTRAINT vaccinations_pk PRIMARY KEY (vaccination_id)
);
COMMENT ON TABLE vaccinations IS 'Щеплення';

ALTER TABLE doctors ADD CONSTRAINT doctors_specialties_fk FOREIGN KEY (specialty_id) REFERENCES specialties (specialty_id);
ALTER TABLE visits ADD CONSTRAINT visits_patients_fk FOREIGN KEY (patient_id) REFERENCES patients (patient_id);
ALTER TABLE visits ADD CONSTRAINT visits_doctors_fk FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id);
ALTER TABLE diagnoses ADD CONSTRAINT diagnoses_visits_fk FOREIGN KEY (visit_id) REFERENCES visits (visit_id) ON DELETE CASCADE;
ALTER TABLE prescriptions ADD CONSTRAINT prescriptions_visits_fk FOREIGN KEY (visit_id) REFERENCES visits (visit_id) ON DELETE CASCADE;
ALTER TABLE insurance_policies ADD CONSTRAINT insurance_policies_patients_fk FOREIGN KEY (patient_id) REFERENCES patients (patient_id) ON DELETE CASCADE;
ALTER TABLE lab_tests ADD CONSTRAINT lab_tests_visits_fk FOREIGN KEY (visit_id) REFERENCES visits (visit_id) ON DELETE CASCADE;
ALTER TABLE vaccinations ADD CONSTRAINT vaccinations_patients_fk FOREIGN KEY (patient_id) REFERENCES patients (patient_id) ON DELETE CASCADE;
CREATE INDEX visits_doctor_idx ON visits (doctor_id, visit_at);
`,
  },
  {
    id: 'obl', icon: '⚾', tables: 7,
    // hand placement mirroring the Oracle Academy ERD (autoLayout crosses the M:N lines here)
    layout: {
      SALES_REPRESENTATIVE: [40, 40], CUSTOMER: [480, 40], TEAM: [920, 40],
      ORDERS: [480, 360], ORDER_ITEM: [920, 400], ITEM: [1360, 360], INVENTORY_LIST: [1360, 40],
    },
    name: { uk: 'OBL Store (Oracle Academy)', en: 'OBL Store (Oracle Academy)' },
    desc: { uk: 'Навчальний проєкт Oracle Academy: покупці, команди, продавці, замовлення, товари, склад. Зв\'язки 1:1, 1:N і M:N', en: 'Oracle Academy course project: customers, teams, sales reps, orders, items, inventory. 1:1, 1:N and M:N relations' },
    ddl: `
CREATE TABLE sales_representative (
  id NUMBER(10) NOT NULL,
  email VARCHAR2(200) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  address VARCHAR2(300) NOT NULL,
  phone_number VARCHAR2(20) NOT NULL,
  commission_rate NUMBER(5,2) NOT NULL,
  CONSTRAINT sales_representative_pk PRIMARY KEY (id),
  CONSTRAINT sales_rep_email_un UNIQUE (email)
);
COMMENT ON TABLE sales_representative IS 'Продавці-консультанти: офіційно обслуговують команди';

CREATE TABLE customer (
  customer_number NUMBER(10) NOT NULL,
  email VARCHAR2(200) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  address VARCHAR2(300) NOT NULL,
  phone_number VARCHAR2(20) NOT NULL,
  current_balance NUMBER(10,2) NOT NULL,
  team_they_belong_to VARCHAR2(100),
  sales_representative_id NUMBER(10),
  CONSTRAINT customer_pk PRIMARY KEY (customer_number),
  CONSTRAINT customer_email_un UNIQUE (email)
);
COMMENT ON TABLE customer IS 'Покупці: індивідуальні клієнти і представники команд';
COMMENT ON COLUMN customer.sales_representative_id IS 'Може бути призначений продавець (необовʼязковий звʼязок)';

CREATE TABLE team (
  id NUMBER(10) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  number_of_players NUMBER(4) NOT NULL,
  discount NUMBER(5,2),
  customer_number NUMBER(10) NOT NULL,
  CONSTRAINT team_pk PRIMARY KEY (id),
  CONSTRAINT team_customer_un UNIQUE (customer_number)
);
COMMENT ON TABLE team IS 'Команди: знижка залежить від кількості гравців';
COMMENT ON COLUMN team.customer_number IS 'Представник команди, звʼязок 1:1';

CREATE TABLE inventory_list (
  id NUMBER(10) NOT NULL,
  cost_of_the_unit NUMBER(10,2) NOT NULL,
  units_on_hand NUMBER(8) NOT NULL,
  CONSTRAINT inventory_list_pk PRIMARY KEY (id)
);
COMMENT ON TABLE inventory_list IS 'Списки товарів на складі';

CREATE TABLE item (
  item_number NUMBER(10) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  description VARCHAR2(1000) NOT NULL,
  price NUMBER(10,2) NOT NULL,
  category VARCHAR2(100) NOT NULL,
  color VARCHAR2(50),
  item_size VARCHAR2(20),
  inventory_list_id NUMBER(10) NOT NULL,
  CONSTRAINT item_pk PRIMARY KEY (item_number)
);
COMMENT ON TABLE item IS 'Товари: мʼячі, бутси, рукавички, футболки, шорти';

CREATE TABLE orders (
  id NUMBER(10) NOT NULL,
  order_date DATE NOT NULL,
  items_purchased VARCHAR2(1000) NOT NULL,
  item_size VARCHAR2(20) NOT NULL,
  color VARCHAR2(50) NOT NULL,
  price NUMBER(10,2) NOT NULL,
  number_of_units NUMBER(6) NOT NULL,
  total_order_price NUMBER(10,2) NOT NULL,
  customer_number NUMBER(10) NOT NULL,
  CONSTRAINT orders_pk PRIMARY KEY (id)
);
COMMENT ON TABLE orders IS 'Замовлення (ORDER зарезервоване слово Oracle)';

CREATE TABLE order_item (
  order_id NUMBER(10) NOT NULL,
  item_number NUMBER(10) NOT NULL,
  CONSTRAINT order_item_pk PRIMARY KEY (order_id, item_number)
);
COMMENT ON TABLE order_item IS 'Таблиця перетину для звʼязку M:N між замовленнями і товарами';

ALTER TABLE customer ADD CONSTRAINT customer_sales_rep_fk FOREIGN KEY (sales_representative_id) REFERENCES sales_representative (id);
ALTER TABLE team ADD CONSTRAINT team_customer_fk FOREIGN KEY (customer_number) REFERENCES customer (customer_number);
ALTER TABLE item ADD CONSTRAINT item_inventory_list_fk FOREIGN KEY (inventory_list_id) REFERENCES inventory_list (id);
ALTER TABLE orders ADD CONSTRAINT orders_customer_fk FOREIGN KEY (customer_number) REFERENCES customer (customer_number);
ALTER TABLE order_item ADD CONSTRAINT order_item_orders_fk FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_item ADD CONSTRAINT order_item_item_fk FOREIGN KEY (item_number) REFERENCES item (item_number);
`,
  },
];

// Column presets for the properties panel
export const COLUMN_PRESETS = [
  { id: 'id', label: { uk: 'ID', en: 'ID' }, cols: [{ name: 'ID', type: 'NUMBER', pk: true, identity: true, nullable: false }] },
  { id: 'audit', label: { uk: 'Аудит', en: 'Audit' }, cols: [
    { name: 'CREATED_AT', type: 'TIMESTAMP', default: 'SYSTIMESTAMP', nullable: false },
    { name: 'CREATED_BY', type: 'VARCHAR2(100 CHAR)' },
    { name: 'UPDATED_AT', type: 'TIMESTAMP' },
    { name: 'UPDATED_BY', type: 'VARCHAR2(100 CHAR)' },
  ] },
  { id: 'name', label: { uk: 'Назва + опис', en: 'Name + description' }, cols: [
    { name: 'NAME', type: 'VARCHAR2(200 CHAR)', nullable: false },
    { name: 'DESCRIPTION', type: 'VARCHAR2(4000 CHAR)' },
  ] },
  { id: 'status', label: { uk: 'Статус', en: 'Status' }, cols: [{ name: 'STATUS', type: 'VARCHAR2(20 CHAR)', default: "'NEW'", nullable: false }] },
  { id: 'active', label: { uk: 'Активний', en: 'Active flag' }, cols: [{ name: 'IS_ACTIVE', type: 'CHAR(1)', default: "'Y'", nullable: false }] },
  { id: 'email', label: { uk: 'Email + телефон', en: 'Email + phone' }, cols: [
    { name: 'EMAIL', type: 'VARCHAR2(255 CHAR)' },
    { name: 'PHONE', type: 'VARCHAR2(20 CHAR)' },
  ] },
  { id: 'money', label: { uk: 'Сума + валюта', en: 'Amount + currency' }, cols: [
    { name: 'AMOUNT', type: 'NUMBER(18,2)', nullable: false },
    { name: 'CURRENCY', type: 'CHAR(3)', default: "'UAH'", nullable: false },
  ] },
  { id: 'soft', label: { uk: 'Мʼяке видалення', en: 'Soft delete' }, cols: [{ name: 'DELETED_AT', type: 'TIMESTAMP' }] },
];
